// Castle Dracula, 1897 (after Bram Stoker): a castle in the Carpathians, the
// pass snowed shut and the gate barred, and somebody dead among the Count's
// guests, the party from England and the few who belong to the place. The
// Count is a guest like any other on the sheet, however the night falls.
// Everything not its own (the roles, the papers, the way the people talk) it
// shares with the manor.

import type { SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'
import { CASTLE_SILHOUETTES } from './silhouettes'
import { CASTLE_GLYPHS } from './items'

export const castle1897: SettingPack = {
  ...manor1920s,
  id: 'castle1897',
  title: 'Castle Dracula, 1897',
  victims: [
    {
      id: 'count',
      name: 'Count Dracula',
      shortName: 'the Count',
      title: 'master of the castle',
      pronouns: 'he',
      firstName: 'the Count',
      lastName: 'Dracula',
      respectful: 'the Count',
      parental: 'Father',
      character: 'count',
      motives: ['hostile', 'indebted', 'exposed', 'dismissed', 'rival', 'forbidden', 'beneficiary'],
      occasions: ['arrival', 'nightfall', 'hunt'],
    },
    {
      id: 'lucy',
      name: 'Miss Lucy Westenra',
      shortName: 'Miss Westenra',
      title: 'a guest of the castle',
      pronouns: 'she',
      firstName: 'Lucy',
      lastName: 'Westenra',
      respectful: 'Miss Westenra',
      parental: 'Mother',
      character: 'lucy',
      motives: ['hostile', 'jilted', 'beneficiary', 'exposed', 'forbidden'],
      occasions: ['nightfall', 'hunt'],
    },
    {
      id: 'godalming',
      name: 'Arthur Holmwood, Lord Godalming',
      shortName: 'Lord Godalming',
      title: 'a guest of the castle',
      pronouns: 'he',
      firstName: 'Arthur',
      lastName: 'Holmwood',
      respectful: 'his lordship',
      parental: 'Father',
      character: 'godalming',
      motives: ['hostile', 'indebted', 'jilted', 'beneficiary', 'rival', 'exposed'],
      occasions: ['arrival', 'hunt'],
    },
  ],
  place: {
    name: 'the castle',
    here: 'this castle',
    people: 'the castle',
    plan: 'the plan of the castle',
    gathering:
      'The wolves in the pass, the gate barred against the night, and everybody gathered in the great hall by candlelight, each with something to say before the questioning begins.',
    weather: 'the storm',
    one: 'guest',
    ones: 'guests',
    passage: 'the stair in the wall',
    placeName: 'Castle Dracula',
    placeShort: 'the Castle',
    at: 'at',
  },
  weather: 'storm',
  ambience: 'rain',
  mapStyles: ['wings', 'cross', 'courtyard'],
  windowLabel: 'between nine and ten o’clock at night, as the wolves began',
  windowClock: 'Between 9 and 10 p.m. this evening',
  suspectsLine: 'The {n} guests and people of the castle, snowed in at Castle Dracula',
  chiefNote: 'The pass is snowed shut till morning and the gate is barred till midnight. You’ve got till then to find out who did it.',
  windowFrom: 'nine o’clock',

  rooms: [
    {
      id: 'hall',
      name: 'the great hall',
      searchFlavor: [
        'A table laid for a host who does not eat, a fire that gives more smoke than heat, and the bell-ropes hanging in the dark above the dais.',
        'Candles guttering in their iron stands. The old armour along the wall has not been touched in a century, and the dust says so.',
      ],
    },
    {
      id: 'library',
      name: 'the library',
      searchFlavor: [
        'Books in English, shelves of them: bradshaws, almanacs, atlases, and a directory of London, the pages thumbed soft.',
        'A reading lamp with the wick turned low, and a chair drawn up to it. The shelf behind has a gap where one book has been taken out.',
      ],
    },
    {
      id: 'chapel',
      name: 'the chapel',
      searchFlavor: [
        'Long boxes of earth stand in a row beneath the broken altar, lids ajar, and the air smells of old soil and colder stone.',
        'A cracked crucifix on the wall, a prie-dieu with no cushion, and a store of sharpened wood by the door, tidily stacked.',
      ],
    },
    {
      id: 'crypt',
      name: 'the crypt',
      searchFlavor: [
        'Tombs with their names worn off, a vault stair slick with damp, and somewhere below, water dripping into the dark.',
        'The cold comes up out of the floor. A lantern has been left on a ledge, burned down to its last inch.',
      ],
    },
    {
      id: 'tower',
      name: 'the east tower room',
      where: 'in the east tower room',
      searchFlavor: [
        'A narrow bed, a wash-stand, and a window with a drop of a thousand feet beneath it. The shutters knock in the wind.',
        'Somebody’s travelling trunk, strapped and locked, and a pair of boots set outside the door as if for a servant who does not come.',
      ],
    },
    {
      id: 'courtyard',
      name: 'the courtyard',
      where: 'in the courtyard',
      kind: 'outdoor',
      searchFlavor: [
        'Snow blowing across the flags, a dry well-head, and the great gate barred with a beam no one man could lift.',
        'Wolf tracks in the drift against the wall. The wind brings the howling down from the pass.',
      ],
    },
    {
      id: 'kitchens',
      name: 'the kitchens',
      searchFlavor: [
        'A cold hearth, a copper pot gone green, and a heap of curved native knives on the dresser, each as long as a forearm.',
        'Bread that has gone hard on its board, a jug of plum brandy, and nothing in the larder that could feed a household.',
      ],
    },
    {
      id: 'study',
      name: 'the Count’s study',
      searchFlavor: [
        'A writing table with a gold chain on it, a lamp that gives no smoke, and a mirror conspicuously absent from the wall.',
        'Neat stacks of letters in several hands and several languages, and a ledger kept in a script too small to read.',
      ],
    },
    {
      id: 'battlements',
      name: 'the battlements',
      where: 'on the battlements',
      kind: 'outdoor',
      searchFlavor: [
        'Frost on the parapet, the pass a black gash below, and the wind loud enough to cover any cry.',
        'A broken embrasure, a drift of snow against the stair door, and a long, long way down.',
      ],
    },
  ],
  sceneRooms: ['hall', 'library', 'chapel', 'crypt', 'tower', 'courtyard', 'kitchens', 'study', 'battlements'],
  valuableRooms: ['study', 'library', 'tower'],
  docRooms: ['study', 'library', 'chapel'],

  means: [
    { id: 'stillroom', label: 'has the run of the Professor’s laudanum and the castle’s medicine chest' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the kitchens and their knives' },
    { id: 'firearms', label: 'carries a revolver' },
    { id: 'height', label: 'knows the stair to the battlements, and is not afraid of it' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a flask of laudanum from the medicine chest, a good deal emptier than it was',
      methodLine: 'poisoned by a hand with the run of the laudanum and the medicine chest',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['hall', 'library', 'chapel', 'tower', 'kitchens', 'study'],
    },
    {
      id: 'stake',
      means: 'strength',
      weaponName: 'a sharpened stake from the chapel’s store, wiped and laid back among the others',
      methodLine: 'staked by someone with the strength for it',
      titled: 'The Stake',
    },
    {
      id: 'fall',
      means: 'height',
      weaponName: 'a broken place in the parapet, fresh scrape marks on the stone, and the pass a thousand feet below',
      methodLine: 'put from the battlements by someone who knows the stair and does not fear the height',
      titled: 'The Battlements',
      rooms: ['battlements', 'tower'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a bell-rope from the great hall, cut short, the end still frayed',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Bell-Rope',
      rooms: ['hall', 'library', 'chapel', 'crypt', 'tower', 'study'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'a revolver, one chamber fired, wiped and put back where it was found',
      methodLine: 'shot by somebody who carries a revolver',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a kukri from the kitchens, wiped and laid back on the dresser with the rest',
      methodLine: 'cut down by someone with the run of the kitchens and their knives',
      titled: 'The Knife',
    },
  ],

  characters: [
    {
      id: 'count',
      name: 'Count Dracula',
      shortName: 'the Count',
      title: 'master of the castle',
      portrait: '🏰',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.05, perfume: 0, spectacles: 0.1, gloves: 0.9 },
      means: ['strength', 'height', 'kitchen'],
      manners: { gracious: 1, donnish: 0.7, prickly: 0.6 },
      motives: { hostile: 0.7, rival: 0.7, exposed: 0.6, indebted: 0.4, beneficiary: 0.3 },
      voice: { pitch: 124, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.8 },
      blurb: 'Keeps the castle, the cellar and the hours, and receives every guest at the door himself.',
    },
    {
      id: 'harker',
      name: 'Mr. Jonathan Harker',
      shortName: 'Mr. Harker',
      title: 'solicitor’s clerk',
      portrait: '📓',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.3, perfume: 0.1, spectacles: 0.5, gloves: 0.4 },
      means: ['firearms', 'strength'],
      manners: { deferential: 1, official: 0.8 },
      motives: { hostile: 0.7, exposed: 0.7, indebted: 0.5, dismissed: 0.4, forbidden: 0.3 },
      voice: { pitch: 176, wave: 'sine', lilt: 3, clip: 0.06, ring: 0.3 },
      blurb: 'Came out on the firm’s business with a diary and a good opinion of everybody, and keeps both in his breast pocket.',
    },
    {
      id: 'mina',
      name: 'Mrs. Mina Harker',
      shortName: 'Mrs. Harker',
      title: 'a schoolmistress, and a typewriter of notes',
      portrait: '✒️',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.05, perfume: 0.4, spectacles: 0.3, gloves: 0.9 },
      means: ['stillroom', 'kitchen'],
      manners: { reserved: 1, gracious: 0.8 },
      motives: { hostile: 0.6, exposed: 0.6, forbidden: 0.5, jilted: 0.3 },
      voice: { pitch: 248, wave: 'sine', lilt: 2.5, clip: 0.06, ring: 0.3 },
      blurb: 'Writes everything down in shorthand, types it up at night, and has opinions about both.',
    },
    {
      id: 'lucy',
      name: 'Miss Lucy Westenra',
      shortName: 'Miss Westenra',
      title: 'a young lady of Hillingham',
      portrait: '🌹',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.02, perfume: 0.9, spectacles: 0.1, gloves: 0.8 },
      means: ['stillroom'],
      manners: { gracious: 1, dramatic: 0.8 },
      motives: { jilted: 0.8, forbidden: 0.7, exposed: 0.6, hostile: 0.4, beneficiary: 0.4 },
      voice: { pitch: 270, wave: 'sine', lilt: 4.5, clip: 0.05, ring: 0.3 },
      blurb: 'Had three proposals in a single afternoon and talks of little else, though she is sleeping badly.',
    },
    {
      id: 'godalming',
      name: 'Arthur Holmwood, Lord Godalming',
      shortName: 'Lord Godalming',
      title: 'a peer, lately come into the title',
      portrait: '🎩',
      pronouns: 'he',
      leanings: { cane: 0.7, smoker: 0.6, perfume: 0.3, spectacles: 0.05, gloves: 0.6 },
      means: ['firearms', 'strength'],
      manners: { boastful: 1, hearty: 0.8 },
      motives: { hostile: 0.8, jilted: 0.6, indebted: 0.5, rival: 0.6, beneficiary: 0.5 },
      voice: { pitch: 150, wave: 'sawtooth', lilt: 3.5, clip: 0.07, ring: 0.5 },
      blurb: 'Inherited the title in the spring, the estate with it, and has been telling people so ever since.',
    },
    {
      id: 'seward',
      name: 'Dr. John Seward',
      shortName: 'Dr. Seward',
      title: 'physician, of the asylum at Purfleet',
      portrait: '💉',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.9, perfume: 0.1, spectacles: 0.5, gloves: 0.3 },
      means: ['stillroom', 'firearms'],
      manners: { official: 1, donnish: 0.8 },
      motives: { jilted: 0.8, hostile: 0.6, rival: 0.6, exposed: 0.4 },
      voice: { pitch: 140, wave: 'triangle', lilt: 2, clip: 0.08, ring: 0.7 },
      blurb: 'Keeps a phonograph diary, a case-book of the mind, and a bottle of chloral he does not mention.',
    },
    {
      id: 'quincey',
      name: 'Mr. Quincey Morris',
      shortName: 'Mr. Morris',
      title: 'of Texas',
      portrait: '🤠',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.95, perfume: 0.05, spectacles: 0.1, gloves: 0.3 },
      means: ['firearms', 'strength', 'kitchen'],
      manners: { hearty: 1, blunt: 0.9 },
      motives: { jilted: 0.8, hostile: 0.6, rival: 0.5, indebted: 0.3 },
      voice: { pitch: 132, wave: 'sawtooth', lilt: 3, clip: 0.08, ring: 0.6 },
      blurb: 'Carries a Winchester, a bowie knife and a fine opinion of any man who will drink with him.',
    },
    {
      id: 'vanhelsing',
      name: 'Professor Abraham Van Helsing',
      shortName: 'Professor Van Helsing',
      title: 'of Amsterdam, physician and philosopher',
      portrait: '🔍',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.3, perfume: 0.05, spectacles: 1, gloves: 0.4 },
      means: ['stillroom', 'strength', 'height'],
      manners: { donnish: 1, rambling: 0.9 },
      motives: { hostile: 0.8, exposed: 0.6, rival: 0.5 },
      voice: { pitch: 146, wave: 'triangle', lilt: 4, clip: 0.09, ring: 0.7 },
      blurb: 'Has a degree in everything, a bag that clinks, and a way of answering a question with a longer one.',
    },
    {
      id: 'renfield',
      name: 'Mr. R. M. Renfield',
      shortName: 'Mr. Renfield',
      title: 'a patient, of independent means',
      portrait: '🕷️',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.2, perfume: 0.02, spectacles: 0.3, gloves: 0.1 },
      means: ['strength', 'kitchen', 'height'],
      manners: { rambling: 1, dramatic: 0.9 },
      motives: { hostile: 0.7, indebted: 0.6, exposed: 0.5, dismissed: 0.4 },
      voice: { pitch: 192, wave: 'square', lilt: 6, clip: 0.05, ring: 0.4 },
      blurb: 'Has a great deal to say about the Master, the flies, and the order in which the guests ought to be fed.',
    },
    {
      id: 'bride',
      name: 'the Weird Sister',
      shortName: 'the Sister',
      title: 'one of the three sisters of the castle',
      portrait: '🕯️',
      pronouns: 'she',
      leanings: { cane: 0.02, smoker: 0.02, perfume: 0.6, spectacles: 0.02, gloves: 0.3 },
      means: ['strength', 'height', 'kitchen'],
      manners: { dramatic: 1, prickly: 0.8 },
      motives: { jilted: 0.8, forbidden: 0.7, hostile: 0.6, exposed: 0.4 },
      voice: { pitch: 256, wave: 'sawtooth', lilt: 5, clip: 0.06, ring: 0.6 },
      blurb: 'Fair, high-coloured and silent for hours together, and laughs at the table when no one has spoken.',
    },
    {
      id: 'mrswestenra',
      name: 'Mrs. Westenra',
      shortName: 'Mrs. Westenra',
      title: 'Lucy’s mother',
      portrait: '🫖',
      pronouns: 'she',
      leanings: { cane: 0.2, smoker: 0.05, perfume: 0.7, spectacles: 0.6, gloves: 0.7 },
      means: ['stillroom', 'kitchen'],
      manners: { gossipy: 1, prickly: 0.6 },
      motives: { forbidden: 0.7, hostile: 0.6, exposed: 0.5, beneficiary: 0.5, indebted: 0.3 },
      voice: { pitch: 214, wave: 'square', lilt: 3, clip: 0.08, ring: 0.4 },
      blurb: 'Has a heart condition she does not like discussed, and a daughter she likes discussed a great deal.',
    },
    {
      id: 'agatha',
      name: 'Sister Agatha',
      shortName: 'Sister Agatha',
      title: 'of the hospital of St. Joseph',
      portrait: '✝️',
      pronouns: 'she',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.02, perfume: 0.05, spectacles: 0.5, gloves: 0.7 },
      means: ['stillroom', 'kitchen'],
      manners: { deferential: 1, reserved: 0.8 },
      motives: { exposed: 0.6, hostile: 0.4, dismissed: 0.5, forbidden: 0.4 },
      voice: { pitch: 232, wave: 'triangle', lilt: 1.5, clip: 0.08, ring: 0.3 },
      blurb: 'Nursed a patient from Buda-Pesth, is writing to a young man in Exeter, and prays in the chapel at odd hours.',
    },
    {
      id: 'coachman',
      name: 'the Count’s coachman',
      shortName: 'the Coachman',
      title: 'a Szgany, driver of the calèche',
      portrait: '🐴',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.05, smoker: 0.8, perfume: 0.02, spectacles: 0.02, gloves: 0.1 },
      means: ['strength', 'kitchen', 'height'],
      manners: { blunt: 1, reserved: 0.8 },
      motives: { dismissed: 0.8, hostile: 0.7, indebted: 0.6, exposed: 0.4 },
      voice: { pitch: 122, wave: 'sawtooth', lilt: 1.5, clip: 0.09, ring: 0.7 },
      blurb: 'Drives the calèche over the pass at night with four black horses, and has never been seen to be cold.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...CASTLE_SILHOUETTES,
  },
  itemArt: {
    ...manor1920s.itemArt!,
    glyphs: { ...manor1920s.itemArt!.glyphs, ...CASTLE_GLYPHS },
  },

  flavorItems: [
    'a Bradshaw’s railway guide, the Whitby page turned down',
    'a phonograph cylinder in a paper sleeve, unlabelled',
    'a rosary of wooden beads, one bead missing',
    'a sprig of dried wild rose, pressed in a prayer book',
    'a shorthand notebook with the last page torn out',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a stair in the thickness of the wall, and a cold way down to the chapel',
  bribeItem: 'a purse of old gold, with {name}’s name on a slip inside',
  keyItem: 'a great iron key, on a ring of them',
  ashesItem: 'a corner of burnt paper in the hearth, still warm',
  secondBody: '{name}, dead and silenced, the candle beside them out',
  occasions: [
    {
      id: 'arrival',
      weight: 3,
      titles: ['The Guest at the Castle', 'Through the Pass', 'A Welcome {At} {Place}'],
      sheet: 'A guest had lately arrived at the castle through the pass.',
      report: 'A guest newly arrived through the pass was being received at the castle. {Victim} was killed during the night, after the gate had been barred.',
      event: 'quarrel',
      intro: [
        'The calèche had come over the pass at dusk with a stranger inside it, and by nightfall the gate was barred and the pass snowed shut behind. At ten o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The wolves are loud in the dark, and everybody who sat down to dinner is still in the castle.',
        'The new arrival was shown to the east tower room, given a candle and a warning about the stair, and the household sat down to a late supper with a place at the table for everyone. Some hours on, {victim} was found in {scene}, quite dead, the deed done {window}. Nobody can leave before morning.',
      ],
    },
    {
      id: 'nightfall',
      weight: 2,
      titles: ['St. George’s Eve', 'Nightfall {At} {Place}', 'The Night the Dead Walk'],
      sheet: 'It was St. George’s Eve, and the castle was full of the Count’s guests.',
      report: 'It was St. George’s Eve, the night the people of the district keep indoors, and the castle was full of guests. {Victim} was killed during the night, after the gate was barred.',
      event: 'slam',
      motives: { forbidden: 2, jilted: 2 },
      intro: [
        'On St. George’s Eve the villagers bolt their doors, cross themselves and say that the dead walk at midnight; at the castle the guests sat down to dine with the shutters closed. At ten o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Every guest at the table is still in the castle, and the gate is barred.',
      ],
    },
    {
      id: 'hunt',
      weight: 2,
      titles: ['The Hunters', 'The Boxes of Earth', 'The Party from England'],
      sheet: 'A party from England had arrived at the castle to put an end to something.',
      report: 'A party from England had arrived at the castle with a purpose of its own. {Victim} was killed during the night, before it could be carried out.',
      event: 'walkout',
      motives: { hostile: 3, exposed: 2 },
      intro: [
        'The party from England had come a great way, by rail, by coach and over the pass on foot, with a bag of instruments and a plan they would not discuss before the household. At ten o’clock {victim} was found in {scene}, quite dead. It had been done {window}. The pass is shut, the gate is barred, and nobody is willing to say what they came for.',
      ],
    },
  ],
  scenarioIntro: [
    'The snow came down the pass at dusk, and by nightfall the gate was barred and the wolves were loud outside. At ten o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the castle, and nobody can before morning.',
  ],
}
