// The Marine Hotel, Seacombe-on-Sea, 1928: a seafront hotel out of season,
// the sea over the promenade and the police on the doors, and somebody dead
// among the permanent residents, the staff and the few guests the gale has
// kept in. The proprietor is at the end of his tether whether he is alive or
// not. Everything not its own — the roles, the papers, the way the people
// talk — it shares with the manor.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'
import { HOTEL_SILHOUETTES } from './silhouettes'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const hotel1928: SettingPack = {
  ...manor1920s,
  id: 'hotel1928',
  title: 'The Marine Hotel, 1928',
  victims: [
    {
      id: 'wainwright',
      name: 'Mr. Cedric Wainwright',
      shortName: 'Mr. Wainwright',
      title: 'proprietor of the Marine Hotel',
      pronouns: 'he',
      firstName: 'Cedric',
      lastName: 'Wainwright',
      respectful: 'the manager',
      parental: 'Father',
      character: 'wainwright',
      // He owed everybody, had sacked half the town, and was selling up: no hand of his to refuse, though.
      motives: ['hostile', 'indebted', 'exposed', 'dismissed', 'jilted', 'beneficiary', 'rival'],
      occasions: ['dance', 'bridge', 'sale', 'wedding', 'dinner'],
    },
    {
      id: 'blythe',
      name: 'Mrs. Honoria Blythe-Crane',
      shortName: 'Mrs. Blythe-Crane',
      title: 'a widow of means, in residence in Room 4',
      pronouns: 'she',
      firstName: 'Honoria',
      lastName: 'Blythe-Crane',
      respectful: 'Mrs. Blythe-Crane',
      parental: 'Mother',
      character: 'widow',
      // A fortune, a will, and a tongue: no staff of her own to dismiss, no business to rival.
      motives: ['beneficiary', 'disinherited', 'indebted', 'exposed', 'hostile', 'jilted'],
      occasions: ['dance', 'bridge', 'wedding', 'dinner'],
    },
    {
      id: 'lefevre',
      name: 'Monsieur Gaston Lefèvre',
      shortName: 'Monsieur Lefèvre',
      title: 'chef de cuisine at the Marine Hotel',
      pronouns: 'he',
      firstName: 'Gaston',
      lastName: 'Lefèvre',
      respectful: 'the chef',
      parental: 'Father',
      character: 'chef',
      // Ruled the kitchens and knew what went on below stairs; nothing to leave, nobody's hand to refuse.
      motives: ['hostile', 'dismissed', 'exposed', 'indebted', 'jilted', 'rival'],
      occasions: ['dance', 'bridge', 'wedding', 'dinner'],
    },
  ],
  place: {
    name: 'the hotel',
    here: 'this hotel',
    people: 'the hotel',
    plan: 'the plan of the hotel',
    gathering:
      'The gale at the glass, the front doors bolted against the sea, and everybody in the residents’ lounge, each with something to say before the questioning begins.',
    weather: 'the gale',
    one: 'guest',
    ones: 'guests',
    passage: 'the service corridor',
    placeName: 'the Marine Hotel',
    placeShort: 'Marine',
    at: 'at',
  },
  weather: 'gale',
  ambience: 'shore',
  // A long front to the sea, with wings: not a courtyard, not a cross.
  mapStyles: ['gallery', 'wings', 'ell'],
  windowLabel: 'between six and seven o’clock, as the band was tuning up',
  windowClock: 'Between 6 and 7 p.m. this evening',
  suspectsLine: 'The {n} guests and staff weatherbound at the Marine Hotel',
  chiefNote: 'The police have the doors, and can hold them till midnight and no longer. You’ve got till then to find out who did it.',
  windowFrom: 'six o’clock',

  rooms: [
    {
      id: 'lounge',
      name: 'the residents’ lounge',
      searchFlavor: [
        'Chintz gone pale at the windows, a wireless murmuring to nobody, and the day’s papers in their rods.',
        'The fire has been let down. Somebody’s knitting is still on the arm of a chair, needles crossed.',
      ],
    },
    {
      id: 'dining',
      name: 'the dining room',
      searchFlavor: [
        'Tables laid for a dinner nobody has eaten. A place card has fallen face down.',
        'The gong stands in its frame by the door. The cruets have been filled and not touched.',
      ],
    },
    {
      id: 'bar',
      name: 'the cocktail bar',
      searchFlavor: [
        'A shaker left wet, a lemon cut and browning, and the band’s music stands folded against the wall.',
        'Somebody has run a tab and not signed it. The siphon is empty.',
      ],
    },
    {
      id: 'kitchens',
      name: 'the kitchens',
      searchFlavor: [
        'Steam, copper, and a stockpot that has been left to catch. The menu for tonight is chalked up and crossed through.',
        'Knives on the magnet rack, one hook bare. A sauce has gone to skin in its pan.',
      ],
    },
    {
      id: 'palmcourt',
      name: 'the palm court',
      kind: 'glasshouse',
      searchFlavor: [
        'Wicker chairs under the glass roof, the palms shivering with every gust, and the sea white beyond the panes.',
        'A dropped programme for the dance. Rain finds its way in at one corner and has made a puddle.',
      ],
    },
    {
      id: 'suite',
      name: 'the Channel Suite',
      where: 'in the Channel Suite',
      searchFlavor: [
        'The best rooms in the house: a sitting room, a bedroom, and a balcony over the sea with the door banging in the wind.',
        'Trunks half unpacked. A bottle of champagne in a bucket of water that was ice.',
      ],
    },
    {
      id: 'promenade',
      name: 'the promenade',
      where: 'on the promenade',
      kind: 'outdoor',
      searchFlavor: [
        'Spray over the rail, shingle flung up on the flags, and the pier lights out along the front.',
        'A deck-chair has blown the length of the promenade and wedged itself in the shelter.',
      ],
    },
    {
      id: 'cellar',
      name: 'the cellar',
      searchFlavor: [
        'Wine racks, the boiler ticking as it cools, and water coming in under the sea door.',
        'Empties, a bicycle without its chain, and the hotel’s ledgers going back to the war.',
      ],
    },
  ],
  sceneRooms: ['lounge', 'dining', 'bar', 'kitchens', 'palmcourt', 'suite', 'promenade', 'cellar'],
  valuableRooms: ['suite', 'bar', 'lounge'],
  docRooms: ['lounge', 'suite', 'cellar'],

  means: [
    { id: 'stillroom', label: 'has a key to the first-aid cupboard' },
    { id: 'firearms', label: 'keeps a service revolver' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the kitchens' },
    { id: 'motor', label: 'can work the lift and the boiler' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a bottle from the first-aid cupboard, its label soaked off',
      methodLine: 'poisoned by a hand with a key to the first-aid cupboard',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['lounge', 'dining', 'bar', 'kitchens', 'palmcourt', 'suite', 'cellar'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'a service revolver, one round fired, wiped and put back in its drawer',
      methodLine: 'shot by somebody who keeps a revolver',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the brass gong stick from the dining room, wiped and hung back the wrong way round',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Gong Stick',
      rooms: ['lounge', 'dining', 'bar', 'kitchens', 'palmcourt', 'suite', 'cellar'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a curtain cord from the lounge, its tassel gone',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Curtain Cord',
      rooms: ['lounge', 'dining', 'bar', 'palmcourt', 'suite', 'cellar'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a carving knife from the kitchens, rinsed and put back wet',
      methodLine: 'stabbed by someone with the run of the kitchens',
      titled: 'The Knife',
    },
    {
      id: 'balcony',
      means: 'strength',
      weaponName: 'the balcony rail of the Channel Suite, the paint scraped, and the promenade forty feet below',
      methodLine: 'put over the balcony rail by someone with the strength for it',
      titled: 'The Balcony',
      rooms: ['suite'],
    },
    {
      id: 'lift',
      means: 'motor',
      weaponName: 'the lift, stopped between floors, its gate wedged open with a doorstop',
      methodLine: 'sent down the lift shaft by someone who can work the lift',
      titled: 'The Lift',
      rooms: ['lounge'],
    },
    {
      id: 'undertow',
      means: 'strength',
      weaponName: 'the sea rail, a torn glove caught on it, and the tide going out',
      methodLine: 'held under in the surf by someone with the strength for it',
      titled: 'The Undertow',
      rooms: ['promenade'],
    },
  ],

  characters: [
    as('hunter', { title: 'a permanent resident, Room 7', blurb: 'Has lived in Room 7 since the Armistice, and regards the lounge, the wireless and the Times as his own.' }),
    as('dowager', { title: 'in residence since the war', blurb: 'Took the corner table in 1917 and has not relinquished it, nor her opinion of the management.' }),
    as('elsie', { title: 'chambermaid', blurb: 'Does the first floor and the suite, and sees the state people leave their rooms in.' }),
    as('ellison', { title: 'a doctor, down for the sea air', blurb: 'Came for a rest and has been called to the lounge three times for the Major’s heart.' }),
    as('barrow', { title: 'solicitor, down about the sale', blurb: 'Arrived with a document case and the hotel company’s compliments, and has not been made welcome.' }),
    as('josephine', { title: 'singing with the dance band', blurb: 'Engaged for the season at the Marine, and counting the days until a better one.' }),
    as('medium', { title: 'taking the sea air, and three sittings a week', blurb: 'Holds her sittings in the palm court after dinner, at a guinea, and the residents go.' }),
    as('painter', { title: 'painting the front for the brochure', blurb: 'Commissioned to make the Marine look like Monte Carlo, and finding the gale no help.' }),
    as('vivienne', { title: 'wintering on the coast', blurb: 'Would ordinarily be at Cannes, and wishes everybody to know what has brought her here instead.' }),
    {
      id: 'wainwright',
      name: 'Mr. Cedric Wainwright',
      shortName: 'Mr. Wainwright',
      title: 'the proprietor',
      portrait: '🏨',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.6, perfume: 0.1, spectacles: 0.5, gloves: 0.2 },
      means: ['firearms', 'motor', 'strength'],
      manners: { prickly: 1, boastful: 0.6, blunt: 0.6, rambling: 0.3 },
      motives: { indebted: 0.9, exposed: 0.7, hostile: 0.7, rival: 0.5, dismissed: 0.3 },
      voice: { pitch: 158, wave: 'sawtooth', lilt: 4, clip: 0.06, ring: 0.5 },
      blurb: 'Owns the Marine, owes on it, and considers every guest a personal affront.',
    },
    {
      id: 'manageress',
      name: 'Mrs. Sybil Wainwright',
      shortName: 'Mrs. Wainwright',
      title: 'the manageress',
      portrait: '💄',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.7, perfume: 0.8, spectacles: 0.3, gloves: 0.5 },
      means: ['kitchen', 'stillroom'],
      manners: { gracious: 0.7, prickly: 0.7, gossipy: 0.6, blunt: 0.4 },
      motives: { exposed: 0.8, jilted: 0.7, indebted: 0.6, hostile: 0.6, beneficiary: 0.4 },
      voice: { pitch: 236, wave: 'square', lilt: 3.5, clip: 0.07, ring: 0.4 },
      blurb: 'Runs the hotel, the staff and her husband, and makes no secret of which is the most trouble.',
    },
    {
      id: 'waiter',
      name: 'Luigi Moretti',
      shortName: 'Luigi',
      title: 'the waiter',
      portrait: '🍽️',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.05, smoker: 0.5, perfume: 0.3, spectacles: 0.1, gloves: 0.6 },
      means: ['kitchen', 'strength'],
      manners: { deferential: 0.9, rambling: 0.6, cheeky: 0.4, hearty: 0.3 },
      motives: { dismissed: 0.9, hostile: 0.6, indebted: 0.5, exposed: 0.4 },
      voice: { pitch: 190, wave: 'triangle', lilt: 5, clip: 0.05, ring: 0.3 },
      blurb: 'Came from Genoa with a reference he wrote himself, and means well in two languages at once.',
    },
    {
      id: 'chef',
      name: 'Monsieur Gaston Lefèvre',
      shortName: 'Monsieur Lefèvre',
      title: 'chef de cuisine',
      portrait: '👨‍🍳',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.8, perfume: 0.1, spectacles: 0.2, gloves: 0.1 },
      means: ['kitchen', 'strength'],
      manners: { prickly: 0.9, boastful: 0.7, blunt: 0.6 },
      motives: { hostile: 0.9, dismissed: 0.7, exposed: 0.5, indebted: 0.4, rival: 0.3 },
      voice: { pitch: 128, wave: 'sawtooth', lilt: 3, clip: 0.08, ring: 0.7 },
      blurb: 'Cooked at the Ritz, he says, and lets the kitchen know what a comedown the Marine is, nightly.',
    },
    {
      id: 'nightporter',
      name: 'Mr. Albert Peck',
      shortName: 'Mr. Peck',
      title: 'the night porter',
      portrait: '🕯️',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.4, smoker: 0.7, perfume: 0.02, spectacles: 0.6, gloves: 0.3 },
      means: ['motor', 'strength'],
      manners: { reserved: 0.7, official: 0.6, gossipy: 0.4 },
      motives: { dismissed: 0.8, hostile: 0.5, indebted: 0.5, exposed: 0.5 },
      voice: { pitch: 118, wave: 'triangle', lilt: 1.5, clip: 0.11, ring: 0.8 },
      blurb: 'Keeps the desk from ten till six, knows who comes in late and with whom, and has never said.',
    },
    {
      id: 'traveller',
      name: 'Mr. Stanley Figgis',
      shortName: 'Mr. Figgis',
      title: 'commercial traveller, in ladies’ hosiery',
      portrait: '🧳',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.8, perfume: 0.3, spectacles: 0.3, gloves: 0.3 },
      means: ['motor'],
      manners: { hearty: 0.9, cheeky: 0.7, rambling: 0.6, gossipy: 0.4 },
      motives: { indebted: 0.8, exposed: 0.7, hostile: 0.5, dismissed: 0.3 },
      voice: { pitch: 168, wave: 'square', lilt: 4, clip: 0.06, ring: 0.5 },
      blurb: 'Stops at the Marine every quarter on his round, has a story for every table, and a bill he has not settled.',
    },
    {
      id: 'groom',
      name: 'Mr. Tony Pelham',
      shortName: 'Mr. Pelham',
      title: 'on his honeymoon',
      portrait: '🥂',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.6, perfume: 0.3, spectacles: 0.2, gloves: 0.4 },
      means: ['strength', 'motor'],
      manners: { gracious: 0.7, cheeky: 0.6, hearty: 0.5, reserved: 0.2 },
      motives: { indebted: 0.8, exposed: 0.7, forbidden: 0.6, hostile: 0.4 },
      voice: { pitch: 172, wave: 'sine', lilt: 3, clip: 0.06, ring: 0.4 },
      blurb: 'Married on Saturday, meant to be in Torquay, and finds the Marine a poor second and the gale a poorer third.',
    },
    {
      id: 'bride',
      name: 'Mrs. Daphne Pelham',
      shortName: 'Mrs. Pelham',
      title: 'on her honeymoon',
      portrait: '💐',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.5, perfume: 0.9, spectacles: 0.1, gloves: 0.7 },
      means: ['stillroom'],
      manners: { gracious: 0.8, cheeky: 0.5, gossipy: 0.5, reserved: 0.3 },
      motives: { forbidden: 0.8, exposed: 0.7, jilted: 0.5, indebted: 0.4 },
      voice: { pitch: 262, wave: 'sine', lilt: 4, clip: 0.05, ring: 0.3 },
      blurb: 'A week married and already keeping one secret from her husband, which the hotel knows and he does not.',
    },
    {
      id: 'receptionist',
      name: 'Miss Ivy Dale',
      shortName: 'Miss Dale',
      title: 'the receptionist',
      portrait: '🔔',
      pronouns: 'she',
      station: 'servant',
      leanings: { cane: 0.05, smoker: 0.2, perfume: 0.4, spectacles: 0.8, gloves: 0.5 },
      means: ['stillroom', 'motor'],
      manners: { official: 0.7, reserved: 0.6, prickly: 0.4 },
      motives: { dismissed: 0.9, exposed: 0.6, jilted: 0.6, indebted: 0.4, hostile: 0.3 },
      voice: { pitch: 222, wave: 'triangle', lilt: 2, clip: 0.07, ring: 0.3 },
      blurb: 'Keeps the register, the keys and the switchboard, and has heard every call put through the hotel.',
    },
    {
      id: 'widow',
      name: 'Mrs. Honoria Blythe-Crane',
      shortName: 'Mrs. Blythe-Crane',
      title: 'a widow of means, Room 4',
      portrait: '💍',
      pronouns: 'she',
      leanings: { cane: 0.6, smoker: 0.2, perfume: 0.7, spectacles: 0.6, gloves: 0.8 },
      means: ['stillroom'],
      manners: { gracious: 0.6, prickly: 0.7, blunt: 0.5, gossipy: 0.5 },
      motives: { hostile: 0.8, exposed: 0.6, indebted: 0.5, rival: 0.4, beneficiary: 0.3 },
      voice: { pitch: 206, wave: 'square', lilt: 2.5, clip: 0.09, ring: 0.5 },
      blurb: 'Has the best room, the worst temper and the largest fortune in the hotel, and will tell you the order.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...HOTEL_SILHOUETTES,
    // (The widow wears the manor's Dowager's cameo until she has one of her own.)
    widow: manor1920s.silhouettes!.dowager,
  },

  flavorItems: [
    'a tide table for the month, two days out of date',
    'a hotel brochure, “Sea Air and Every Comfort”, the corner torn',
    'a bridge scoring pad, the last rubber unfinished',
    'a tin of seaside rock, mostly gone',
    'a wireless programme with the dance band ringed in pencil',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a service door behind the panelling, and a cold way along the old servants’ corridor',
  bribeItem: 'an envelope of notes from the hotel safe, with {name}’s name pencilled on it',
  occasions: [
    {
      id: 'dance',
      weight: 3,
      titles: ['The New Year Dance', 'Last Waltz {At} {Place}', 'Gale over {Place}'],
      sheet: 'The hotel was holding its New Year’s Eve dance.',
      report: 'The hotel’s New Year’s Eve dance was to begin at eight. {Victim} was killed during the evening, after the gale had closed the front.',
      event: 'quarrel',
      intro: [
        'The band had come down from London for the New Year’s Eve dance, and the gale had come up the Channel to meet it. By six the sea was over the promenade and the police had closed the front; at seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The band is still here, and so is everybody else.',
        'Paper hats, a cold buffet, and a dance band tuning up in an empty bar: the Marine’s New Year’s Eve was never going to be gay, and then the gale shut the front. At seven o’clock {victim} was found in {scene}, the deed done {window}. Nobody in the hotel will see the New Year in anywhere else.',
      ],
    },
    {
      id: 'bridge',
      weight: 2,
      titles: ['The Bridge Week', 'A Hand Unfinished', 'Dummy {At} {Place}'],
      sheet: 'The hotel was holding its winter bridge week.',
      report: 'The hotel’s winter bridge week was in its third day. {Victim} was killed during the evening, after the gale had closed the front.',
      event: 'slam',
      motives: { indebted: 2.5, exposed: 2, hostile: 1.5 },
      intro: [
        'Bridge week at the Marine: four tables in the lounge, the stakes higher than the management knew, and feeling higher still. The gale shut the front at six; at seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}, and the cards are still on the tables where the players left them.',
      ],
    },
    {
      id: 'sale',
      weight: 2,
      titles: ['The Sale of {Place}', 'Under New Management', 'The Marine Hotels Company'],
      sheet: 'The proprietor was to sign the hotel over to the Grand Marine Hotels company that night.',
      report: '{Victim} was to sign the hotel’s sale to a company that evening, and had given the staff their notice. {He} was killed before the papers were signed.',
      event: 'telephone',
      motives: { dismissed: 3, beneficiary: 2, rival: 2, indebted: 1.5 },
      intro: [
        '{victim} had sold the Marine, or as good as: the company’s solicitor was in the house with the papers, and the staff had been given a month. Then the gale shut the front, and at seven o’clock {he} was found in {scene}, quite dead, the papers unsigned. Whoever did it is still under the roof {he} meant to sell.',
      ],
    },
    {
      id: 'wedding',
      weight: 2,
      titles: ['The Wedding Party', 'No Toast {At} {Place}', 'Confetti in the Gale'],
      sheet: 'A wedding party, weatherbound, had taken the first floor.',
      report: 'A wedding party kept in by the gale had the first floor. {Victim} was killed during the evening, after the front was closed.',
      event: 'walkout',
      motives: { forbidden: 3, jilted: 2 },
      intro: [
        'The wedding party had meant to be on the boat train by now, and was instead in the Marine’s lounge with the confetti still in its hair, listening to the sea come over the promenade. At seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}. Nobody has left the hotel, and nobody is in a mood to drink anybody’s health.',
      ],
    },
    {
      id: 'dinner',
      weight: 2,
      titles: ['The Regimental Dinner', 'Absent Friends', 'The Loyal Toast'],
      sheet: 'The dining room was given over to a regimental dinner.',
      report: 'The Major’s regimental dinner was being held in the dining room. {Victim} was killed during the evening, after the gale had closed the front.',
      event: 'quarrel',
      motives: { hostile: 2, exposed: 1.5 },
      intro: [
        'The regiment dined at the Marine every January, fewer of them each year, and this year the gale kept the speeches short. At six the sea came over the front; at seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The loyal toast was never drunk.',
      ],
    },
  ],
  scenarioIntro: [
    'The gale came up the Channel at four, and by six the sea was over the promenade and the police had closed the front. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the hotel, and nobody can.',
  ],
}
