// The Empress Theatre, Shaftesbury Avenue, 1929: the dress rehearsal of a new
// thriller run late into the fog, the first night cancelled, the stage door
// bolted and the company kept in under the working light. The rooms are the
// theatre's, front and back; the household is the company. Everything not
// its own — the roles, the papers, the way the people talk — it shares with
// the manor.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'
import { THEATRE_SILHOUETTES } from './silhouettes'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const theatre1929: SettingPack = {
  ...manor1920s,
  id: 'theatre1929',
  title: 'The Empress Theatre, 1929',
  victims: [
    {
      id: 'ashcombe',
      name: 'Sir Gerald Ashcombe',
      shortName: 'Sir Gerald',
      title: 'actor-manager of the Empress',
      pronouns: 'he',
      firstName: 'Gerald',
      lastName: 'Ashcombe',
      respectful: 'the Guv’nor',
      parental: 'Father',
      character: 'actormanager',
      occasions: ['dress', 'matinee', 'backer', 'gala', 'understudy'],
    },
    {
      id: 'dane',
      name: 'Miss Lavinia Dane',
      shortName: 'Miss Dane',
      title: 'leading lady of the Empress',
      pronouns: 'she',
      firstName: 'Lavinia',
      lastName: 'Dane',
      respectful: 'Miss Dane',
      parental: 'Mother',
      character: 'leadinglady',
      // A star has rivals, admirers and creditors, and could have anybody sacked; no blessing of hers to refuse.
      motives: ['jilted', 'rival', 'exposed', 'hostile', 'indebted', 'dismissed', 'beneficiary'],
      occasions: ['dress', 'matinee', 'backer', 'gala', 'understudy'],
    },
    {
      id: 'pell',
      name: 'Mr. Aubrey Pell',
      shortName: 'Mr. Pell',
      title: 'dramatic critic of the Morning Post',
      pronouns: 'he',
      firstName: 'Aubrey',
      lastName: 'Pell',
      respectful: 'Mr. Pell',
      parental: 'Father',
      character: 'critic',
      // A critic ends careers in a paragraph, and knows what he has seen at the stage door.
      motives: ['exposed', 'hostile', 'rival', 'indebted', 'jilted', 'dismissed'],
      occasions: ['dress', 'matinee', 'gala'],
    },
    {
      id: 'tuttle',
      name: 'Sam Tuttle',
      shortName: 'Sam',
      title: 'stage doorkeeper of the Empress',
      pronouns: 'he',
      firstName: 'Sam',
      lastName: 'Tuttle',
      respectful: 'Sam',
      parental: 'Father',
      character: 'doorkeeper',
      // Forty years on the stage door: he saw who came in, and who came in by the dock instead.
      motives: ['hostile', 'exposed', 'indebted', 'dismissed', 'jilted'],
      occasions: ['dress', 'matinee', 'backer', 'gala', 'understudy'],
    },
  ],
  place: {
    name: 'the theatre',
    here: 'this theatre',
    people: 'the company',
    plan: 'the plan of the theatre',
    gathering:
      'Fog in Shaftesbury Avenue, the stage door bolted, and the whole company on the stage under the working light, each with something to say before the questioning begins.',
    weather: 'the fog',
    one: 'player',
    ones: 'players',
    passage: 'the understage',
    placeName: 'the Empress',
    placeShort: 'Empress',
    at: 'at',
  },
  weather: 'fog',
  ambience: 'none',
  mapStyles: ['theatre'],
  windowLabel: 'between five and six o’clock, while the second act was playing',
  windowClock: 'Between 5 and 6 p.m. this evening',
  suspectsLine: 'The {n} of the company kept in at the Empress',
  chiefNote: 'The company can be kept in the theatre till midnight, and the fog will keep the rest of London out. You’ve got till then to find out who did it.',
  windowFrom: 'five o’clock',

  rooms: [
    {
      id: 'stage',
      name: 'the Stage',
      where: 'on the Stage',
      end: 'middle',
      searchFlavor: [
        'The set for the second act, a drawing room with one wall missing, and the working light hanging over it all.',
        'Chalk marks on the boards, a prompt copy open on a chair, and the house beyond the footlights quite dark.',
      ],
    },
    {
      id: 'prompt',
      name: 'the Prompt Corner',
      where: 'in the Prompt Corner',
      end: 'front',
      searchFlavor: [
        'The prompt desk, its cue lights dark, and the stage manager’s book open at the second act.',
        'Ropes, a fire bucket, and a call-board with the cast list and somebody’s name struck through.',
      ],
    },
    {
      id: 'flies',
      name: 'the Fly Gallery',
      where: 'up in the Fly Gallery',
      end: 'back',
      searchFlavor: [
        'A narrow platform high over the stage, the hemp lines tied off on their cleats, and the sandbags hanging still.',
        'The stage forty feet below, and the dust of fifty years on the rail.',
      ],
    },
    {
      id: 'green',
      name: 'the Green Room',
      searchFlavor: [
        'Sagging armchairs, a gas ring, signed photographs of the dead, and the tannoy hissing to itself.',
        'A pack of cards left mid-game, a cold pot of tea, and this week’s notices pinned up with the worst one underlined.',
      ],
    },
    {
      id: 'dressing',
      name: 'Dressing Room No. 1',
      where: 'in Dressing Room No. 1',
      searchFlavor: [
        'The star’s room: a mirror ringed with bulbs, telegrams in the frame, flowers going over in the basin.',
        'Greasepaint, a dressing gown over the chair, and a decanter with the stopper out.',
      ],
    },
    {
      id: 'props',
      name: 'the Props Room',
      searchFlavor: [
        'Shelves of the useful and the improbable: a stuffed owl, a telephone that does not ring, a tray of daggers.',
        'The props table laid out for the second act, every object on its chalked outline, and one outline empty.',
      ],
    },
    {
      id: 'bar',
      name: 'the Stalls Bar',
      where: 'in the Stalls Bar',
      searchFlavor: [
        'Mirrors and gilt, the bottles locked away, and a programme for a first night that is not going to happen.',
        'The house manager’s office behind the bar, its ledger open, and the evening’s takings not taken.',
      ],
    },
    {
      id: 'dock',
      name: 'the Scene Dock',
      where: 'in the Scene Dock',
      kind: 'outdoor',
      searchFlavor: [
        'The great doors to the alley standing open on the fog, flats stacked against the wall, and the hoist chain swinging.',
        'A lorry’s tyre marks on the wet floor, sawdust, and the smell of size and paint.',
      ],
    },
  ],
  sceneRooms: ['stage', 'prompt', 'flies', 'green', 'dressing', 'props', 'bar', 'dock'],
  valuableRooms: ['dressing', 'bar', 'props'],
  docRooms: ['bar', 'dressing', 'prompt'],

  means: [
    { id: 'stillroom', label: 'has a key to the dresser’s cabinet' },
    { id: 'firearms', label: 'handles the prop revolver, and knows where the live rounds are kept' },
    { id: 'strength', label: 'has the strength of a flyman' },
    { id: 'kitchen', label: 'has the run of the props table' },
    { id: 'motor', label: 'knows the working of the flies and the traps' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a bottle from the dresser’s cabinet, its label soaked off',
      methodLine: 'poisoned by a hand with a key to the dresser’s cabinet',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['stage', 'prompt', 'green', 'dressing', 'props', 'bar'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'the prop revolver from the second act, one live round fired, back on the props table in its chalked outline',
      methodLine: 'shot by somebody who handles the prop revolver',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'a stage weight, the iron kind, wiped and put back on the brace',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Stage Weight',
      rooms: ['stage', 'prompt', 'green', 'dressing', 'props', 'bar', 'dock'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a length of hemp from the fly floor, cut from a line and knotted',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Hemp',
      rooms: ['stage', 'prompt', 'flies', 'green', 'dressing', 'props', 'bar'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'the stage dagger from the third act, its blade not retractable after all',
      methodLine: 'stabbed by someone with the run of the props table',
      titled: 'The Stage Dagger',
    },
    {
      id: 'sandbag',
      means: 'motor',
      weaponName: 'a sandbag from the flies, its line cut clean, lying where it fell',
      methodLine: 'struck from above by someone who knows the working of the flies',
      titled: 'The Sandbag',
      rooms: ['stage'],
    },
    {
      id: 'trap',
      means: 'motor',
      weaponName: 'the star trap, its catch slipped, and a drop of twelve feet to the cellar floor',
      methodLine: 'sent through the trap by someone who knows the working of it',
      titled: 'The Trap',
      rooms: ['stage'],
    },
    {
      id: 'gallery',
      means: 'strength',
      weaponName: 'the fly gallery rail, and the stage forty feet below',
      methodLine: 'put over the fly rail by someone with the strength for it',
      titled: 'The Fly Rail',
      rooms: ['flies'],
    },
    {
      id: 'hoist',
      means: 'motor',
      weaponName: 'the scene hoist, its chain run out, and a flat come down from a height',
      methodLine: 'crushed under the hoist by someone who knows the working of it',
      titled: 'The Hoist',
      rooms: ['dock'],
    },
  ],

  characters: [
    as('josephine', { title: 'singing in the interval', blurb: 'Engaged for the interval numbers, and meant for better than the interval.' }),
    as('trent', { title: 'the backer', blurb: 'Put up the money for the production, and has been in front for every rehearsal counting it.' }),
    as('barrow', { title: 'the management’s solicitor', blurb: 'Drew up the contracts, and has been sent for about one of them.' }),
    as('vivienne', { title: 'patroness of the company', blurb: 'Lends the production her name and her box, and expects to be consulted about the casting.' }),
    as('medium', { title: 'consulted nightly by the star', blurb: 'Reads the cards in Dressing Room No. 1 before every performance, and has not been wrong yet, she says.' }),
    as('painter', { title: 'the scene painter', blurb: 'Painted the second act drawing room in a week, and the first act in an afternoon.' }),
    as('elsie', { title: 'dresser to the leading lady', blurb: 'Does the quick changes and hears what is said during them.' }),
    as('hunter', { title: 'a stage-door admirer', blurb: 'Has sent flowers round every night of the last three productions, and been let in for the dress rehearsal.' }),
    {
      id: 'actormanager',
      name: 'Sir Gerald Ashcombe',
      shortName: 'Sir Gerald',
      title: 'the actor-manager',
      portrait: '🎭',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.5, perfume: 0.4, spectacles: 0.3, gloves: 0.5 },
      means: ['firearms', 'motor', 'kitchen'],
      manners: { theatrical: 1, boastful: 0.6, gracious: 0.4 },
      motives: { rival: 0.9, exposed: 0.7, indebted: 0.7, hostile: 0.5, jilted: 0.3 },
      voice: { pitch: 128, wave: 'sawtooth', lilt: 4, clip: 0.09, ring: 0.9 },
      blurb: 'Owns the lease, plays the lead, directs the production and takes the notices personally.',
    },
    {
      id: 'leadinglady',
      name: 'Miss Lavinia Dane',
      shortName: 'Miss Dane',
      title: 'the leading lady',
      portrait: '🌹',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.6, perfume: 0.95, spectacles: 0.1, gloves: 0.8 },
      means: ['stillroom', 'kitchen'],
      manners: { theatrical: 0.9, gracious: 0.6, prickly: 0.4 },
      motives: { rival: 0.9, jilted: 0.8, exposed: 0.6, dismissed: 0.5, indebted: 0.4 },
      voice: { pitch: 232, wave: 'sine', lilt: 5, clip: 0.08, ring: 0.6 },
      blurb: 'Has had her name above the title for ten years, and has noticed the understudy is younger.',
    },
    {
      id: 'juvenile',
      name: 'Mr. Toby Marchmont',
      shortName: 'Mr. Marchmont',
      title: 'the juvenile lead',
      portrait: '💫',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.7, perfume: 0.5, spectacles: 0.1, gloves: 0.4 },
      means: ['firearms', 'strength'],
      manners: { theatrical: 0.7, cheeky: 0.7, boastful: 0.4 },
      motives: { dismissed: 0.9, indebted: 0.7, forbidden: 0.6, exposed: 0.5, rival: 0.4 },
      voice: { pitch: 170, wave: 'triangle', lilt: 4, clip: 0.06, ring: 0.4 },
      blurb: 'Two years out of RADA, in love with the leading lady or the part, and not yet sure which.',
    },
    {
      id: 'characteractress',
      name: 'Miss Maud Pringle',
      shortName: 'Miss Pringle',
      title: 'the character actress',
      portrait: '🧶',
      pronouns: 'she',
      leanings: { cane: 0.5, smoker: 0.4, perfume: 0.4, spectacles: 0.7, gloves: 0.5 },
      means: ['stillroom', 'kitchen'],
      manners: { theatrical: 0.7, gossipy: 0.8, hearty: 0.4 },
      motives: { dismissed: 0.8, exposed: 0.6, hostile: 0.6, jilted: 0.5, indebted: 0.4 },
      voice: { pitch: 198, wave: 'square', lilt: 3, clip: 0.08, ring: 0.5 },
      blurb: 'Has played every housekeeper, aunt and landlady in the West End, and remembers everybody’s first notice.',
    },
    {
      id: 'stagemanager',
      name: 'Mr. Len Garrity',
      shortName: 'Mr. Garrity',
      title: 'the stage manager',
      portrait: '📋',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.9, perfume: 0.05, spectacles: 0.6, gloves: 0.2 },
      means: ['motor', 'kitchen', 'firearms'],
      manners: { blunt: 0.9, cockney: 0.5, prickly: 0.4 },
      motives: { dismissed: 0.8, hostile: 0.7, indebted: 0.5, exposed: 0.5 },
      voice: { pitch: 134, wave: 'square', lilt: 1.5, clip: 0.1, ring: 0.7 },
      blurb: 'Calls the show, keeps the book and the props table, and has never missed a cue or forgiven a slight.',
    },
    {
      id: 'asm',
      name: 'Miss Peggy Dunn',
      shortName: 'Miss Dunn',
      title: 'the assistant stage manager',
      portrait: '🔦',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.5, perfume: 0.3, spectacles: 0.5, gloves: 0.3 },
      means: ['kitchen', 'motor'],
      manners: { deferential: 0.7, rambling: 0.6, cheeky: 0.4, reserved: 0.3 },
      motives: { dismissed: 0.9, exposed: 0.6, jilted: 0.5, indebted: 0.5, forbidden: 0.3 },
      voice: { pitch: 240, wave: 'triangle', lilt: 4, clip: 0.05, ring: 0.3 },
      blurb: 'Runs for everything, sets the props, understudies two parts, and is paid for none of it properly.',
    },
    {
      id: 'doorkeeper',
      name: 'Sam Tuttle',
      shortName: 'Sam',
      title: 'the stage doorkeeper',
      portrait: '🚪',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.4, smoker: 0.8, perfume: 0.02, spectacles: 0.6, gloves: 0.3 },
      means: ['strength', 'motor'],
      manners: { cockney: 0.9, gossipy: 0.6, deferential: 0.3 },
      motives: { dismissed: 0.9, hostile: 0.6, indebted: 0.5, exposed: 0.5 },
      voice: { pitch: 122, wave: 'triangle', lilt: 2, clip: 0.11, ring: 0.8 },
      blurb: 'Forty years on the stage door, knows every face that has passed it, and takes the flowers in.',
    },
    {
      id: 'wardrobe',
      name: 'Mrs. Nellie Cobb',
      shortName: 'Mrs. Cobb',
      title: 'the wardrobe mistress',
      portrait: '🧵',
      pronouns: 'she',
      station: 'servant',
      leanings: { cane: 0.2, smoker: 0.3, perfume: 0.3, spectacles: 0.9, gloves: 0.3 },
      means: ['stillroom', 'strength'],
      manners: { cockney: 0.7, blunt: 0.7, gossipy: 0.5 },
      motives: { dismissed: 0.8, hostile: 0.6, exposed: 0.6, indebted: 0.5 },
      voice: { pitch: 210, wave: 'square', lilt: 2.5, clip: 0.09, ring: 0.5 },
      blurb: 'Has let out and taken in every costume in the house, and knows exactly who has put on weight and why.',
    },
    {
      id: 'critic',
      name: 'Mr. Aubrey Pell',
      shortName: 'Mr. Pell',
      title: 'dramatic critic of the Morning Post',
      portrait: '🖋️',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.6, perfume: 0.3, spectacles: 0.8, gloves: 0.6 },
      means: ['stillroom'],
      manners: { donnish: 0.8, prickly: 0.7, boastful: 0.4 },
      motives: { exposed: 0.9, hostile: 0.7, rival: 0.6, jilted: 0.5, indebted: 0.4 },
      voice: { pitch: 146, wave: 'sine', lilt: 2.5, clip: 0.1, ring: 0.6 },
      blurb: 'Let in to the dress rehearsal as a courtesy, and has already written the first paragraph.',
    },
    {
      id: 'playwright',
      name: 'Mr. Julian Vosper',
      shortName: 'Mr. Vosper',
      title: 'the author',
      portrait: '📝',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.9, perfume: 0.2, spectacles: 0.7, gloves: 0.3 },
      means: ['kitchen', 'stillroom'],
      manners: { rambling: 0.9, donnish: 0.5, prickly: 0.5 },
      motives: { exposed: 0.8, hostile: 0.8, indebted: 0.6, rival: 0.5, dismissed: 0.4 },
      voice: { pitch: 160, wave: 'triangle', lilt: 3.5, clip: 0.07, ring: 0.5 },
      blurb: 'Wrote the play, has watched it cut by a third in rehearsal, and has not been quiet about it.',
    },
    {
      id: 'flyman',
      name: 'Alf Bream',
      shortName: 'Alf',
      title: 'the flyman',
      portrait: '🪢',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.05, smoker: 0.8, perfume: 0.02, spectacles: 0.2, gloves: 0.7 },
      means: ['strength', 'motor'],
      manners: { cockney: 0.8, reserved: 0.7, blunt: 0.4 },
      motives: { dismissed: 0.8, hostile: 0.7, indebted: 0.5, exposed: 0.4 },
      voice: { pitch: 116, wave: 'square', lilt: 1, clip: 0.12, ring: 0.9 },
      blurb: 'Flies the cloths from the gallery, says nothing on the stage or off it, and sees everything from above.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...THEATRE_SILHOUETTES,
  },

  flavorItems: [
    'a programme for the first night, the cast list already out of date',
    'a stick of number five greasepaint, worn to a stub',
    'a telegram, “Break a leg, darling”, unsigned',
    'a prompt copy of the first act, cut to ribbons in blue pencil',
    'a bouquet with the card taken off',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a trap in the boards, and a cold way down through the understage',
  bribeItem: 'an envelope of notes in the management’s stationery, with {name}’s name on it',
  occasions: [
    {
      id: 'dress',
      weight: 3,
      titles: ['The Dress Rehearsal', 'Curtain Up {At} {Place}', 'The Second Mrs. Carew'],
      sheet: 'The company was in the dress rehearsal of a new thriller, the first night being tonight.',
      report: 'The company was in the dress rehearsal of a new thriller, with the first night due at eight. {Victim} was killed during the second act. The first night has been cancelled, and the company kept in.',
      event: 'quarrel',
      intro: [
        'The dress rehearsal of “The Second Mrs. Carew” had run late, as dress rehearsals do, and the fog had come down Shaftesbury Avenue while it ran. At seven o’clock {victim} was found in {scene}, quite dead, and not by anybody’s stagecraft. It had been done {window}. The first night is off, the stage door is bolted, and the company is still in the house.',
        'A new thriller, a dress rehearsal that would not end, and a fog outside you could lean on. At seven o’clock {victim} was found in {scene}, the deed done {window}. The house manager has put a notice on the doors, and nobody in the company has been allowed near them.',
      ],
    },
    {
      id: 'matinee',
      weight: 2,
      titles: ['The Last Matinée', 'Final Performance', 'The Notice Is Up'],
      sheet: 'The company was playing the last matinée of the run, and the notice was up.',
      report: 'The last matinée of the run was playing, and the company was to disperse in the morning. {Victim} was killed during the second act, and the stage door was bolted at the curtain.',
      event: 'walkout',
      motives: { dismissed: 2, indebted: 2, jilted: 1.5 },
      intro: [
        'The notice had been up a fortnight, the last matinée had played to half a house, and the company was packing. Then the fog came down, and at seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}. Nobody is going anywhere tonight, in the fog or out of it.',
      ],
    },
    {
      id: 'backer',
      weight: 2,
      titles: ['The Angel', 'Money in Front', 'The Backer’s Verdict'],
      sheet: 'The play’s backer was in front for the dress rehearsal, to see his money on the stage.',
      report: 'The backer was in front for the dress rehearsal, and the company knew the run depended on his verdict. {Victim} was killed during the second act, and the stage door was bolted at the curtain.',
      event: 'telephone',
      motives: { indebted: 3, exposed: 2, rival: 1.5 },
      intro: [
        'The backer had come to see what his money had bought, and sat in the stalls through the dress rehearsal with his hat on, which is never a good sign. The fog came down during the second act. At seven o’clock {victim} was found in {scene}, quite dead, and it had been done {window}. The run may yet go on; the company cannot.',
      ],
    },
    {
      id: 'gala',
      weight: 2,
      titles: ['The Gala', 'By Royal Command', 'A Charity Matinée'],
      sheet: 'The company was playing a charity matinée, with royalty in the box.',
      report: 'A charity matinée was playing, with a royal party in the box. {Victim} was killed during the second act; the box left at the curtain, and the stage door was bolted.',
      event: 'quarrel',
      motives: { exposed: 2, hostile: 1.5 },
      intro: [
        'There had been royalty in the box for the charity matinée and the whole company on its best behaviour, which does not come naturally to a company. The box had gone and the fog had come. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The stage door is bolted and the company kept in.',
      ],
    },
    {
      id: 'understudy',
      weight: 2,
      titles: ['The Understudy', 'Indisposed', 'A Star Is Made'],
      sheet: 'The understudy had gone on in the lead that afternoon, the star being indisposed.',
      report: 'The understudy went on in the lead at the matinée, the star being indisposed, and the house loved her. {Victim} was killed during the second act, and the stage door was bolted at the curtain.',
      event: 'slam',
      motives: { rival: 3, jilted: 2, dismissed: 1.5 },
      intro: [
        'The star was indisposed, the understudy went on, and the house stood up at the end of it, which is a thing a company does not forget or forgive. The fog came down with the curtain. At seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}, and the understudy is still in the star’s dressing room.',
      ],
    },
  ],
  scenarioIntro: [
    'The fog came down Shaftesbury Avenue at five, and by seven the stage door was bolted. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The first night is off, and nobody in the company has left the theatre.',
  ],
}
