// St. Jude's College, Oxford, 1927: a small college in Michaelmas fog on the
// night of the Gaudy, the gate locked on the Dean's order, and somebody dead
// among the fellows, the servants and the guests who dined. The rooms are the
// college's; the household is the whole college. Everything not its own — the
// roles, the papers, the way the people talk — it shares with the manor.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'
import { COLLEGE_SILHOUETTES } from './silhouettes'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const college1927: SettingPack = {
  ...manor1920s,
  id: 'college1927',
  title: 'St. Jude’s College, 1927',
  victims: [
    {
      id: 'fenwick',
      name: 'Dr. Ambrose Fenwick',
      shortName: 'the Master',
      title: 'Master of St. Jude’s',
      pronouns: 'he',
      firstName: 'Ambrose',
      lastName: 'Fenwick',
      respectful: 'the Master',
      parental: 'Father',
      character: 'master',
      children: ['masterdaughter'],
      occasions: ['gaudy', 'election', 'bequest', 'degree', 'fellowship'],
    },
    {
      id: 'garside',
      name: 'Mr. Lionel Garside',
      shortName: 'the Bursar',
      title: 'Bursar of St. Jude’s',
      pronouns: 'he',
      firstName: 'Lionel',
      lastName: 'Garside',
      respectful: 'the Bursar',
      parental: 'Father',
      character: 'bursar',
      // Held the college's purse and its leases, and had his own candidate for the Lodgings; no daughter to marry.
      motives: ['indebted', 'exposed', 'hostile', 'dismissed', 'rival', 'jilted', 'beneficiary'],
      occasions: ['gaudy', 'election', 'degree', 'fellowship'],
    },
    {
      id: 'quill',
      name: 'Mr. Alfred Quill',
      shortName: 'Mr. Quill',
      title: 'head porter of St. Jude’s',
      pronouns: 'he',
      firstName: 'Alfred',
      lastName: 'Quill',
      respectful: 'Mr. Quill',
      parental: 'Father',
      character: 'headporter',
      // Kept the gate book for thirty years, and knew who came in late and by what wall.
      motives: ['hostile', 'exposed', 'indebted', 'dismissed', 'jilted'],
      occasions: ['gaudy', 'election', 'degree', 'fellowship'],
    },
  ],
  place: {
    name: 'the college',
    here: 'this college',
    people: 'the college',
    plan: 'the plan of the college',
    gathering:
      'Fog in the quad, the gate locked, and the whole college in Hall, each with something to say before the questioning begins.',
    weather: 'the fog',
    one: 'colleague',
    ones: 'colleagues',
    passage: 'the cloister',
    placeName: 'St. Jude’s',
    placeShort: 'St. Jude’s',
    at: 'at',
  },
  weather: 'fog',
  ambience: 'fog',
  mapStyles: ['courtyard'],
  windowLabel: 'between six and seven o’clock, as Hall filled for dinner',
  windowClock: 'Between 6 and 7 p.m. this evening',
  suspectsLine: 'The {n} members of the college within the gate',
  chiefNote: 'The Dean will keep the gate locked till midnight, and not a minute past. You’ve got till then to find out who did it.',
  windowFrom: 'six o’clock',

  rooms: [
    {
      id: 'lodgings',
      name: 'the Master’s Lodgings',
      where: 'in the Master’s Lodgings',
      searchFlavor: [
        'Panelling, portraits of dead Masters, and a fire that somebody has let go down.',
        'A decanter with one glass beside it, and the college seal on the desk, out of its box.',
      ],
    },
    {
      id: 'scr',
      name: 'the Senior Common Room',
      searchFlavor: [
        'Leather chairs, the day’s papers, and the port going round in nobody’s hands.',
        'The betting book lies open. The last wager is on the election, and the stake is a dozen of claret.',
      ],
    },
    {
      id: 'hall',
      name: 'the Hall',
      where: 'in Hall',
      searchFlavor: [
        'Long tables laid for the Gaudy, high table on its dais, and the founder looking down from his frame.',
        'The grace has not been said. A chair at high table has been pushed back and left.',
      ],
    },
    {
      id: 'chapel',
      name: 'the Chapel',
      searchFlavor: [
        'Cold stone, the organ’s pipes catching what light there is, and the tower stair door standing open.',
        'The plate is in its aumbry and the aumbry is locked. A hymn number has not been taken down.',
      ],
    },
    {
      id: 'library',
      name: 'the Library',
      searchFlavor: [
        'Chained folios, the gallery running round above, and a ladder that has been moved.',
        'A reading lamp still burning over an open volume. The fog has got in at a window.',
      ],
    },
    {
      id: 'buttery',
      name: 'the Buttery',
      searchFlavor: [
        'Barrels, the battels book, and the smell of the college ale and the kitchens beyond.',
        'A tankard half drunk on the hatch, and a tally chalked up and crossed through.',
      ],
    },
    {
      id: 'lodge',
      name: 'the Porter’s Lodge',
      where: 'in the Porter’s Lodge',
      searchFlavor: [
        'Pigeon-holes of letters, the gate book, a kettle on the ring, and the great key on its hook.',
        'The gate book’s last entry is in a hurried hand. The fog has come in under the door.',
      ],
    },
    {
      id: 'quad',
      name: 'the Front Quad',
      where: 'in the Front Quad',
      kind: 'outdoor',
      searchFlavor: [
        'Fog to the first-floor windows, the lawn grey and wet, and the fountain dripping into itself.',
        'Gravel, footprints going every way, and a gown dropped on the grass where nobody should walk.',
      ],
    },
  ],
  sceneRooms: ['lodgings', 'scr', 'hall', 'chapel', 'library', 'buttery', 'lodge', 'quad'],
  valuableRooms: ['chapel', 'lodgings', 'library'],
  docRooms: ['lodgings', 'library', 'scr', 'lodge'],

  means: [
    { id: 'stillroom', label: 'has the run of the laboratory and its poisons cupboard' },
    { id: 'firearms', label: 'keeps a service revolver' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the Buttery and the kitchens' },
    { id: 'motor', label: 'knows the way over the roofs and up the tower stair' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a bottle from the laboratory’s poisons cupboard, the label soaked off',
      methodLine: 'poisoned by a hand with the run of the laboratory',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['lodgings', 'scr', 'hall', 'chapel', 'library', 'buttery', 'lodge'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'a service revolver, one round fired, wiped and put back in its drawer',
      methodLine: 'shot by somebody who keeps a revolver',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the college mace from Hall, its silver head wiped and its shaft not',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Mace',
      rooms: ['lodgings', 'scr', 'hall', 'chapel', 'library', 'buttery', 'lodge'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'the cord of a Library blind, cut down and knotted',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Blind Cord',
      rooms: ['lodgings', 'scr', 'hall', 'library', 'buttery', 'lodge'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a carving knife from the Buttery, rinsed and put back wet',
      methodLine: 'stabbed by someone with the run of the Buttery',
      titled: 'The Knife',
    },
    {
      id: 'gallery',
      means: 'motor',
      weaponName: 'the Library gallery rail, polished where a hand slid, and the stone floor twenty feet below',
      methodLine: 'put over the gallery rail by someone who knows the way up to it',
      titled: 'The Gallery',
      rooms: ['library'],
    },
    {
      id: 'tower',
      means: 'motor',
      weaponName: 'the tower stair, a hundred and twelve steps, and a stone landing at the foot of them',
      methodLine: 'sent down the tower stair by someone who knows the way up it',
      titled: 'The Tower Stair',
      rooms: ['chapel'],
    },
    {
      id: 'fountain',
      means: 'strength',
      weaponName: 'the fountain in the Front Quad, its basin disturbed, and a cap floating in it',
      methodLine: 'held under in the fountain by someone with the strength for it',
      titled: 'The Fountain',
      rooms: ['quad'],
    },
  ],

  characters: [
    as('vicar', { title: 'the Chaplain', blurb: 'Has preached to the college for twenty years, and is not sure any of it has taken.' }),
    as('ellison', { title: 'the college doctor', blurb: 'Keeps the fellows alive against their habits, and knows exactly what those are.' }),
    as('barrow', { title: 'the college’s solicitor', blurb: 'Up from Lincoln’s Inn with a document case about the college’s leases, and not saying which.' }),
    as('hunter', { title: 'an old member, down for the Gaudy', blurb: 'Matriculated in ’89, dines every Gaudy, and finds the college gone soft since.' }),
    as('medium', { title: 'addressing the Psychical Society', blurb: 'Engaged to speak to the undergraduates’ society on the survival of the soul, at a fee.' }),
    as('heiress', { title: 'reading History at St. Hilda’s', blurb: 'Dining as the Master’s guest, and the only person in Hall who has read the set books.' }),
    as('painter', { title: 'painting the Master’s portrait', blurb: 'Commissioned to hang in Hall with the rest, and finding the sitter will not sit.' }),
    as('dowager', { title: 'the Master’s sister', blurb: 'Keeps house in the Lodgings and considers the fellows a set of unruly lodgers.' }),
    as('daughter', { id: 'masterdaughter', name: 'Miss Violet Fenwick', shortName: 'Miss Fenwick', title: 'the Master’s daughter' }),
    {
      id: 'master',
      name: 'Dr. Ambrose Fenwick',
      shortName: 'the Master',
      title: 'Master of the college',
      portrait: '🎓',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.4, perfume: 0.05, spectacles: 0.9, gloves: 0.3 },
      means: ['motor', 'strength'],
      manners: { donnish: 1, gracious: 0.6, boastful: 0.4 },
      motives: { rival: 0.9, exposed: 0.7, hostile: 0.6, indebted: 0.4, beneficiary: 0.3 },
      voice: { pitch: 132, wave: 'sine', lilt: 2.5, clip: 0.09, ring: 0.7 },
      blurb: 'Has ruled St. Jude’s for twenty years, and means to choose who rules it next.',
    },
    {
      id: 'dean',
      name: 'Dr. Cuthbert Allardyce',
      shortName: 'the Dean',
      title: 'Dean of the college',
      portrait: '⚖️',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.2, perfume: 0.05, spectacles: 0.8, gloves: 0.4 },
      means: ['strength', 'motor'],
      manners: { prickly: 0.9, donnish: 0.8, blunt: 0.5 },
      motives: { rival: 0.9, hostile: 0.7, exposed: 0.5, dismissed: 0.4, indebted: 0.3 },
      voice: { pitch: 124, wave: 'square', lilt: 1.5, clip: 0.1, ring: 0.6 },
      blurb: 'Keeps discipline, keys and grudges, and has had the gate locked tonight on his own authority.',
    },
    {
      id: 'bursar',
      name: 'Mr. Lionel Garside',
      shortName: 'the Bursar',
      title: 'Bursar of the college',
      portrait: '🧾',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.7, perfume: 0.1, spectacles: 0.7, gloves: 0.3 },
      means: ['firearms', 'kitchen'],
      manners: { hearty: 0.7, official: 0.6, boastful: 0.4 },
      motives: { indebted: 0.9, exposed: 0.8, rival: 0.6, hostile: 0.5, dismissed: 0.4 },
      voice: { pitch: 150, wave: 'sawtooth', lilt: 3, clip: 0.07, ring: 0.6 },
      blurb: 'Holds the college’s purse, its leases and its port, and has been asked about all three lately.',
    },
    {
      id: 'tutor',
      name: 'Mr. Percival Thane',
      shortName: 'Mr. Thane',
      title: 'the Senior Tutor',
      portrait: '📜',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.8, perfume: 0.05, spectacles: 0.8, gloves: 0.2 },
      means: ['stillroom', 'motor'],
      manners: { donnish: 0.9, reserved: 0.6, prickly: 0.5 },
      motives: { rival: 0.9, dismissed: 0.7, exposed: 0.6, hostile: 0.5, jilted: 0.3 },
      voice: { pitch: 140, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.5 },
      blurb: 'Has been passed over for the Lodgings twice, and has a long memory and a longer sentence.',
    },
    {
      id: 'fellow',
      name: 'Dr. Rupert Lisle',
      shortName: 'Dr. Lisle',
      title: 'a research fellow, in chemistry',
      portrait: '⚗️',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.6, perfume: 0.1, spectacles: 0.6, gloves: 0.3 },
      means: ['stillroom', 'strength'],
      manners: { cheeky: 0.7, donnish: 0.6, rambling: 0.4 },
      motives: { dismissed: 0.9, exposed: 0.7, rival: 0.6, indebted: 0.5, forbidden: 0.4 },
      voice: { pitch: 176, wave: 'triangle', lilt: 4, clip: 0.06, ring: 0.4 },
      blurb: 'The youngest fellow, with a laboratory, a fellowship up for renewal, and opinions about both.',
    },
    {
      id: 'headporter',
      name: 'Mr. Alfred Quill',
      shortName: 'Mr. Quill',
      title: 'the head porter',
      portrait: '🎩',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.2, smoker: 0.7, perfume: 0.02, spectacles: 0.5, gloves: 0.6 },
      means: ['motor', 'strength'],
      manners: { official: 0.7, deferential: 0.7, blunt: 0.4 },
      motives: { dismissed: 0.9, hostile: 0.6, exposed: 0.5, indebted: 0.5 },
      voice: { pitch: 126, wave: 'square', lilt: 1.5, clip: 0.11, ring: 0.8 },
      blurb: 'Thirty years in the Lodge, keeps the gate book and the gate, and knows every wall that can be climbed.',
    },
    {
      id: 'scout',
      name: 'Mr. Harold Beddoes',
      shortName: 'Beddoes',
      title: 'the Master’s scout',
      portrait: '🫖',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.3, smoker: 0.5, perfume: 0.02, spectacles: 0.6, gloves: 0.4 },
      means: ['kitchen', 'motor'],
      manners: { deferential: 0.9, gossipy: 0.6, reserved: 0.5, rambling: 0.3 },
      motives: { dismissed: 0.8, exposed: 0.6, hostile: 0.5, indebted: 0.5 },
      voice: { pitch: 136, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.6 },
      blurb: 'Has done the Lodgings and the staircase beside it since before the war, and empties the waste-paper baskets.',
    },
    {
      id: 'don',
      name: 'Miss Agatha Kerr',
      shortName: 'Miss Kerr',
      title: 'a Fellow of Somerville, dining',
      portrait: '🦉',
      pronouns: 'she',
      leanings: { cane: 0.2, smoker: 0.4, perfume: 0.2, spectacles: 0.9, gloves: 0.5 },
      means: ['stillroom'],
      manners: { donnish: 0.9, blunt: 0.7, gracious: 0.3 },
      motives: { rival: 0.9, hostile: 0.7, exposed: 0.5, dismissed: 0.5, jilted: 0.3 },
      voice: { pitch: 204, wave: 'square', lilt: 2, clip: 0.09, ring: 0.5 },
      blurb: 'The first woman to dine at high table at St. Jude’s, and in no doubt what several of the fellows think of it.',
    },
    {
      id: 'undergraduate',
      name: 'Mr. Peter Fenwick',
      shortName: 'Mr. Fenwick',
      title: 'the Master’s nephew, an undergraduate',
      portrait: '🥄',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.7, perfume: 0.3, spectacles: 0.2, gloves: 0.3 },
      means: ['strength', 'motor'],
      manners: { cheeky: 0.9, hearty: 0.5, rambling: 0.4 },
      motives: { disinherited: 0.9, indebted: 0.8, forbidden: 0.6, exposed: 0.5, hostile: 0.3 },
      voice: { pitch: 182, wave: 'sawtooth', lilt: 4.5, clip: 0.05, ring: 0.4 },
      blurb: 'In his third year and his second set of debts, and rusticated once already for climbing in.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...COLLEGE_SILHOUETTES,
    masterdaughter: manor1920s.silhouettes!.daughter,
  },

  flavorItems: [
    'a copy of the college statutes, its pages uncut',
    'a bottle of the college port, two glasses’ worth down',
    'an essay on the Peloponnesian War, marked beta minus',
    'the seating plan for the Gaudy, much amended',
    'a Bible with a bookmark at Judges',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a door behind the panelling, and a cold way along the old cloister to the next staircase',
  bribeItem: 'an envelope of notes on the college’s own paper, with {name}’s name on it',
  occasions: [
    {
      id: 'gaudy',
      weight: 3,
      titles: ['The {Short} Gaudy', 'Gaudy Night', 'Fog over {Place}'],
      sheet: 'The college was holding its Gaudy, and the old members had come up to dine.',
      report: 'The old members had come up for the Gaudy, and dinner was laid in Hall. {Victim} was killed during the evening, after the fog had come down and the gate was locked.',
      event: 'quarrel',
      intro: [
        'The old members had come up for the Gaudy, and the fog came up the river to meet them: by six it was to the first-floor windows and the Dean had the gate locked. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the college, and nobody can.',
        'A Gaudy is the one night of the year a college forgives itself everything. By six the fog had shut St. Jude’s off from the town, and at seven o’clock {victim} was found in {scene}, the deed done {window}. The old members are still in Hall, and so is whoever did it.',
      ],
    },
    {
      id: 'election',
      weight: 2,
      titles: ['The Election', 'The Next Master', 'A Vacancy in the Lodgings'],
      sheet: 'The fellows were to meet that night to elect a new Master.',
      report: 'The fellows were to meet that night to elect a new Master, and {Victim} had made {his} views on the candidates known. {He} was killed before the meeting took place.',
      event: 'walkout',
      motives: { rival: 3, hostile: 2, dismissed: 1.5 },
      intro: [
        'The fellows were to elect a new Master that night, and had been not speaking to one another about it for a month. The fog came down at four and the Dean locked the gate at six; at seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}. The election has been adjourned, and nobody has left the college.',
      ],
    },
    {
      id: 'bequest',
      weight: 2,
      titles: ['The {LastName} Bequest', 'The Unsigned Will', 'A Benefaction'],
      sheet: '{Victim} meant to sign a new will that night, leaving the college {his} fortune.',
      report: '{Victim} meant to sign a new will that night, with the college’s solicitor to witness it. {He} was killed before {he} was able to do so.',
      event: 'slam',
      motives: { disinherited: 3, beneficiary: 3 },
      intro: [
        '{victim} had the college’s solicitor up from London to witness a new will, and everybody who had an interest in the old one had contrived to dine. Then the fog came down and the gate was locked. At seven o’clock {he} was found in {scene}, quite dead, and the will unsigned. The college was to have had everything; somebody preferred that it should not.',
      ],
    },
    {
      id: 'degree',
      weight: 2,
      titles: ['The Honorary Degree', 'A Dinner in Hall', 'Honoris Causa'],
      sheet: 'The college was dining a visiting scholar, to be given an honorary degree in the morning.',
      report: 'The college was dining a visiting scholar who was to be given an honorary degree in the morning. {Victim} was killed during the evening, after the fog had come down and the gate was locked.',
      event: 'quarrel',
      motives: { exposed: 2, rival: 1.5 },
      intro: [
        'A distinguished visitor, a dinner in Hall in his honour, and the whole college on its best behaviour for one night. By six the fog had shut the gate; at seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The visitor will have something to tell them in Leipzig.',
      ],
    },
    {
      id: 'fellowship',
      weight: 2,
      titles: ['The Vacant Fellowship', 'A Question of Tenure', 'The Election to the Fellowship'],
      sheet: 'The fellows were to elect to a vacant fellowship that night.',
      report: 'A vacant fellowship was to be filled that night, and {Victim} had a candidate. {He} was killed before the fellows met.',
      event: 'telephone',
      motives: { rival: 3, dismissed: 2, exposed: 1.5 },
      intro: [
        'A fellowship was vacant, two men wanted it, and the fellows were to settle it after dinner; which is to say that nothing else had been talked of for a week. The fog came down at four and the gate was locked at six. At seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}, and the fellowship is still vacant.',
      ],
    },
  ],
  scenarioIntro: [
    'The fog came down at four, and by six the head porter had locked the gate on the Dean’s order. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the college, and nobody can.',
  ],
}
