import type { SettingPack } from '../schema'
import { dialogue } from './dialogue'
import { silhouettes } from './silhouettes'

export const manor1920s: SettingPack = {
  id: 'manor1920s',
  title: 'Blackwood Manor, 1926',
  victim: {
    name: 'Lord Edgar Blackwood',
    shortName: 'Lord Blackwood',
    title: 'master of Blackwood Manor',
    pronouns: 'he',
  },
  windowLabel: 'between half past six and half past seven, while the house dressed for dinner',

  rooms: [
    {
      id: 'study',
      name: 'the study',
      searchFlavor: [
        'Papers in stern stacks, a globe that spins with a squeak. Nothing here speaks.',
        'The desk drawers hold sealing-wax, string, and a smell of old cigars.',
      ],
    },
    {
      id: 'library',
      name: 'the library',
      searchFlavor: [
        'A ladder on brass rails, a thousand unread spines. The dust lies undisturbed.',
        'Someone left a novel face-down on the arm of a chair. It tells you nothing.',
      ],
    },
    {
      id: 'conservatory',
      kind: 'glasshouse',
      name: 'the conservatory',
      searchFlavor: [
        'Ferns sweat against the glass. The gravel path bears no useful print.',
        'Orchids, damp heat, a watering-can half full. Nothing out of place.',
      ],
    },
    {
      id: 'billiards',
      name: 'the billiard room',
      searchFlavor: [
        'The baize is brushed, the balls racked. A game was finished, or never begun.',
        'Cues in their rack like rifles. The scoreboard still shows an old game.',
      ],
    },
    {
      id: 'drawing',
      name: 'the drawing room',
      searchFlavor: [
        'Cold tea in thin china. The cushions confess nothing.',
        'The gramophone holds a dance record, its needle worn. No help there.',
      ],
    },
    {
      id: 'dining',
      name: 'the dining room',
      searchFlavor: [
        'Seven places laid for a dinner nobody ate. The silver is all accounted for.',
        'The candles have burned to different heights. Curious, but idle.',
      ],
    },
    {
      id: 'kitchen',
      name: 'the kitchen',
      searchFlavor: [
        'Copper pans, a sulking stove, a pheasant that will now go to waste.',
        'The knife block is full. You counted twice.',
      ],
    },
    {
      id: 'terrace',
      kind: 'outdoor',
      name: 'the garden terrace',
      searchFlavor: [
        'Rain has scrubbed the flagstones clean. The roses keep their own counsel.',
        'A forgotten shawl on the balustrade, damp with evening. Nobody claims the night was warm.',
      ],
    },
  ],
  sceneRooms: ['study', 'conservatory', 'billiards'],
  valuableRooms: ['study', 'library', 'drawing'],
  docRooms: ['study', 'library', 'drawing'],

  traits: [
    { id: 'cane', label: 'walks with a cane', evidenceName: 'fresh scuff-marks of a cane ferrule' },
    { id: 'smoker', label: 'smokes like a chimney', evidenceName: 'a spill of fresh tobacco ash' },
    { id: 'perfume', label: 'wears a distinctive scent', evidenceName: 'a lingering trace of scent' },
    { id: 'spectacles', label: 'wears spectacles', evidenceName: 'a cracked spectacle lens' },
    { id: 'gloves', label: 'is never without gloves', evidenceName: 'a torn kid glove' },
  ],

  means: [
    { id: 'stillroom', label: 'keeps a key to the still-room' },
    { id: 'firearms', label: 'knew the gun-room cupboard' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a vial from the still-room, half-empty, smelling of bitter almonds',
      methodLine: 'poisoned — by a hand with still-room access',
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'the gun-room revolver, one round spent, hastily hidden',
      methodLine: 'shot — by someone who knew the gun-room cupboard',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the heavy brass poker, wiped ill',
      methodLine: 'struck down — by someone with the strength for it',
    },
  ],

  characters: [
    {
      id: 'colonel',
      name: 'Colonel Rupert Ashworth',
      shortName: 'the Colonel',
      title: 'retired officer',
      portrait: '🎖️',
      pronouns: 'he',
      trait: 'cane',
      means: ['firearms', 'strength'],
      blurb: 'Served with the late Lord Blackwood the elder; treats the manor as a mess hall.',
    },
    {
      id: 'vicar',
      name: 'Reverend James Whitfield',
      shortName: 'the Reverend',
      title: 'vicar of the parish',
      portrait: '📖',
      pronouns: 'he',
      trait: 'cane',
      means: ['strength'],
      blurb: 'Gentle in the pulpit, sharp at the card table.',
    },
    {
      id: 'trent',
      name: 'Mr. Hugo Trent',
      shortName: 'Mr. Trent',
      title: 'business partner',
      portrait: '💼',
      pronouns: 'he',
      trait: 'smoker',
      means: ['firearms', 'stillroom'],
      blurb: 'Half of Blackwood & Trent, Importers. The half that does the talking.',
    },
    {
      id: 'josephine',
      name: 'Miss Josephine Hart',
      shortName: 'Miss Hart',
      title: 'jazz singer',
      portrait: '🎤',
      pronouns: 'she',
      trait: 'smoker',
      means: ['firearms'],
      blurb: 'Engaged for the evening’s entertainment; stayed for the weekend.',
    },
    {
      id: 'vivienne',
      name: 'Lady Vivienne Marsh',
      shortName: 'Lady Marsh',
      title: 'society widow',
      portrait: '🕊️',
      pronouns: 'she',
      trait: 'perfume',
      means: ['stillroom'],
      blurb: 'Twice widowed, thrice invited everywhere.',
    },
    {
      id: 'elsie',
      name: 'Elsie Dunn',
      shortName: 'Elsie',
      title: 'parlour maid',
      portrait: '🕯️',
      pronouns: 'she',
      trait: 'perfume',
      means: ['stillroom', 'strength'],
      blurb: 'Sees every room in the house before anyone is awake in it.',
    },
    {
      id: 'ellison',
      name: 'Dr. Edmund Ellison',
      shortName: 'Dr. Ellison',
      title: 'family physician',
      portrait: '🩺',
      pronouns: 'he',
      trait: 'spectacles',
      means: ['stillroom'],
      blurb: 'Has attended the family for thirty years, and their secrets longer.',
    },
    {
      id: 'barrow',
      name: 'Mr. Felix Barrow',
      shortName: 'Mr. Barrow',
      title: 'the family solicitor',
      portrait: '📜',
      pronouns: 'he',
      trait: 'spectacles',
      means: ['firearms'],
      blurb: 'Arrived Thursday with a briefcase and has not once opened it in company.',
    },
    {
      id: 'constance',
      name: 'Miss Constance Fairweather',
      shortName: 'Miss Fairweather',
      title: 'the late Lord’s ward',
      portrait: '🎀',
      pronouns: 'she',
      trait: 'gloves',
      means: ['strength'],
      blurb: 'Raised at Blackwood since the age of nine; due to come of age this spring.',
    },
    {
      id: 'pemberton',
      name: 'Mrs. Agnes Pemberton',
      shortName: 'Mrs. Pemberton',
      title: 'housekeeper',
      portrait: '🗝️',
      pronouns: 'she',
      trait: 'gloves',
      means: ['stillroom', 'strength'],
      blurb: 'Keeps the keys, the accounts, and her own counsel.',
    },
  ],
  silhouettes,

  motiveItems: {
    hostile: 'an unsent letter, furious in tone',
    indebted: 'a ledger page of debts, underlined twice in red',
    jilted: 'a bundle of returned love-letters, tied with black ribbon',
  },
  flavorItems: [
    'a dog-eared railway timetable',
    'an empty decanter, rinsed clean',
    'a half-finished crossword in an unsteady hand',
    'a novel with a pressed flower at chapter three',
    'a programme from last season’s regatta',
  ],

  roleNames: {
    culprit: 'the guilty party',
    witness: 'the one who saw something near the scene that evening',
    oracle: 'the one who notices what others miss — and I noticed something of the killer',
    confidant: 'the one people confide in; I know the truth of somebody at this table',
    gossip: 'the one who hears what this house whispers',
    alibi: 'accounted for — I was not alone that hour',
    thief: 'a thief, if you must have it — but no murderer',
    begrudged: 'the one with the grudge — I’ll own it, since you would find it out',
    loner: 'the one who kept to themselves; nobody can vouch for me, and I know how that looks',
    drunk: 'not entirely to be relied upon, I fear',
  },
  roleLabels: {
    culprit: 'the murderer',
    witness: 'the one who saw something',
    oracle: 'the observant one',
    confidant: 'the keeper of a secret',
    gossip: 'the gossip',
    alibi: 'one of the pair together',
    thief: 'the hidden thief',
    begrudged: 'the begrudged',
    loner: 'the loner',
    drunk: 'the muddled one',
  },
  deckDescriptions: {
    culprit: 'one of the seven did the murder',
    witness: 'one glimpsed something near the scene',
    oracle: 'one noticed a telling detail of the killer',
    confidant: 'one knows the truth of another’s character',
    gossip: 'one hears everything this house whispers',
    alibi: 'two spent the hour in each other’s company',
    thief: 'one is hiding something — though it is not murder',
    begrudged: 'one nursed a grudge against the dead man — though it is not murder',
    loner: 'one kept entirely to themselves, and none can vouch for them',
    drunk: 'one is sincerely mistaken in what they believe they know',
  },

  scenarioIntro: [
    'The storm took the telephone line at six; the bridge went under an hour later. At eight o’clock, {victim} was found in {scene} — quite dead, and not by accident. It happened {window}. No one has come to the house, and no one has left it.',
    'Seven guests. One house, cut off by the flood. And in {scene}, {victim}, who will not be coming down to dinner. The deed was done {window}. The killer is still at the table — and you have until midnight to say their name.',
  ],

  interludes: [
    'The rain sets in for the night, and the house holds its breath. The investigation is yours, detective.',
    'The rain doubles against the windows, and somewhere upstairs a door closes softly.',
    'The candles are burning low; the guests have stopped pretending to read.',
    'The fire is down to embers. Someone in this house is watching you work.',
    'The clock clears its throat. It is now, detective, or it is never.',
  ],

  dialogue,
}
