import type { SettingPack } from '../schema'
import type { DialogueBanks } from '../schema'
import { dialogue } from './dialogue'
import { manners } from './manners'
import { silhouettes, traitLooks } from './silhouettes'

/** Lay one set of banks over another; where both have a bank, its lines are pooled. */
function pooled(...sets: DialogueBanks[]): DialogueBanks {
  const out: DialogueBanks = {}
  for (const set of sets) {
    for (const [key, lines] of Object.entries(set)) out[key] = [...(out[key] ?? []), ...lines]
  }
  return out
}

export const manor1920s: SettingPack = {
  id: 'manor1920s',
  title: 'Blackwood Manor, 1926',
  victim: {
    name: 'Lord Edgar Blackwood',
    shortName: 'Lord Blackwood',
    title: 'master of Blackwood Manor',
    pronouns: 'he',
  },
  windowLabel: 'between half past six and half past seven, while the house dressed for dinner',

  rooms: [
    {
      id: 'study',
      name: 'the study',
      searchFlavor: [
        'Papers in stern stacks, a globe that spins with a squeak. Nothing here speaks.',
        'The desk drawers hold sealing-wax, string, and a smell of old cigars.',
      ],
    },
    {
      id: 'library',
      name: 'the library',
      searchFlavor: [
        'A ladder on brass rails, a thousand unread spines. The dust lies undisturbed.',
        'Someone left a novel face-down on the arm of a chair. It tells you nothing.',
      ],
    },
    {
      id: 'conservatory',
      kind: 'glasshouse',
      name: 'the conservatory',
      searchFlavor: [
        'Ferns sweat against the glass. The gravel path bears no useful print.',
        'Orchids, damp heat, a watering-can half full. Nothing out of place.',
      ],
    },
    {
      id: 'billiards',
      name: 'the billiard room',
      searchFlavor: [
        'The baize is brushed, the balls racked. A game was finished, or never begun.',
        'Cues in their rack like rifles. The scoreboard still shows an old game.',
      ],
    },
    {
      id: 'drawing',
      name: 'the drawing room',
      searchFlavor: [
        'Cold tea in thin china. The cushions confess nothing.',
        'The gramophone holds a dance record, its needle worn. No help there.',
      ],
    },
    {
      id: 'dining',
      name: 'the dining room',
      searchFlavor: [
        'Seven places laid for a dinner nobody ate. The silver is all accounted for.',
        'The candles have burned to different heights. Curious, but idle.',
      ],
    },
    {
      id: 'kitchen',
      name: 'the kitchen',
      searchFlavor: [
        'Copper pans, a sulking stove, a pheasant that will now go to waste.',
        'The knife block is full. You counted twice.',
      ],
    },
    {
      id: 'terrace',
      kind: 'outdoor',
      name: 'the garden terrace',
      searchFlavor: [
        'Rain has scrubbed the flagstones clean. The roses keep their own counsel.',
        'A forgotten shawl on the balustrade, damp with evening. Nobody claims the night was warm.',
      ],
    },
  ],
  sceneRooms: ['study', 'conservatory', 'billiards'],
  valuableRooms: ['study', 'library', 'drawing'],
  docRooms: ['study', 'library', 'drawing'],

  traits: [
    {
      id: 'cane',
      label: 'walks with a cane',
      furtiveLabel: 'leans on a cane, and resents the need of it',
      evidenceName: 'fresh scuff-marks of a cane ferrule',
    },
    {
      id: 'smoker',
      label: 'smokes like a chimney',
      furtiveLabel: 'smokes, and would rather you had not noticed',
      evidenceName: 'a spill of fresh tobacco ash',
    },
    {
      id: 'perfume',
      label: 'wears a distinctive scent',
      furtiveLabel: 'wears a scent, and seems shy of it',
      evidenceName: 'a lingering trace of scent',
    },
    {
      id: 'spectacles',
      label: 'wears spectacles',
      furtiveLabel: 'wears spectacles, and keeps taking them off',
      evidenceName: 'a cracked spectacle lens',
    },
    {
      id: 'gloves',
      label: 'is never without gloves',
      furtiveLabel: 'keeps gloves on, and fidgets with the buttons',
      evidenceName: 'a torn kid glove',
    },
  ],

  means: [
    { id: 'stillroom', label: 'keeps a key to the still-room' },
    { id: 'firearms', label: 'knew the gun-room cupboard' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a vial from the still-room, half-empty, smelling of bitter almonds',
      methodLine: 'poisoned — by a hand with still-room access',
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'the gun-room revolver, one round spent, hastily hidden',
      methodLine: 'shot — by someone who knew the gun-room cupboard',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the heavy brass poker, wiped ill',
      methodLine: 'struck down — by someone with the strength for it',
    },
  ],

  characters: [
    {
      id: 'colonel',
      name: 'Colonel Rupert Ashworth',
      shortName: 'the Colonel',
      title: 'retired officer',
      portrait: '🎖️',
      pronouns: 'he',
      leanings: { cane: 0.9, smoker: 0.7, perfume: 0.1, spectacles: 0.4, gloves: 0.5 },
      means: ['firearms', 'strength'],
      manners: { boastful: 0.8, prickly: 0.6, blunt: 0.5, rambling: 0.4 },
      voice: { pitch: 131, wave: 'triangle', lilt: 1.5, clip: 0.1, ring: 0.8 },
      blurb: 'Served with the late Lord Blackwood the elder; treats the manor as a mess hall.',
    },
    {
      id: 'vicar',
      name: 'Reverend James Whitfield',
      shortName: 'the Reverend',
      title: 'vicar of the parish',
      portrait: '📖',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.1, perfume: 0.1, spectacles: 0.8, gloves: 0.3 },
      means: ['strength'],
      manners: { gracious: 0.8, rambling: 0.7, reserved: 0.4, gossipy: 0.3 },
      voice: { pitch: 196, wave: 'triangle', lilt: 1.5, clip: 0.09, ring: 0.6 },
      blurb: 'Gentle in the pulpit, sharp at the card table.',
    },
    {
      id: 'trent',
      name: 'Mr. Hugo Trent',
      shortName: 'Mr. Trent',
      title: 'business partner',
      portrait: '💼',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.9, perfume: 0.3, spectacles: 0.4, gloves: 0.4 },
      means: ['firearms', 'stillroom'],
      manners: { boastful: 0.9, gossipy: 0.5, dramatic: 0.4, prickly: 0.3 },
      voice: { pitch: 147, wave: 'square', lilt: 2.5, clip: 0.08, ring: 0.6 },
      blurb: 'Half of Blackwood & Trent, Importers. The half that does the talking.',
    },
    {
      id: 'josephine',
      name: 'Miss Josephine Hart',
      shortName: 'Miss Hart',
      title: 'jazz singer',
      portrait: '🎤',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.9, perfume: 0.8, spectacles: 0.1, gloves: 0.7 },
      means: ['firearms'],
      manners: { dramatic: 0.8, gossipy: 0.6, cheeky: 0.5, boastful: 0.4 },
      voice: { pitch: 277, wave: 'sine', lilt: 3.5, clip: 0.08 },
      blurb: 'Engaged for the evening’s entertainment; stayed for the weekend.',
    },
    {
      id: 'vivienne',
      name: 'Lady Vivienne Marsh',
      shortName: 'Lady Marsh',
      title: 'society widow',
      portrait: '🕊️',
      pronouns: 'she',
      leanings: { cane: 0.3, smoker: 0.4, perfume: 0.9, spectacles: 0.2, gloves: 0.8 },
      means: ['stillroom'],
      manners: { gracious: 0.7, gossipy: 0.7, dramatic: 0.5 },
      voice: { pitch: 330, wave: 'triangle', lilt: 2, clip: 0.075 },
      blurb: 'Twice widowed, thrice invited everywhere.',
    },
    {
      id: 'elsie',
      name: 'Elsie Dunn',
      shortName: 'Elsie',
      title: 'parlour maid',
      portrait: '🕯️',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.15, perfume: 0.5, spectacles: 0.3, gloves: 0.5 },
      means: ['stillroom', 'strength'],
      manners: { deferential: 0.9, gossipy: 0.5, cheeky: 0.3, reserved: 0.3 },
      voice: { pitch: 466, wave: 'square', lilt: 3, clip: 0.045, gain: 0.8 },
      blurb: 'Sees every room in the house before anyone is awake in it.',
    },
    {
      id: 'ellison',
      name: 'Dr. Edmund Ellison',
      shortName: 'Dr. Ellison',
      title: 'family physician',
      portrait: '🩺',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.4, perfume: 0.1, spectacles: 0.9, gloves: 0.4 },
      means: ['stillroom'],
      manners: { reserved: 0.8, gracious: 0.6, rambling: 0.4 },
      voice: { pitch: 165, wave: 'triangle', lilt: 1, clip: 0.1, ring: 0.7 },
      blurb: 'Has attended the family for thirty years, and their secrets longer.',
    },
    {
      id: 'barrow',
      name: 'Mr. Felix Barrow',
      shortName: 'Mr. Barrow',
      title: 'the family solicitor',
      portrait: '📜',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.3, perfume: 0.1, spectacles: 0.9, gloves: 0.5 },
      means: ['firearms'],
      manners: { reserved: 0.8, prickly: 0.6, gracious: 0.3 },
      voice: { pitch: 220, wave: 'square', lilt: 1, clip: 0.06, ring: 0.4 },
      blurb: 'Arrived Thursday with a briefcase and has not once opened it in company.',
    },
    {
      id: 'constance',
      name: 'Miss Constance Fairweather',
      shortName: 'Miss Fairweather',
      title: 'the late Lord’s ward',
      portrait: '🎀',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.1, perfume: 0.7, spectacles: 0.4, gloves: 0.9 },
      means: ['strength'],
      manners: { gracious: 0.6, dramatic: 0.6, cheeky: 0.4, reserved: 0.3 },
      voice: { pitch: 554, wave: 'sine', lilt: 3, clip: 0.055 },
      blurb: 'Raised at Blackwood since the age of nine; due to come of age this spring.',
    },
    {
      id: 'pemberton',
      name: 'Mrs. Agnes Pemberton',
      shortName: 'Mrs. Pemberton',
      title: 'housekeeper',
      portrait: '🗝️',
      pronouns: 'she',
      leanings: { cane: 0.4, smoker: 0.1, perfume: 0.3, spectacles: 0.6, gloves: 0.8 },
      means: ['stillroom', 'strength'],
      manners: { prickly: 0.7, reserved: 0.6, deferential: 0.4, blunt: 0.4 },
      voice: { pitch: 233, wave: 'sawtooth', lilt: 1.5, clip: 0.065 },
      blurb: 'Keeps the keys, the accounts, and her own counsel.',
    },
    {
      id: 'captain',
      name: 'Captain Josiah Thorne',
      shortName: 'the Captain',
      title: 'retired sea captain',
      portrait: '⚓',
      pronouns: 'he',
      leanings: { cane: 0.85, smoker: 0.8, perfume: 0.05, spectacles: 0.4, gloves: 0.2 },
      means: ['firearms', 'strength'],
      manners: { boastful: 0.9, blunt: 0.7, rambling: 0.5 },
      voice: { pitch: 139, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.8 },
      blurb: 'Has been round the Horn four times, and will take you round it a fifth over the port.',
    },
    {
      id: 'explorer',
      name: 'Mr. Adrian Sinclair',
      shortName: 'Mr. Sinclair',
      title: 'explorer, lately returned',
      portrait: '🧭',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.8, perfume: 0.1, spectacles: 0.4, gloves: 0.3 },
      means: ['firearms', 'strength'],
      manners: { boastful: 0.9, dramatic: 0.5, rambling: 0.4 },
      voice: { pitch: 175, wave: 'square', lilt: 2.5, clip: 0.07, ring: 0.5 },
      blurb: 'Three years up a river nobody else has heard of, and finds the drawing room rather cramped.',
    },
    {
      id: 'gardener',
      name: 'Mr. Thomas Wickham',
      shortName: 'Mr. Wickham',
      title: 'the head gardener',
      portrait: '🌱',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.6, perfume: 0.1, spectacles: 0.3, gloves: 0.85 },
      means: ['stillroom', 'strength'],
      manners: { blunt: 0.9, reserved: 0.5, deferential: 0.4, rambling: 0.3 },
      voice: { pitch: 156, wave: 'triangle', lilt: 1, clip: 0.11, ring: 0.7 },
      blurb: 'On first-name terms with every rose in the county, and rather fewer of its people.',
    },
    {
      id: 'scullery',
      name: 'Lucy Brennan',
      shortName: 'Lucy',
      title: 'scullery maid',
      portrait: '🧹',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.1, perfume: 0.4, spectacles: 0.4, gloves: 0.6 },
      means: ['stillroom'],
      manners: { deferential: 0.9, reserved: 0.5, gossipy: 0.4, cheeky: 0.3 },
      voice: { pitch: 494, wave: 'sine', lilt: 2.5, clip: 0.05 },
      blurb: 'Six weeks in service, and already knows which stairs creak and who uses them after dark.',
    },
    {
      id: 'bootboy',
      name: 'Herbert Grayson',
      shortName: 'Herbert',
      title: 'the bootboy',
      portrait: '🥾',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.15, perfume: 0.05, spectacles: 0.5, gloves: 0.5 },
      means: ['strength'],
      manners: { deferential: 0.7, cheeky: 0.7, reserved: 0.5 },
      voice: { pitch: 392, wave: 'square', lilt: 3.5, clip: 0.045, gain: 0.8 },
      blurb: 'Fourteen, and can tell you where any guest has walked by what he scrapes off their boots.',
    },
    {
      id: 'nanny',
      name: 'Nanny Connelly',
      shortName: 'Nanny Connelly',
      title: 'the old nursemaid',
      portrait: '🧶',
      pronouns: 'she',
      leanings: { cane: 0.7, smoker: 0.05, perfume: 0.6, spectacles: 0.9, gloves: 0.3 },
      means: ['stillroom'],
      manners: { gossipy: 0.9, rambling: 0.8, gracious: 0.4 },
      voice: { pitch: 294, wave: 'triangle', lilt: 3.5, clip: 0.05 },
      blurb: 'Raised three generations of Blackwoods, and will tell you about each of them whether you ask or not.',
    },
    {
      id: 'butler',
      name: 'Mr. Joseph Greenwood',
      shortName: 'the Butler',
      title: 'the butler',
      portrait: '🔔',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.1, perfume: 0.3, spectacles: 0.6, gloves: 0.9 },
      means: ['stillroom', 'firearms'],
      manners: { reserved: 0.8, deferential: 0.7, prickly: 0.3 },
      voice: { pitch: 147, wave: 'triangle', lilt: 0.8, clip: 0.1, ring: 0.7 },
      blurb: 'Has announced four hundred dinners at Blackwood and approved of perhaps six.',
    },
    {
      id: 'cook',
      name: 'Mrs. Margaret Stone',
      shortName: 'Mrs. Stone',
      title: 'the cook',
      portrait: '🥄',
      pronouns: 'she',
      leanings: { cane: 0.3, smoker: 0.2, perfume: 0.1, spectacles: 0.6, gloves: 0.4 },
      means: ['stillroom', 'strength'],
      manners: { blunt: 0.8, prickly: 0.6, gossipy: 0.5 },
      voice: { pitch: 247, wave: 'sawtooth', lilt: 2, clip: 0.06 },
      blurb: 'Rules the kitchen by divine right, and regards the dining room as a colony.',
    },
    {
      id: 'chauffeur',
      name: 'Mr. Robert Chambers',
      shortName: 'Mr. Chambers',
      title: 'the chauffeur',
      portrait: '🚗',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.7, perfume: 0.3, spectacles: 0.3, gloves: 0.9 },
      means: ['firearms', 'strength'],
      manners: { deferential: 0.6, blunt: 0.6, reserved: 0.4, cheeky: 0.3 },
      voice: { pitch: 185, wave: 'square', lilt: 2, clip: 0.06, ring: 0.4 },
      blurb: 'Knows where everyone has been driven, and has so far been too well paid to say.',
    },
    {
      id: 'dowager',
      name: 'Lady Augusta Penhallow',
      shortName: 'the Dowager',
      title: 'a formidable aunt',
      portrait: '👑',
      pronouns: 'she',
      leanings: { cane: 0.85, smoker: 0.1, perfume: 0.6, spectacles: 0.8, gloves: 0.6 },
      means: ['stillroom'],
      manners: { prickly: 0.9, dramatic: 0.5, rambling: 0.4, boastful: 0.3 },
      voice: { pitch: 262, wave: 'sawtooth', lilt: 1, clip: 0.08, ring: 0.3 },
      blurb: 'Has disapproved of every marriage in the family since 1881, and been right about most.',
    },
    {
      id: 'painter',
      name: 'Mr. Vincent Mallory',
      shortName: 'Mr. Mallory',
      title: 'portrait painter',
      portrait: '🎨',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.85, perfume: 0.6, spectacles: 0.4, gloves: 0.1 },
      means: ['strength'],
      manners: { dramatic: 0.9, boastful: 0.6, rambling: 0.4, cheeky: 0.3 },
      voice: { pitch: 208, wave: 'sine', lilt: 3.5, clip: 0.08, ring: 0.4 },
      blurb: 'Engaged to paint his lordship in May; still, he explains, waiting for the light.',
    },
    {
      id: 'heiress',
      name: 'Miss Dorothy Vandermeer',
      shortName: 'Miss Vandermeer',
      title: 'American heiress',
      portrait: '💎',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.6, perfume: 0.9, spectacles: 0.1, gloves: 0.7 },
      means: ['firearms'],
      manners: { gossipy: 0.6, blunt: 0.5, dramatic: 0.5, cheeky: 0.5 },
      voice: { pitch: 440, wave: 'triangle', lilt: 3, clip: 0.06 },
      blurb: 'Chicago money, Paris frocks, and a habit of saying aloud what the county only thinks.',
    },
  ],
  silhouettes,
  traitLooks,

  motiveItems: {
    hostile: 'an unsent letter, furious in tone',
    indebted: 'a ledger page of debts, underlined twice in red',
    jilted: 'a bundle of returned love-letters, tied with black ribbon',
  },
  flavorItems: [
    'a dog-eared railway timetable',
    'an empty decanter, rinsed clean',
    'a half-finished crossword in an unsteady hand',
    'a novel with a pressed flower at chapter three',
    'a programme from last season’s regatta',
  ],

  roleNames: {
    culprit: 'the Murderer',
    witness: 'the Witness',
    oracle: 'the Observer',
    confidant: 'the Confidant',
    gossip: 'the Gossip',
    sleuth: 'the Sleuth',
    steward: 'the Steward',
    collector: 'the Collector',
    alibi: 'the Companion',
    thief: 'the Thief',
    begrudged: 'the Begrudged',
    loner: 'the Loner',
    redherring: 'the Red Herring',
    blackmailer: 'the Blackmailer',
    amnesiac: 'the Amnesiac',
    sweetheart: 'the Sweetheart',
    accomplice: 'the Accomplice',
    forger: 'the Forger',
    drunk: 'the Drunk',
  },
  roleLabels: {
    culprit: 'the Murderer',
    witness: 'the Witness',
    oracle: 'the Observer',
    confidant: 'the Confidant',
    gossip: 'the Gossip',
    sleuth: 'the Sleuth',
    steward: 'the Steward',
    collector: 'the Collector',
    alibi: 'the Companion',
    thief: 'the Thief',
    begrudged: 'the Begrudged',
    loner: 'the Loner',
    redherring: 'the Red Herring',
    blackmailer: 'the Blackmailer',
    amnesiac: 'the Amnesiac',
    sweetheart: 'the Sweetheart',
    accomplice: 'the Accomplice',
    forger: 'the Forger',
    drunk: 'the Drunk',
  },
  deckDescriptions: {
    culprit: 'Did the murder, and will tell you they are somebody else.',
    witness: 'Glimpsed somebody near the scene that evening.',
    oracle: 'Noticed a telling detail of the killer.',
    confidant: 'Knows the truth of one other person’s character.',
    gossip: 'Hears what this house whispers: who had cause to hate the dead man.',
    sleuth: 'Has narrowed it to three of the household: one of them is the murderer.',
    steward: 'Sat between two of the household all evening, and knows how many of that pair are lying about where they were.',
    collector: 'Took something up from one of the rooms before you could search it, and will hand it over when asked who they are.',
    alibi: 'Spent the hour in the company of one of the innocent, who will say the same.',
    thief: 'Stole something tonight and will lie to hide it, claiming to be somebody else — but did no murder.',
    begrudged: 'Nursed a grudge against the dead man — but did no murder.',
    loner: 'Kept entirely to themselves. Nothing vouches for them.',
    redherring: 'Was seen at the scene this evening — but earlier, before the murder. Did nothing.',
    blackmailer: 'Has been bleeding several of the household, who will point at them before anyone. Will claim to be somebody else — but did no murder.',
    amnesiac: 'Cannot remember where they were. Only the room itself can tell you.',
    sweetheart: 'Spent the hour with one of the innocent, and would sooner lie than say so. Will claim to be somebody else, and to have been alone, until pressed.',
    accomplice: 'Stands with the murderer. Will claim to be the Companion, and swear the murderer was beside them.',
    forger: 'Stands with the murderer. Will claim to be the Collector, and hand you something made to bear the murderer out.',
    drunk: 'Sincerely believes they are somebody else, and is mistaken in what they tell you.',
  },
  roleIcons: {
    culprit: 'dagger',
    witness: 'eye',
    oracle: 'search',
    confidant: 'speech',
    gossip: 'ear',
    sleuth: 'list',
    steward: 'star',
    collector: 'box',
    alibi: 'pair',
    thief: 'gem',
    begrudged: 'flame',
    loner: 'moon',
    redherring: 'fish',
    blackmailer: 'letter',
    amnesiac: 'question',
    sweetheart: 'heart',
    accomplice: 'mask',
    forger: 'pen',
    drunk: 'glass',
  },
  roleAsides: {
    alibi: 'I was not alone that hour.',
    collector: 'I picked something up this evening that you had better have.',
    begrudged: 'I had my quarrel with him, and I’ll own it, since you would find it out.',
    loner: 'I kept to myself. Nobody can vouch for me, and I know how that looks.',
    redherring: 'I was in that room this evening, yes — but earlier, and he was alive and well when I left it.',
    amnesiac: 'Do not ask me for that hour. I have not got it.',
    sweetheart: 'There is someone in this house I care for, and I will say no more of it than that.',
    thief: 'A thief, if you must have it — but no murderer.',
  },

  scenarioIntro: [
    'The storm took the telephone line at six; the bridge went under an hour later. At eight o’clock, {victim} was found in {scene} — quite dead, and not by accident. It happened {window}. No one has come to the house, and no one has left it.',
    'Seven guests. One house, cut off by the flood. And in {scene}, {victim}, who will not be coming down to dinner. The deed was done {window}. The killer is still at the table — and you have until midnight to say their name.',
  ],

  interludes: [
    'The rain sets in for the night, and the house holds its breath. The investigation is yours, {detective}.',
    'The rain doubles against the windows, and somewhere upstairs a door closes softly.',
    'The candles are burning low; the guests have stopped pretending to read.',
    'The fire is down to embers. Someone in this house is watching you work.',
    'The clock clears its throat. It is now, {detective}, or it is never.',
  ],

  dialogue: pooled(dialogue, manners),
}
