import type { SettingPack } from '../schema'
import type { DialogueBanks } from '../schema'
import { dialogue } from './dialogue'
import { itemArt } from './items'
import { manners } from './manners'
import { motiveLines, olderMotiveLines } from './motiveLines'
import { silhouettes, traitLooks } from './silhouettes'

/** Lay one set of banks over another; where both have a bank, its lines are pooled. */
function pooled(...sets: DialogueBanks[]): DialogueBanks {
  const out: DialogueBanks = {}
  for (const set of sets) {
    for (const [key, lines] of Object.entries(set)) out[key] = [...(out[key] ?? []), ...lines]
  }
  return out
}

import { heartyLines } from './heartyLines'
import { helperLines } from './helperLines'
import { murdererLines } from './murdererLines'
import { observedLines } from './observedLines'

export const manor1920s: SettingPack = {
  id: 'manor1920s',
  title: 'Blackwood Manor, 1926',
  victim: {
    name: 'Lord Edgar Blackwood',
    shortName: 'Lord Blackwood',
    title: 'master of Blackwood Manor',
    pronouns: 'he',
    firstName: 'Edgar',
    lastName: 'Blackwood',
    respectful: 'his lordship',
    parental: 'Father',
  },
  place: {
    name: 'the house',
    here: 'this house',
    people: 'the household',
    plan: 'the plan of the house',
    gathering:
      'Storm at the windows, a body upstairs, and seven guests in the hall — each with something to say before the questioning begins.',
  },
  weather: 'storm',
  windowLabel: 'between half past six and half past seven, while the house dressed for dinner',

  rooms: [
    {
      id: 'study',
      name: 'the study',
      searchFlavor: [
        'Papers in stern stacks, a globe that spins with a squeak. Nothing here speaks.',
        'The desk drawers hold sealing-wax, string, and a smell of old cigars.',
      ],
    },
    {
      id: 'library',
      name: 'the library',
      searchFlavor: [
        'A ladder on brass rails, a thousand unread spines. The dust lies undisturbed.',
        'Someone left a novel face-down on the arm of a chair. It tells you nothing.',
      ],
    },
    {
      id: 'conservatory',
      kind: 'glasshouse',
      name: 'the conservatory',
      searchFlavor: [
        'Ferns sweat against the glass. The gravel path bears no useful print.',
        'Orchids, damp heat, a watering-can half full. Nothing out of place.',
      ],
    },
    {
      id: 'billiards',
      name: 'the billiard room',
      searchFlavor: [
        'The baize is brushed, the balls racked. A game was finished, or never begun.',
        'Cues in their rack like rifles. The scoreboard still shows an old game.',
      ],
    },
    {
      id: 'drawing',
      name: 'the drawing room',
      searchFlavor: [
        'Cold tea in thin china. The cushions confess nothing.',
        'The gramophone holds a dance record, its needle worn. No help there.',
      ],
    },
    {
      id: 'dining',
      name: 'the dining room',
      searchFlavor: [
        'Seven places laid for a dinner nobody ate. The silver is all accounted for.',
        'The candles have burned to different heights. Curious, but idle.',
      ],
    },
    {
      id: 'kitchen',
      name: 'the kitchen',
      searchFlavor: [
        'Copper pans, a sulking stove, a pheasant that will now go to waste.',
        'The knife block is full. You counted twice.',
      ],
    },
    {
      id: 'terrace',
      kind: 'outdoor',
      name: 'the garden terrace',
      where: 'on the garden terrace',
      searchFlavor: [
        'Rain has scrubbed the flagstones clean. The roses keep their own counsel.',
        'A forgotten shawl on the balustrade, damp with evening. Nobody claims the night was warm.',
      ],
    },
  ],
  sceneRooms: ['study', 'library', 'drawing', 'billiards', 'conservatory', 'kitchen', 'dining', 'terrace'],
  valuableRooms: ['study', 'library', 'drawing'],
  docRooms: ['study', 'library', 'drawing'],

  traits: [
    {
      id: 'cane',
      label: 'walks with a cane',
      furtiveLabel: 'leans on a cane, and resents the need of it',
      evidenceName: 'fresh scuff-marks of a cane ferrule',
    },
    {
      id: 'smoker',
      label: 'smokes like a chimney',
      furtiveLabel: 'smokes, and would rather you had not noticed',
      evidenceName: 'a spill of fresh tobacco ash',
    },
    {
      id: 'perfume',
      label: 'wears a distinctive scent',
      furtiveLabel: 'wears a scent, and seems shy of it',
      evidenceName: 'a lingering trace of scent',
    },
    {
      id: 'spectacles',
      label: 'wears spectacles',
      furtiveLabel: 'wears spectacles, and keeps taking them off',
      evidenceName: 'a cracked spectacle lens',
    },
    {
      id: 'gloves',
      label: 'is never without gloves',
      furtiveLabel: 'keeps gloves on, and fidgets with the buttons',
      evidenceName: 'a torn kid glove',
    },
  ],

  means: [
    { id: 'stillroom', label: 'keeps a key to the still-room' },
    { id: 'firearms', label: 'knew the gun-room cupboard' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the kitchen and its knives' },
    { id: 'motor', label: 'can drive the motor-car' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a vial from the still-room, half-empty, smelling of bitter almonds',
      methodLine: 'poisoned — by a hand with still-room access',
      rooms: ['study', 'library', 'drawing', 'billiards', 'conservatory', 'kitchen', 'dining'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'the gun-room revolver, one round spent, hastily hidden',
      methodLine: 'shot — by someone who knew the gun-room cupboard',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the heavy brass poker, wiped ill',
      methodLine: 'struck down — by someone with the strength for it',
      rooms: ['study', 'library', 'drawing', 'billiards', 'dining'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a curtain cord, cut from its rail and knotted',
      methodLine: 'strangled — by someone with the strength for it',
      rooms: ['study', 'library', 'drawing', 'billiards', 'dining'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a boning knife from the kitchen block, rinsed and put back wet',
      methodLine: 'stabbed — by someone with the run of the kitchen knives',
    },
    {
      id: 'fall',
      means: 'strength',
      weaponName: 'a length of the balcony rail, broken outward, and scuffed stone above',
      methodLine: 'thrown from the balcony — by someone with the strength for it',
      rooms: ['terrace', 'conservatory'],
    },
    {
      id: 'motor',
      means: 'motor',
      weaponName: 'the motor-car, its wing dented and one lamp smashed',
      methodLine: 'run down with the motor-car — by someone who can drive it',
      rooms: ['terrace'],
    },
  ],

  characters: [
    {
      id: 'colonel',
      name: 'Colonel Rupert Ashworth',
      shortName: 'the Colonel',
      title: 'retired officer',
      portrait: '🎖️',
      pronouns: 'he',
      leanings: { cane: 0.9, smoker: 0.7, perfume: 0.1, spectacles: 0.4, gloves: 0.5 },
      means: ['firearms', 'strength'],
      manners: { boastful: 0.8, prickly: 0.6, blunt: 0.5, rambling: 0.4 },
      motives: { hostile: 0.8, indebted: 0.6, exposed: 0.6, beneficiary: 0.3, rival: 0.3, disinherited: 0.2 },
      voice: { pitch: 131, wave: 'triangle', lilt: 1.5, clip: 0.1, ring: 0.8 },
      blurb: 'Served with the late Lord Blackwood the elder; treats the manor as a mess hall.',
    },
    {
      id: 'vicar',
      name: 'Reverend James Whitfield',
      shortName: 'the Reverend',
      title: 'vicar of the parish',
      portrait: '📖',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.1, perfume: 0.1, spectacles: 0.8, gloves: 0.3 },
      means: ['strength'],
      manners: { gracious: 0.8, rambling: 0.7, reserved: 0.4, gossipy: 0.3 },
      motives: { exposed: 0.8, indebted: 0.6, hostile: 0.5, dismissed: 0.5, beneficiary: 0.3 },
      voice: { pitch: 196, wave: 'triangle', lilt: 1.5, clip: 0.09, ring: 0.6 },
      blurb: 'Gentle in the pulpit, sharp at the card table.',
    },
    {
      id: 'trent',
      name: 'Mr. Hugo Trent',
      shortName: 'Mr. Trent',
      title: 'business partner',
      portrait: '💼',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.9, perfume: 0.3, spectacles: 0.4, gloves: 0.4 },
      means: ['firearms', 'stillroom', 'motor'],
      manners: { boastful: 0.9, hearty: 0.5, gossipy: 0.5, dramatic: 0.4, prickly: 0.3 },
      motives: { rival: 1, indebted: 0.7, hostile: 0.5, exposed: 0.5, forbidden: 0.4 },
      voice: { pitch: 147, wave: 'square', lilt: 2.5, clip: 0.08, ring: 0.6 },
      blurb: 'Half of Blackwood & Trent, Importers. The half that does the talking.',
    },
    {
      id: 'josephine',
      name: 'Miss Josephine Hart',
      shortName: 'Miss Hart',
      title: 'jazz singer',
      portrait: '🎤',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.9, perfume: 0.8, spectacles: 0.1, gloves: 0.7 },
      means: ['firearms'],
      manners: { dramatic: 0.8, gossipy: 0.6, cheeky: 0.5, boastful: 0.4 },
      motives: { jilted: 0.9, exposed: 0.7, forbidden: 0.6, indebted: 0.5, hostile: 0.4, beneficiary: 0.3 },
      voice: { pitch: 277, wave: 'sine', lilt: 3.5, clip: 0.08 },
      blurb: 'Engaged for the evening’s entertainment; stayed for the weekend.',
    },
    {
      id: 'vivienne',
      name: 'Lady Vivienne Marsh',
      shortName: 'Lady Marsh',
      title: 'society widow',
      portrait: '🕊️',
      pronouns: 'she',
      leanings: { cane: 0.3, smoker: 0.4, perfume: 0.9, spectacles: 0.2, gloves: 0.8 },
      means: ['stillroom'],
      manners: { gracious: 0.7, gossipy: 0.7, dramatic: 0.5 },
      motives: { jilted: 0.9, indebted: 0.6, exposed: 0.6, hostile: 0.5, beneficiary: 0.4 },
      voice: { pitch: 330, wave: 'triangle', lilt: 2, clip: 0.075 },
      blurb: 'Twice widowed, thrice invited everywhere.',
    },
    {
      id: 'elsie',
      station: 'servant',
      name: 'Elsie Dunn',
      shortName: 'Elsie',
      title: 'parlour maid',
      portrait: '🕯️',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.15, perfume: 0.5, spectacles: 0.3, gloves: 0.5 },
      means: ['stillroom', 'strength', 'kitchen'],
      manners: { deferential: 0.9, gossipy: 0.5, cheeky: 0.3, reserved: 0.3 },
      motives: { dismissed: 1, exposed: 0.6, forbidden: 0.5, hostile: 0.4, indebted: 0.2 },
      voice: { pitch: 466, wave: 'square', lilt: 3, clip: 0.045, gain: 0.8 },
      blurb: 'Sees every room in the house before anyone is awake in it.',
    },
    {
      id: 'ellison',
      name: 'Dr. Edmund Ellison',
      shortName: 'Dr. Ellison',
      title: 'family physician',
      portrait: '🩺',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.4, perfume: 0.1, spectacles: 0.9, gloves: 0.4 },
      means: ['stillroom'],
      manners: { reserved: 0.8, gracious: 0.6, rambling: 0.4 },
      motives: { exposed: 0.8, indebted: 0.6, hostile: 0.5, beneficiary: 0.4, forbidden: 0.4, rival: 0.3 },
      voice: { pitch: 165, wave: 'triangle', lilt: 1, clip: 0.1, ring: 0.7 },
      blurb: 'Has attended the family for thirty years, and their secrets longer.',
    },
    {
      id: 'barrow',
      name: 'Mr. Felix Barrow',
      shortName: 'Mr. Barrow',
      title: 'the family solicitor',
      portrait: '📜',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.3, perfume: 0.1, spectacles: 0.9, gloves: 0.5 },
      means: ['firearms'],
      manners: { reserved: 0.8, prickly: 0.6, gracious: 0.3 },
      motives: { exposed: 0.8, indebted: 0.7, rival: 0.5, beneficiary: 0.5, dismissed: 0.5, hostile: 0.4 },
      voice: { pitch: 220, wave: 'square', lilt: 1, clip: 0.06, ring: 0.4 },
      blurb: 'Arrived Thursday with a briefcase and has not once opened it in company.',
    },
    {
      id: 'constance',
      name: 'Miss Constance Fairweather',
      shortName: 'Miss Fairweather',
      title: 'the late Lord’s ward',
      portrait: '🎀',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.1, perfume: 0.7, spectacles: 0.4, gloves: 0.9 },
      means: ['strength'],
      manners: { gracious: 0.6, dramatic: 0.6, cheeky: 0.4, reserved: 0.3 },
      motives: { disinherited: 1, beneficiary: 0.8, forbidden: 0.6, dismissed: 0.5, hostile: 0.4, exposed: 0.4 },
      voice: { pitch: 554, wave: 'sine', lilt: 3, clip: 0.055 },
      blurb: 'Raised at Blackwood since the age of nine; due to come of age this spring.',
    },
    {
      id: 'pemberton',
      station: 'servant',
      name: 'Mrs. Agnes Pemberton',
      shortName: 'Mrs. Pemberton',
      title: 'housekeeper',
      portrait: '🗝️',
      pronouns: 'she',
      leanings: { cane: 0.4, smoker: 0.1, perfume: 0.3, spectacles: 0.6, gloves: 0.8 },
      means: ['stillroom', 'strength', 'kitchen'],
      manners: { prickly: 0.7, reserved: 0.6, deferential: 0.4, blunt: 0.4 },
      motives: { dismissed: 1, exposed: 0.6, hostile: 0.5, beneficiary: 0.4, jilted: 0.3, indebted: 0.3 },
      voice: { pitch: 233, wave: 'sawtooth', lilt: 1.5, clip: 0.065 },
      blurb: 'Keeps the keys, the accounts, and her own counsel.',
    },
    {
      id: 'captain',
      name: 'Captain Josiah Thorne',
      shortName: 'the Captain',
      title: 'retired sea captain',
      portrait: '⚓',
      pronouns: 'he',
      leanings: { cane: 0.85, smoker: 0.8, perfume: 0.05, spectacles: 0.4, gloves: 0.2 },
      means: ['firearms', 'strength'],
      manners: { boastful: 0.9, blunt: 0.7, hearty: 0.6, rambling: 0.5 },
      motives: { hostile: 0.7, indebted: 0.7, rival: 0.6, exposed: 0.5, beneficiary: 0.3 },
      voice: { pitch: 139, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.8 },
      blurb: 'Has been round the Horn four times, and will take you round it a fifth over the port.',
    },
    {
      id: 'hunter',
      name: 'Major Bertram Kettering',
      shortName: 'the Major',
      title: 'big-game hunter',
      portrait: '🦁',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.85, perfume: 0.05, spectacles: 0.3, gloves: 0.6 },
      means: ['firearms', 'strength', 'motor'],
      manners: { hearty: 1, boastful: 0.6, blunt: 0.4 },
      motives: { indebted: 0.8, rival: 0.7, hostile: 0.6, exposed: 0.5, forbidden: 0.5, beneficiary: 0.3 },
      voice: { pitch: 148, wave: 'square', lilt: 3, clip: 0.08, ring: 0.6 },
      blurb: 'Has shot most things that walk in Africa, and finds the English variety much harder to bring down.',
    },
    {
      id: 'medium',
      name: 'Madame Zelda Voss',
      shortName: 'Madame Voss',
      title: 'spiritualist medium',
      portrait: '🔮',
      pronouns: 'she',
      leanings: { cane: 0.2, smoker: 0.4, perfume: 0.9, spectacles: 0.3, gloves: 0.7 },
      means: ['stillroom', 'kitchen'],
      manners: { dramatic: 1, rambling: 0.5, gracious: 0.4, reserved: 0.3 },
      motives: { exposed: 1, indebted: 0.6, hostile: 0.4, dismissed: 0.4, jilted: 0.3, beneficiary: 0.3 },
      voice: { pitch: 205, wave: 'sine', lilt: 4.5, clip: 0.11, ring: 0.2 },
      blurb: 'Speaks for the dead at a guinea a sitting, and has never yet been told anything by them that she did not already know.',
    },
    {
      id: 'explorer',
      name: 'Mr. Adrian Sinclair',
      shortName: 'Mr. Sinclair',
      title: 'explorer, lately returned',
      portrait: '🧭',
      pronouns: 'he',
      leanings: { cane: 0.5, smoker: 0.8, perfume: 0.1, spectacles: 0.4, gloves: 0.3 },
      means: ['firearms', 'strength', 'motor'],
      manners: { boastful: 0.9, hearty: 0.7, dramatic: 0.5, rambling: 0.4 },
      motives: { indebted: 0.9, forbidden: 0.6, rival: 0.5, exposed: 0.5, hostile: 0.5 },
      voice: { pitch: 175, wave: 'square', lilt: 2.5, clip: 0.07, ring: 0.5 },
      blurb: 'Three years up a river nobody else has heard of, and finds the drawing room rather cramped.',
    },
    {
      id: 'gardener',
      station: 'servant',
      name: 'Mr. Thomas Wickham',
      shortName: 'Mr. Wickham',
      title: 'the head gardener',
      portrait: '🌱',
      pronouns: 'he',
      leanings: { cane: 0.6, smoker: 0.6, perfume: 0.1, spectacles: 0.3, gloves: 0.85 },
      means: ['stillroom', 'strength'],
      manners: { blunt: 0.9, reserved: 0.5, deferential: 0.4, rambling: 0.3 },
      motives: { dismissed: 1, hostile: 0.5, exposed: 0.4, indebted: 0.3, beneficiary: 0.3 },
      voice: { pitch: 156, wave: 'triangle', lilt: 1, clip: 0.11, ring: 0.7 },
      blurb: 'On first-name terms with every rose in the county, and rather fewer of its people.',
    },
    {
      id: 'scullery',
      station: 'servant',
      name: 'Lucy Brennan',
      shortName: 'Lucy',
      title: 'scullery maid',
      portrait: '🧹',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.1, perfume: 0.4, spectacles: 0.4, gloves: 0.6 },
      means: ['stillroom', 'kitchen'],
      manners: { deferential: 0.9, reserved: 0.5, gossipy: 0.4, cheeky: 0.3 },
      motives: { dismissed: 1, exposed: 0.5, hostile: 0.3, forbidden: 0.3 },
      voice: { pitch: 494, wave: 'sine', lilt: 2.5, clip: 0.05 },
      blurb: 'Six weeks in service, and already knows which stairs creak and who uses them after dark.',
    },
    {
      id: 'bootboy',
      station: 'servant',
      name: 'Herbert Grayson',
      shortName: 'Herbert',
      title: 'the bootboy',
      portrait: '🥾',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.15, perfume: 0.05, spectacles: 0.5, gloves: 0.5 },
      means: ['strength', 'kitchen'],
      manners: { deferential: 0.7, cheeky: 0.7, reserved: 0.5 },
      motives: { dismissed: 1, hostile: 0.4, exposed: 0.4, indebted: 0.2 },
      voice: { pitch: 392, wave: 'square', lilt: 3.5, clip: 0.045, gain: 0.8 },
      blurb: 'Fourteen, and can tell you where any guest has walked by what he scrapes off their boots.',
    },
    {
      id: 'nanny',
      station: 'servant',
      name: 'Nanny Connelly',
      shortName: 'Nanny Connelly',
      title: 'the old nursemaid',
      portrait: '🧶',
      pronouns: 'she',
      leanings: { cane: 0.7, smoker: 0.05, perfume: 0.6, spectacles: 0.9, gloves: 0.3 },
      means: ['stillroom', 'kitchen'],
      manners: { gossipy: 0.9, rambling: 0.8, gracious: 0.4 },
      motives: { dismissed: 0.9, beneficiary: 0.6, hostile: 0.4, exposed: 0.4 },
      voice: { pitch: 294, wave: 'triangle', lilt: 3.5, clip: 0.05 },
      blurb: 'Raised three generations of Blackwoods, and will tell you about each of them whether you ask or not.',
    },
    {
      id: 'butler',
      station: 'servant',
      name: 'Mr. Joseph Greenwood',
      shortName: 'the Butler',
      title: 'the butler',
      portrait: '🔔',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.1, perfume: 0.3, spectacles: 0.6, gloves: 0.9 },
      means: ['stillroom', 'firearms', 'kitchen'],
      manners: { reserved: 0.8, deferential: 0.7, prickly: 0.3 },
      motives: { dismissed: 0.9, exposed: 0.7, beneficiary: 0.5, hostile: 0.5, indebted: 0.4 },
      voice: { pitch: 147, wave: 'triangle', lilt: 0.8, clip: 0.1, ring: 0.7 },
      blurb: 'Has announced four hundred dinners at Blackwood and approved of perhaps six.',
    },
    {
      id: 'cook',
      station: 'servant',
      name: 'Mrs. Margaret Stone',
      shortName: 'Mrs. Stone',
      title: 'the cook',
      portrait: '🥄',
      pronouns: 'she',
      leanings: { cane: 0.3, smoker: 0.2, perfume: 0.1, spectacles: 0.6, gloves: 0.4 },
      means: ['stillroom', 'strength', 'kitchen'],
      manners: { blunt: 0.8, prickly: 0.6, gossipy: 0.5 },
      motives: { dismissed: 1, hostile: 0.5, exposed: 0.5, indebted: 0.3, jilted: 0.2 },
      voice: { pitch: 247, wave: 'sawtooth', lilt: 2, clip: 0.06 },
      blurb: 'Rules the kitchen by divine right, and regards the dining room as a colony.',
    },
    {
      id: 'chauffeur',
      station: 'servant',
      name: 'Mr. Robert Chambers',
      shortName: 'Mr. Chambers',
      title: 'the chauffeur',
      portrait: '🚗',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.7, perfume: 0.3, spectacles: 0.3, gloves: 0.9 },
      means: ['firearms', 'strength', 'motor'],
      manners: { deferential: 0.6, blunt: 0.6, reserved: 0.4, cheeky: 0.3 },
      motives: { dismissed: 0.9, forbidden: 0.7, exposed: 0.6, indebted: 0.4, hostile: 0.4 },
      voice: { pitch: 185, wave: 'square', lilt: 2, clip: 0.06, ring: 0.4 },
      blurb: 'Knows where everyone has been driven, and has so far been too well paid to say.',
    },
    {
      id: 'dowager',
      name: 'Lady Augusta Penhallow',
      shortName: 'the Dowager',
      title: 'a formidable aunt',
      portrait: '👑',
      pronouns: 'she',
      leanings: { cane: 0.85, smoker: 0.1, perfume: 0.6, spectacles: 0.8, gloves: 0.6 },
      means: ['stillroom'],
      manners: { prickly: 0.9, dramatic: 0.5, rambling: 0.4, boastful: 0.3 },
      motives: { hostile: 0.8, disinherited: 0.7, beneficiary: 0.7, exposed: 0.4, indebted: 0.4 },
      voice: { pitch: 262, wave: 'sawtooth', lilt: 1, clip: 0.08, ring: 0.3 },
      blurb: 'Has disapproved of every marriage in the family since 1881, and been right about most.',
    },
    {
      id: 'painter',
      name: 'Mr. Vincent Mallory',
      shortName: 'Mr. Mallory',
      title: 'portrait painter',
      portrait: '🎨',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.85, perfume: 0.6, spectacles: 0.4, gloves: 0.1 },
      means: ['strength'],
      manners: { dramatic: 0.9, boastful: 0.6, rambling: 0.4, cheeky: 0.3 },
      motives: { forbidden: 0.8, indebted: 0.7, exposed: 0.5, hostile: 0.4, dismissed: 0.3 },
      voice: { pitch: 208, wave: 'sine', lilt: 3.5, clip: 0.08, ring: 0.4 },
      blurb: 'Engaged to paint his lordship in May; still, he explains, waiting for the light.',
    },
    {
      id: 'heiress',
      name: 'Miss Dorothy Vandermeer',
      shortName: 'Miss Vandermeer',
      title: 'American heiress',
      portrait: '💎',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.6, perfume: 0.9, spectacles: 0.1, gloves: 0.7 },
      means: ['firearms', 'motor'],
      manners: { gossipy: 0.6, blunt: 0.5, dramatic: 0.5, cheeky: 0.5 },
      motives: { jilted: 0.8, forbidden: 0.6, rival: 0.5, exposed: 0.5, hostile: 0.4 },
      voice: { pitch: 440, wave: 'triangle', lilt: 3, clip: 0.06 },
      blurb: 'Chicago money, Paris frocks, and a habit of saying aloud what the county only thinks.',
    },
    {
      id: 'daughter',
      station: 'family',
      name: 'Miss Violet Blackwood',
      shortName: 'Miss Blackwood',
      title: 'his lordship’s daughter',
      portrait: '🍸',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.8, perfume: 0.8, spectacles: 0.2, gloves: 0.6 },
      means: ['stillroom', 'firearms', 'motor'],
      manners: { cheeky: 0.8, dramatic: 0.6, prickly: 0.5, gracious: 0.4, blunt: 0.3 },
      motives: { disinherited: 1, beneficiary: 0.9, hostile: 0.6, exposed: 0.6, indebted: 0.5 },
      callsVictim: 'Father',
      kin: 'child',
      voice: { pitch: 370, wave: 'triangle', lilt: 3, clip: 0.06, ring: 0.5 },
      blurb: 'Down from town for the week-end, under protest. Knows where the good brandy is kept.',
    },
    {
      id: 'son',
      station: 'family',
      name: 'Mr. Julian Blackwood',
      shortName: 'Mr. Julian',
      title: 'his lordship’s son',
      portrait: '🎾',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.7, perfume: 0.3, spectacles: 0.3, gloves: 0.5 },
      means: ['firearms', 'strength', 'motor'],
      manners: { hearty: 0.8, boastful: 0.7, cheeky: 0.7, gracious: 0.4, prickly: 0.4, reserved: 0.3 },
      motives: { disinherited: 1, beneficiary: 0.9, indebted: 0.8, hostile: 0.6, exposed: 0.6, rival: 0.4 },
      callsVictim: 'Father',
      kin: 'child',
      voice: { pitch: 185, wave: 'triangle', lilt: 2.5, clip: 0.07, ring: 0.6 },
      blurb: 'Sent down from Oxford, and in no hurry to say why. Has his father’s chin and none of his patience.',
    },
  ],
  silhouettes,
  traitLooks,
  itemArt,

  motiveItems: {
    devoted: [
      'a letter in his lordship’s hand, thanking them warmly',
      'a note from his lordship: “I could not do without you”',
    ],
    hostile: [
      'an unsent letter, furious in tone',
      'a photograph of his lordship, the face scratched out',
      'a solicitor’s letter threatening suit against his lordship',
      'a diary, the pen pressed clean through the page',
    ],
    indebted: [
      'a ledger page of debts, underlined twice in red',
      'a sheaf of notes of hand, made out to his lordship',
      'a pawnbroker’s ticket for the family silver',
      'a banker’s final demand, unopened',
    ],
    jilted: [
      'a bundle of returned love-letters, tied with black ribbon',
      'an engagement ring, returned in its box',
      'a locket with the portrait prised out',
      'a wedding invitation, torn across',
    ],
    disinherited: [
      'a new will, drawn up and not yet signed',
      'a draft of a will, one name struck through',
      'a solicitor’s card: “Monday, eleven — to sign”',
      'his lordship’s letter to his solicitor, asking for a new will',
    ],
    beneficiary: [
      'a will, signed and witnessed this very week',
      'a codicil in a fresh hand, the ink barely dry',
      'a life-assurance policy, lately doubled',
      'a deed-box, newly labelled and newly locked',
    ],
    dismissed: [
      'a letter of dismissal, without a character',
      'a notice to quit by quarter-day',
      'an advertisement for the place, already sent to the paper',
      'an envelope of money, marked “in full and final”',
    ],
    exposed: [
      'an enquiry agent’s report, addressed to his lordship',
      'a newspaper cutting, one name ringed in ink',
      'a telegram: “PROOF IN HAND STOP WILL SPEAK TUESDAY”',
      'a letter in his lordship’s hand, beginning “I know”',
    ],
    rival: [
      'articles of partnership, one clause underlined',
      'a letter dissolving the partnership, ready for the post',
      'a share certificate, made over without consent',
      'the firm’s account book, with a second set of figures',
    ],
    forbidden: [
      'a letter forbidding the match, in his lordship’s hand',
      'a ring, sent back by his lordship’s order',
      'two railway tickets to Gretna Green',
      'a note, much folded: “Father will never consent”',
    ],
  },
  relationLabels: {
    devoted: 'devoted to him',
    cordial: 'on easy terms',
    strained: 'on strained terms',
    hostile: 'at daggers drawn',
    indebted: 'deep in his debt',
    jilted: 'thrown over by him',
    disinherited: 'about to be cut out of his will',
    beneficiary: 'the gainer by his new will',
    dismissed: 'about to be turned out by him',
    exposed: 'about to be exposed by him',
    rival: 'his partner, and being squeezed out',
    forbidden: 'forbidden to marry into his family',
  },
  secondBody: '{name}, dead — and silenced',
  secondTraceBySex: {
    he: 'the print of a man’s shoe, in what was spilled',
    she: 'the print of a woman’s heel, in what was spilled',
  },
  murderers: {
    plain: {
      name: 'the Murderer',
      does: 'Did the murder, and will tell you they are somebody else.',
    },
    serial: {
      name: 'the Serial Murderer',
      does: 'Will kill again as ten o’clock strikes, to silence whoever knows most against them — and, in the hurry of it, leave something of themselves behind.',
    },
    regretful: {
      name: 'the Regretful Murderer',
      does: 'Cannot bear it. When the household is gathered at the last, before you have named anybody, will stand up and say they did it.',
    },
  },
  passageItem: 'a panel in the wall that swings inward on a dark passage',
  bareScene: 'the place where it was done, and nothing it was done with',
  bribeItem: 'an envelope of banknotes, with {name}’s name on it',
  flavorItems: [
    'a dog-eared railway timetable',
    'an empty decanter, rinsed clean',
    'a half-finished crossword in an unsteady hand',
    'a novel with a pressed flower at chapter three',
    'a programme from last season’s regatta',
  ],

  roleNames: {
    culprit: 'the Murderer',
    witness: 'the Witness',
    oracle: 'the Observer',
    confidant: 'the Confidant',
    gossip: 'the Gossip',
    sleuth: 'the Sleuth',
    steward: 'the Steward',
    collector: 'the Collector',
    architect: 'the Architect',
    discoverer: 'the Discoverer',
    alibi: 'the Companion',
    thief: 'the Thief',
    begrudged: 'the Begrudged',
    loner: 'the Loner',
    redherring: 'the Red Herring',
    blackmailer: 'the Blackmailer',
    amnesiac: 'the Amnesiac',
    sweetheart: 'the Sweetheart',
    accomplice: 'the Accomplice',
    forger: 'the Forger',
    framer: 'the Framer',
    cleaner: 'the Cleaner',
    whisperer: 'the Whisperer',
    sponsor: 'the Sponsor',
    martyr: 'the Martyr',
    drunk: 'the Drunk',
  },
  roleLabels: {
    culprit: 'the Murderer',
    witness: 'the Witness',
    oracle: 'the Observer',
    confidant: 'the Confidant',
    gossip: 'the Gossip',
    sleuth: 'the Sleuth',
    steward: 'the Steward',
    collector: 'the Collector',
    architect: 'the Architect',
    discoverer: 'the Discoverer',
    alibi: 'the Companion',
    thief: 'the Thief',
    begrudged: 'the Begrudged',
    loner: 'the Loner',
    redherring: 'the Red Herring',
    blackmailer: 'the Blackmailer',
    amnesiac: 'the Amnesiac',
    sweetheart: 'the Sweetheart',
    accomplice: 'the Accomplice',
    forger: 'the Forger',
    framer: 'the Framer',
    cleaner: 'the Cleaner',
    whisperer: 'the Whisperer',
    sponsor: 'the Sponsor',
    martyr: 'the Martyr',
    drunk: 'the Drunk',
  },
  deckDescriptions: {
    culprit: 'Did the murder, and will tell you they are somebody else.',
    witness: 'Glimpsed somebody near the scene that evening.',
    oracle: 'Was first along the corridor after it was done, and passed somebody coming away from the scene. It may mean everything, or nothing.',
    confidant: 'Knows the truth of one other person’s character.',
    gossip: 'Hears what this house whispers: who had cause to hate the dead man.',
    sleuth: 'Has narrowed it to three of the household: one of them is the murderer.',
    steward: 'Kept an eye on two of the household all evening, and knows how many of that pair are lying about where they were.',
    collector: 'Took something up from one of the rooms before you could search it, and will hand it over when asked who they are.',
    architect: 'Knows the old house and its walls: can tell you which room the secret passage leads to from the scene.',
    discoverer: 'Found him still living, for a moment: heard a last word, or saw a last sign, that tells something of the killer.',
    alibi: 'Sought out company on purpose: spent the hour with one of the innocent, who will say the same. Any two guests may have been together — it does not take a Companion.',
    thief: 'Stole something tonight and will lie to hide it, claiming to be somebody else — but did no murder.',
    begrudged: 'Nursed a grudge against the dead man — but did no murder.',
    loner: 'Was alone, and left no trace of it: nothing vouches for them. Others may have been alone too — but their rooms will bear them out.',
    redherring: 'Was at the scene within the hour, and was seen there — but left before it was done.',
    blackmailer: 'Has been bleeding several of the household, who will point at them before anyone. Will claim to be somebody else — but did no murder.',
    amnesiac: 'Cannot remember where they were. Only the room itself can tell you.',
    sweetheart: 'Spent the hour with one of the innocent, and would sooner lie than say so. Will claim to be somebody else, and to have been alone, until pressed.',
    accomplice: 'Stands with the murderer. Will claim to be the Companion, and swear the murderer was beside them.',
    forger: 'Stands with the murderer. Will claim to be the Collector, and hand you something made to bear the murderer out.',
    framer: 'Stands with the murderer. Has left something of an innocent guest’s at the scene, and will claim to be the Witness who saw them there.',
    cleaner: 'Stands with the murderer. Has carried the weapon off from the scene and hidden it where they spent the hour — and will say they were somewhere else.',
    whisperer: 'Stands with the murderer. Has told one honest guest a story, who will swear to having seen the murderer somewhere they never were.',
    martyr: 'Stands with the murderer. When the household is gathered at the last, will stand up and say they did it — though they lacked the means, or the motive, or the chance.',
    sponsor: 'Stands with the murderer. Has paid a witness to say nothing of what they know — and left the money where it can be found.',
    drunk: 'Sincerely believes they are somebody else, and is mistaken in what they tell you.',
  },
  roleIcons: {
    culprit: 'dagger',
    witness: 'eye',
    oracle: 'search',
    confidant: 'speech',
    gossip: 'ear',
    sleuth: 'list',
    steward: 'star',
    collector: 'box',
    architect: 'door',
    discoverer: 'lantern',
    alibi: 'pair',
    thief: 'gem',
    begrudged: 'flame',
    loner: 'moon',
    redherring: 'fish',
    blackmailer: 'letter',
    amnesiac: 'question',
    sweetheart: 'heart',
    accomplice: 'mask',
    forger: 'pen',
    framer: 'frame',
    cleaner: 'broom',
    whisperer: 'whisper',
    sponsor: 'coin',
    martyr: 'candle',
    drunk: 'glass',
  },
  roleAsides: {
    alibi: 'I was not alone that hour.',
    collector: 'I picked something up this evening that you had better have.',
    begrudged: 'I had my quarrel with him, and I’ll own it, since you would find it out.',
    loner: 'I kept to myself. Nobody can vouch for me, and I know how that looks.',
    redherring: 'I was in that room within the hour, yes — and he was alive and well when I left it.',
    amnesiac: 'Do not ask me for that hour. I have not got it.',
    sweetheart: 'There is someone in this house I care for, and I will say no more of it than that.',
    thief: 'A thief, if you must have it — but no murderer.',
  },

  occasions: [
    {
      id: 'party',
      weight: 3,
      sheet: 'The household was gathered for a weekend party.',
      event: 'quarrel',
      intro: [
        'The storm took the telephone line at six; the bridge went under an hour later. A weekend party, cut off by the flood. At eight o’clock, {victim} was found in {scene} — quite dead, and not by accident. It happened {window}. No one has come to the house, and no one has left it.',
        'Seven guests, asked down for the weekend. One house, cut off by the flood. And in {scene}, {victim}, who will not be coming down to dinner. The deed was done {window}. The killer is still at the table — and you have until midnight to say their name.',
      ],
    },
    {
      id: 'will',
      weight: 2,
      sheet: 'The household was summoned for the signing of a new will.',
      event: 'slam',
      motives: { disinherited: 3, beneficiary: 3, dismissed: 1.5 },
      intro: [
        '{victim} had called them all down for one purpose: his solicitor had drawn up a new will, and he meant to sign it after dinner. The bridge went under at six, and the storm took the telephone. At eight o’clock he was found in {scene} — quite dead, and the will unsigned. It happened {window}. No one has left the house.',
        'A new will, and everybody with an interest in the old one under the same roof. {victim} was to put his name to it tonight. He was found in {scene} first — the deed done {window} — and the flood has shut the house on whoever did it. You have until midnight.',
      ],
    },
    {
      id: 'business',
      weight: 2,
      sheet: 'The household was gathered to settle the affairs of the firm.',
      event: 'telephone',
      motives: { rival: 3, indebted: 2, exposed: 1.5 },
      intro: [
        'The partners, the creditors, and one or two who would not say which they were: {victim} had called them to Blackwood to settle the firm’s affairs, and had spent the day on the telephone with the City. The line went at six, the bridge at seven. At eight o’clock he was found in {scene} — quite dead. It happened {window}. No one has left.',
        'Money had brought them all to the house, and money kept them there when the flood cut the road. {victim} was found in {scene}, the deed done {window}, and the firm’s affairs are now the least of anybody’s troubles. The killer is still at the table. You have until midnight.',
      ],
    },
    {
      id: 'engagement',
      weight: 2,
      sheet: 'The household was gathered for a dinner to announce an engagement.',
      event: 'walkout',
      motives: { forbidden: 3, jilted: 2 },
      intro: [
        'It was to have been a happy evening: a dinner, a toast, an engagement announced — and {victim} had let it be known that afternoon that he would not give his blessing. The storm cut the house off at six. At eight o’clock he was found in {scene} — quite dead, and no toast drunk. It happened {window}.',
        'The champagne was on ice and the house was full for the announcement. Instead, {victim} was found in {scene}, the deed done {window}, and the flood has shut the door on the lot of them. Somebody at that table did it — and you have until midnight to say who.',
      ],
    },
  ],
  scenarioIntro: [
    'The storm took the telephone line at six; the bridge went under an hour later. At eight o’clock, {victim} was found in {scene} — quite dead, and not by accident. It happened {window}. No one has come to the house, and no one has left it.',
    'Seven guests. One house, cut off by the flood. And in {scene}, {victim}, who will not be coming down to dinner. The deed was done {window}. The killer is still at the table — and you have until midnight to say their name.',
  ],

  dialogue: pooled(
    dialogue,
    manners,
    motiveLines,
    olderMotiveLines,
    helperLines,
    observedLines,
    murdererLines,
    heartyLines,
  ),
}
