// New Scotland Yard, January 1928: rain and fog over Whitehall, the doors
// locked on the division's own people, and somebody dead in the building,
// Chief Inspector Craddock as often as not. Sergeant Pike is at the table
// with the rest of the division, and so is the Chief Inspector when he is not
// the one dead. The rooms are the building's; the household is the division
// and whoever was caught inside when the doors were locked. Everything not its
// own — the roles, the papers, the way the people talk — it shares with the
// manor.

import type { CharacterDef, SettingPack } from '../schema'
import { PIKE_VOICE } from '../lifelines'
import { manor1920s } from '../manor1920s'
import { YARD_SILHOUETTES } from './silhouettes'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const yard1928: SettingPack = {
  ...manor1920s,
  id: 'yard1928',
  title: 'Scotland Yard, 1928',
  victims: [
    {
      id: 'craddock',
      name: 'Chief Inspector Charles Craddock',
      shortName: 'the Chief Inspector',
      title: 'Chief Inspector, Criminal Investigation Department',
      pronouns: 'he',
      firstName: 'Charles',
      lastName: 'Craddock',
      respectful: 'the Chief Inspector',
      parental: 'Father',
      character: 'craddock',
      // (The note at the foot of the case sheet is his on every other night. Tonight there is none: the foot of the sheet is bare, and his absence felt.)
      chief: null,
      occasions: ['night', 'hanging', 'inspection', 'inquiry', 'dinner'],
    },
    {
      id: 'hollis',
      name: 'Superintendent Edward Hollis',
      shortName: 'the Superintendent',
      title: 'Superintendent, Criminal Investigation Department',
      pronouns: 'he',
      firstName: 'Edward',
      lastName: 'Hollis',
      respectful: 'the Superintendent',
      parental: 'Father',
      character: 'superintendent',
      // He wrote the division's reports, and could end a career with one; nobody's hand of his to refuse.
      motives: ['hostile', 'exposed', 'rival', 'dismissed', 'indebted', 'jilted', 'beneficiary'],
      occasions: ['night', 'hanging', 'inspection', 'inquiry', 'dinner'],
    },
    {
      id: 'ellison',
      name: 'Dr. Edmund Ellison',
      shortName: 'Dr. Ellison',
      title: 'police surgeon to the division',
      pronouns: 'he',
      firstName: 'Edmund',
      lastName: 'Ellison',
      respectful: 'the doctor',
      parental: 'Father',
      character: 'ellison',
      // The surgeon signed what the division needed signed, and knew what it had not wanted known.
      motives: ['hostile', 'exposed', 'indebted', 'jilted', 'beneficiary', 'rival'],
      occasions: ['night', 'hanging', 'inspection', 'inquiry', 'dinner'],
    },
    {
      id: 'finn',
      name: 'Harry Finn',
      shortName: 'Finn',
      title: 'an informer, held in the cells overnight',
      pronouns: 'he',
      firstName: 'Harry',
      lastName: 'Finn',
      respectful: 'Finn',
      parental: 'Father',
      character: 'informer',
      // A nark knows who paid him and who he sold; he had nothing to leave and nobody to dismiss.
      motives: ['hostile', 'exposed', 'indebted', 'jilted'],
      occasions: ['night', 'hanging', 'inquiry'],
    },
  ],
  place: {
    name: 'the Yard',
    here: 'this building',
    people: 'the division',
    plan: 'the plan of the building',
    gathering:
      'Rain and fog in Whitehall, the doors locked and a constable on each, and the whole division in the CID room, each with something to say before the questioning begins.',
    weather: 'the fog',
    one: 'colleague',
    ones: 'colleagues',
    passage: 'the old tunnel',
    placeName: 'New Scotland Yard',
    placeShort: 'the Yard',
    at: 'at',
  },
  weather: 'smog',
  ambience: 'smog',
  // A Victorian office building: corridors and rooms off them.
  mapStyles: ['gallery', 'ell', 'cross'],
  windowLabel: 'between six and seven o’clock, as the fog came down over the river',
  windowClock: 'Between 6 and 7 p.m. this evening',
  suspectsLine: 'The {n} people kept in the building',
  chiefNote: 'Nobody leaves this building before midnight: I have put a man on every door. You’ve got till then to find out who did it.',
  windowFrom: 'six o’clock',
  // (Sergeant Pike is at the table, so he cannot be sent to search; and the Yard does not wire itself.)
  lifelineKinds: ['coffee', 'telegram', 'note', 'expert'],
  lifelineWords: {
    telegram: {
      name: 'a chit for the Registry',
      does: 'Send down to Records for the file on one guest: how they truly stood with the victim.',
      came: 'sent up from Records',
      about: 'the Registry’s file on {name}',
      heading: 'The file from Records',
      logged: 'Records sends up the file on {name}.',
      noted: 'Records sent up the file on {name}: it is with your evidence.',
    },
  },

  rooms: [
    {
      id: 'office',
      name: 'the Chief Inspector’s office',
      where: 'in the Chief Inspector’s office',
      searchFlavor: [
        'A desk under a green-shaded lamp, the fog pressed against the window, and a tray of files marked for the morning.',
        'The gas fire popping, a photograph of the division in 1919, and the safe standing open on nothing.',
      ],
    },
    {
      id: 'cid',
      name: 'the CID room',
      where: 'in the CID room',
      searchFlavor: [
        'Desks in rows, telephones that cannot get through, and the duty book open at tonight with nothing written in it.',
        'Overcoats on the hooks, a kettle on the ring, and the wall map of the Metropolitan District with pins in it.',
      ],
    },
    {
      id: 'charge',
      name: 'the Charge Room',
      where: 'in the Charge Room',
      searchFlavor: [
        'The charge desk, the book chained to it, a bench for the accused, and the smell of wet serge.',
        'The street door bolted and barred, and a constable’s cape dripping on the hook beside it.',
      ],
    },
    {
      id: 'cells',
      name: 'the Cells',
      where: 'down in the Cells',
      searchFlavor: [
        'Whitewash, a row of iron doors, and the rain audible through the grating.',
        'One cell occupied until tonight, its blanket folded, its slop pail empty.',
      ],
    },
    {
      id: 'museum',
      name: 'the Crime Museum',
      where: 'in the Crime Museum',
      searchFlavor: [
        'Glass cases of the worst London has done: ropes, razors, a forger’s plates, and the death masks along the top shelf.',
        'Every weapon in the room has a label and a date. One case is unlocked, and its label faces the wall.',
      ],
    },
    {
      id: 'surgeon',
      name: 'the Surgeon’s Room',
      where: 'in the Surgeon’s Room',
      searchFlavor: [
        'A marble slab, a cabinet of bottles behind glass, and a cold that is not only the weather.',
        'Rubber gloves drying on the tap, the doctor’s bag, and a report half typed in the machine.',
      ],
    },
    {
      id: 'canteen',
      name: 'the Canteen',
      searchFlavor: [
        'Long tables, thick cups, an urn that has gone off the boil, and tonight’s menu chalked up and crossed through.',
        'A dartboard, a wireless, and a cake with a knife in it that nobody has cut.',
      ],
    },
    {
      id: 'yard',
      name: 'the Back Yard',
      where: 'in the Back Yard',
      kind: 'outdoor',
      searchFlavor: [
        'Rain on the cobbles, the Squad car under its tarpaulin, and the blue lamp over the gate haloed in the fog.',
        'The gate chained, a constable under the lamp stamping his feet, and the fog swallowing the street beyond.',
      ],
    },
  ],
  sceneRooms: ['office', 'cid', 'charge', 'cells', 'museum', 'surgeon', 'canteen', 'yard'],
  valuableRooms: ['museum', 'office', 'surgeon'],
  docRooms: ['office', 'cid', 'charge'],

  means: [
    { id: 'stillroom', label: 'has the run of the surgeon’s cabinet' },
    { id: 'firearms', label: 'can draw a revolver from the armoury' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the canteen' },
    { id: 'motor', label: 'drives the Flying Squad car' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a bottle from the surgeon’s cabinet, its label soaked off',
      methodLine: 'poisoned by a hand with the run of the surgeon’s cabinet',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['office', 'cid', 'charge', 'cells', 'museum', 'surgeon', 'canteen'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'a Webley from the armoury, one round fired, signed out to nobody',
      methodLine: 'shot by somebody who can draw a revolver from the armoury',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'a truncheon from the rack in the Charge Room, wiped and hung back the wrong way round',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Truncheon',
      rooms: ['office', 'cid', 'charge', 'cells', 'museum', 'surgeon', 'canteen'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a rope from a case in the Crime Museum, the old knot still in it',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Museum Rope',
      rooms: ['office', 'cid', 'charge', 'cells', 'museum', 'surgeon', 'canteen'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a carving knife from the canteen, rinsed and put back wet',
      methodLine: 'stabbed by someone with the run of the canteen',
      titled: 'The Knife',
    },
    {
      id: 'stair',
      means: 'strength',
      weaponName: 'the stone stair down to the Cells, and the flags at the foot of it',
      methodLine: 'sent down the cell stair by someone with the strength for it',
      titled: 'The Cell Stair',
      rooms: ['cells', 'charge'],
    },
    {
      id: 'cobbles',
      means: 'strength',
      weaponName: 'the cobbles of the yard, the iron boot-scraper by the door, and the rain washing both',
      methodLine: 'knocked down in the yard by someone with the strength for it',
      titled: 'The Cobbles',
      rooms: ['yard'],
    },
    {
      id: 'squadcar',
      means: 'motor',
      weaponName: 'the Flying Squad car, its bumper bloodied, and the cobbles too wet to hold a track',
      methodLine: 'run down in the yard by someone who drives the Squad car',
      titled: 'The Squad Car',
      rooms: ['yard'],
    },
  ],

  characters: [
    as('ellison', { title: 'the police surgeon', blurb: 'Signs the division’s certificates, and has signed one or two he would rather not discuss.' }),
    as('barrow', { title: 'a solicitor, at the Yard for his client', blurb: 'Came to see a client out of the cells and has been kept in by the Assistant Commissioner’s order, to his considerable annoyance.' }),
    as('medium', { title: 'brought in under the Vagrancy Act', blurb: 'Charged with fortune-telling in Bayswater, and has told three constables theirs while waiting.' }),
    as('colonel', { title: 'come about a stolen medal', blurb: 'Reported the theft of his D.S.O. at four, and has been explaining its importance to the division since.' }),
    as('painter', { title: 'the police artist', blurb: 'Draws the faces the witnesses describe, and has drawn most of the division for the canteen wall.' }),
    as('vivienne', { title: 'come to report a theft of jewels', blurb: 'Lost a diamond clip at the Savoy, she says, and expects the Yard to find it before her husband does.' }),
    {
      id: 'pike',
      name: 'Sergeant Alfred Pike',
      shortName: 'Sergeant Pike',
      title: 'a sergeant of the division',
      portrait: '👮',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.6, perfume: 0.02, spectacles: 0.3, gloves: 0.5 },
      means: ['strength', 'motor'],
      manners: { cockney: 0.9, deferential: 0.7, hearty: 0.3 },
      motives: { dismissed: 0.8, hostile: 0.5, exposed: 0.5, indebted: 0.4 },
      voice: PIKE_VOICE,
      blurb: 'Twelve years in the division, knows every corridor of it, and has shown more than one new detective the ropes.',
    },
    {
      id: 'craddock',
      name: 'Chief Inspector Charles Craddock',
      shortName: 'the Chief Inspector',
      title: 'Chief Inspector, CID',
      portrait: '🕵️',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.8, perfume: 0.05, spectacles: 0.5, gloves: 0.4 },
      means: ['firearms', 'strength'],
      manners: { official: 0.9, blunt: 0.7, prickly: 0.4 },
      motives: { hostile: 0.8, exposed: 0.7, rival: 0.6, dismissed: 0.5, indebted: 0.3 },
      voice: { pitch: 118, wave: 'square', lilt: 1.5, clip: 0.11, ring: 0.8 },
      blurb: 'Runs the division from a desk he hates, and has never forgiven a case he could not close.',
    },
    {
      id: 'superintendent',
      name: 'Superintendent Edward Hollis',
      shortName: 'the Superintendent',
      title: 'Superintendent, CID',
      portrait: '🎖️',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.5, perfume: 0.1, spectacles: 0.7, gloves: 0.6 },
      means: ['firearms', 'motor'],
      manners: { official: 0.9, boastful: 0.6, gracious: 0.4 },
      motives: { rival: 0.9, exposed: 0.7, hostile: 0.6, dismissed: 0.4, indebted: 0.3 },
      voice: { pitch: 136, wave: 'sawtooth', lilt: 2.5, clip: 0.09, ring: 0.7 },
      blurb: 'Writes the reports that go upstairs, and decides whose name is in them.',
    },
    {
      id: 'lowther',
      name: 'Detective Sergeant Frank Lowther',
      shortName: 'Sergeant Lowther',
      title: 'a detective sergeant',
      portrait: '🔍',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.8, perfume: 0.2, spectacles: 0.2, gloves: 0.5 },
      means: ['firearms', 'motor', 'strength'],
      manners: { cheeky: 0.8, official: 0.5, boastful: 0.5 },
      motives: { rival: 0.9, dismissed: 0.7, exposed: 0.6, indebted: 0.5, hostile: 0.4 },
      voice: { pitch: 160, wave: 'square', lilt: 3.5, clip: 0.07, ring: 0.5 },
      blurb: 'Pike’s rival for every promotion going, and ahead on points, by his own count.',
    },
    {
      id: 'wpc',
      name: 'Woman Police Constable Grace Tennant',
      shortName: 'WPC Tennant',
      title: 'a woman police constable',
      portrait: '👒',
      pronouns: 'she',
      leanings: { cane: 0.05, smoker: 0.2, perfume: 0.3, spectacles: 0.3, gloves: 0.8 },
      means: ['stillroom', 'motor'],
      manners: { official: 0.8, reserved: 0.6, blunt: 0.4 },
      motives: { dismissed: 0.9, exposed: 0.6, jilted: 0.5, hostile: 0.5, indebted: 0.3 },
      voice: { pitch: 214, wave: 'triangle', lilt: 2, clip: 0.08, ring: 0.4 },
      blurb: 'One of the first of her kind at the Yard, takes the statements of women and children, and has heard every opinion of it.',
    },
    {
      id: 'chargesergeant',
      name: 'Sergeant Albert Dodd',
      shortName: 'Sergeant Dodd',
      title: 'the charge sergeant',
      portrait: '📖',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.7, perfume: 0.02, spectacles: 0.7, gloves: 0.4 },
      means: ['strength', 'kitchen'],
      manners: { official: 0.8, hearty: 0.6, cockney: 0.5 },
      motives: { dismissed: 0.8, indebted: 0.6, exposed: 0.6, hostile: 0.4 },
      voice: { pitch: 130, wave: 'triangle', lilt: 2, clip: 0.1, ring: 0.7 },
      blurb: 'Keeps the charge book and the cell keys, and has booked in half the villains in London by name.',
    },
    {
      id: 'fingerprint',
      name: 'Mr. Cyril Pettit',
      shortName: 'Mr. Pettit',
      title: 'of the Fingerprint Bureau',
      portrait: '🔬',
      pronouns: 'he',
      leanings: { cane: 0.2, smoker: 0.3, perfume: 0.1, spectacles: 0.95, gloves: 0.7 },
      means: ['stillroom'],
      manners: { donnish: 0.8, reserved: 0.6, official: 0.5 },
      motives: { exposed: 0.9, dismissed: 0.6, rival: 0.6, hostile: 0.4, indebted: 0.3 },
      voice: { pitch: 178, wave: 'sine', lilt: 2, clip: 0.09, ring: 0.3 },
      blurb: 'Has matched four hundred prints and hanged eleven men by them, and keeps the count in a notebook.',
    },
    {
      id: 'records',
      name: 'Miss Edith Pruett',
      shortName: 'Miss Pruett',
      title: 'of the Criminal Record Office',
      portrait: '🗂️',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.2, perfume: 0.3, spectacles: 0.9, gloves: 0.5 },
      means: ['stillroom', 'kitchen'],
      manners: { official: 0.8, prickly: 0.6, reserved: 0.4 },
      motives: { dismissed: 0.8, exposed: 0.7, jilted: 0.5, hostile: 0.5, indebted: 0.3 },
      voice: { pitch: 226, wave: 'square', lilt: 2, clip: 0.08, ring: 0.4 },
      blurb: 'Keeps the Registry, can find any file in London in four minutes, and knows which ones are missing.',
    },
    {
      id: 'informer',
      name: 'Harry Finn',
      shortName: 'Finn',
      title: 'an informer, held overnight',
      portrait: '🐀',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.9, perfume: 0.05, spectacles: 0.1, gloves: 0.2 },
      means: ['strength'],
      manners: { cockney: 1, cheeky: 0.6, rambling: 0.4 },
      motives: { hostile: 0.9, exposed: 0.7, indebted: 0.6, dismissed: 0.3 },
      voice: { pitch: 186, wave: 'sawtooth', lilt: 4.5, clip: 0.05, ring: 0.4 },
      blurb: 'Sells what he hears in the Seven Dials to whichever sergeant pays, and was in the cells tonight for his own protection.',
    },
    {
      id: 'charwoman',
      name: 'Mrs. Lil Hobbs',
      shortName: 'Mrs. Hobbs',
      title: 'the charwoman',
      portrait: '🧹',
      pronouns: 'she',
      station: 'servant',
      leanings: { cane: 0.4, smoker: 0.5, perfume: 0.05, spectacles: 0.6, gloves: 0.3 },
      means: ['kitchen'],
      manners: { cockney: 0.9, gossipy: 0.7, blunt: 0.4 },
      motives: { dismissed: 0.8, hostile: 0.6, exposed: 0.6, indebted: 0.5 },
      voice: { pitch: 206, wave: 'triangle', lilt: 3, clip: 0.09, ring: 0.5 },
      blurb: 'Does the offices after six with a bucket and a key to every one of them, and reads what is left on the desks.',
    },
    {
      id: 'reporter',
      name: 'Mr. Dennis Quayle',
      shortName: 'Mr. Quayle',
      title: 'crime reporter, the Daily Sketch',
      portrait: '📰',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.9, perfume: 0.2, spectacles: 0.3, gloves: 0.3 },
      means: ['motor'],
      manners: { cheeky: 0.8, gossipy: 0.7, boastful: 0.5 },
      motives: { exposed: 0.9, hostile: 0.6, rival: 0.5, indebted: 0.5 },
      voice: { pitch: 168, wave: 'square', lilt: 4, clip: 0.06, ring: 0.5 },
      blurb: 'Came for a story about the fog and has stayed for a better one, with a pencil already out.',
    },
    {
      id: 'driver',
      name: 'Bert Nash',
      shortName: 'Nash',
      title: 'driver, the Flying Squad',
      portrait: '🚗',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.8, perfume: 0.02, spectacles: 0.2, gloves: 0.9 },
      means: ['motor', 'strength'],
      manners: { cockney: 0.8, blunt: 0.6, hearty: 0.3 },
      motives: { dismissed: 0.8, hostile: 0.6, indebted: 0.6, exposed: 0.4 },
      voice: { pitch: 124, wave: 'square', lilt: 1.5, clip: 0.1, ring: 0.8 },
      blurb: 'Drives the Squad’s Lea-Francis faster than anybody in London, and has driven it tonight through fog you could not see the bonnet in.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...YARD_SILHOUETTES,
  },

  flavorItems: [
    'a Police Gazette, a fortnight old, folded at the wanted men',
    'a tin of boot polish and a brush, the brush worn to the wood',
    'a railway timetable with the night trains to Dover marked',
    'a mug of tea with the skin on it',
    'a charge sheet, filled in and never signed',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a door in the cellar wall, and a cold way along the old tunnel under Whitehall',
  bribeItem: 'an envelope of notes from the informants’ fund, with {name}’s name on it',
  occasions: [
    {
      id: 'night',
      weight: 3,
      titles: ['Night Duty', 'The Night Shift {At} {Place}', 'A Quiet Night at the Yard'],
      sheet: 'The night shift had come on, and the building was quiet.',
      report: '{Victim} was in the building as the night shift came on. {He} was killed during the evening, and the Assistant Commissioner had the doors locked at once.',
      event: 'quarrel',
      intro: [
        'The night shift had come on at six, the fog had come down with it, and the building had settled to a long quiet evening of paperwork when, at seven o’clock, {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The Assistant Commissioner had the doors locked before the body was cold, with a constable on each. Whoever did it is a colleague, or a guest of the division, and is still in the building.',
        'Scotland Yard, with its doors locked on its own people: the one night in a hundred years the police could not send for the police. At seven o’clock {victim} was found in {scene}, the deed done {window}. There is a constable on every door, and the murderer is on the inside of all of them.',
      ],
    },
    {
      id: 'hanging',
      weight: 2,
      titles: ['The Night Before', 'A Confession Wanted', 'Eight O’Clock at Pentonville'],
      sheet: 'A man was to hang at Pentonville in the morning, and a confession was still wanted.',
      report: 'A man was to hang at Pentonville at eight in the morning, and {Victim} had said there was something still to be got out of the case before then. {He} was killed during the evening, and the doors were locked at once.',
      event: 'telephone',
      motives: { exposed: 3, hostile: 2 },
      intro: [
        'A man was to hang at Pentonville at eight in the morning, and {victim} had let it be known that the case was not as closed as the file said. The fog came down at six, and at seven o’clock {he} was found in {scene}, quite dead. It had been done {window}. The doors are locked, and whatever {he} meant to say before eight, somebody has made sure {he} will not.',
      ],
    },
    {
      id: 'inspection',
      weight: 2,
      titles: ['The Commissioner’s Inspection', 'Best Behaviour', 'Brass at the Yard'],
      sheet: 'The Commissioner was inspecting the division that evening.',
      report: 'The Commissioner was inspecting the division that evening, and every desk was tidy for once. {Victim} was killed during the inspection, and the doors were locked at once.',
      event: 'walkout',
      motives: { dismissed: 2.5, exposed: 2, rival: 1.5 },
      intro: [
        'The Commissioner had chosen tonight to inspect the division, and the division had chosen to be found at its desks for once, in the fog, with the rain at the windows. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The doors were locked on the Commissioner’s order, and he is still in the building with everyone he came to see.',
      ],
    },
    {
      id: 'inquiry',
      weight: 2,
      titles: ['The Inquiry', 'A Matter of Conduct', 'The File on the Division'],
      sheet: 'An inquiry into the division’s conduct was to open in the morning.',
      report: 'An inquiry into the conduct of the division was to open in the morning, and {Victim} was to give evidence to it. {He} was killed during the evening, and the doors were locked at once.',
      event: 'slam',
      motives: { exposed: 3, hostile: 2, dismissed: 1.5 },
      intro: [
        'An inquiry was to open in the morning into what the division had been doing with its informants’ fund, and {victim} had been asked to give evidence to it. The fog came down at six, and at seven o’clock {he} was found in {scene}, quite dead. It had been done {window}. The doors are locked, and whatever {he} meant to tell the inquiry, {he} will not now.',
      ],
    },
    {
      id: 'dinner',
      weight: 2,
      titles: ['The Division Dinner', 'Absent Friends', 'The Loyal Toast'],
      sheet: 'The division’s annual dinner was being held in the canteen.',
      report: 'The division’s annual dinner was laid in the canteen, and everybody was in the building for it. {Victim} was killed during the evening, and the doors were locked at once.',
      event: 'quarrel',
      motives: { hostile: 1.5, indebted: 1.5, rival: 1.5 },
      intro: [
        'The division dines together once a year, in the canteen, with speeches, and this year nobody left early, because at seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The doors were locked before the pudding, and the loyal toast was never drunk.',
      ],
    },
  ],
  scenarioIntro: [
    'The fog came down over the river at six, and the rain with it. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The Assistant Commissioner had the doors locked at once, with a constable on each, and nobody has left the Yard.',
  ],
}
