// The Highland Express, 1929: a night train running north through the snow,
// due into Inverness at midnight, and a financier dead in his compartment. Two carriages, a corridor apiece.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const train1926: SettingPack = {
  ...manor1920s,
  id: 'train1926',
  title: 'The Highland Express, 1929',
  victims: [
    {
      id: 'marchbanks',
      name: 'Sir Julius Marchbanks',
      shortName: 'Sir Julius',
      title: 'financier, of Marchbanks & Lowe',
      pronouns: 'he',
      firstName: 'Julius',
      lastName: 'Marchbanks',
      respectful: 'Sir Julius',
      parental: 'Father',
      children: ['financierdaughter', 'financierson'],
    },
    {
      id: 'trent',
      name: 'Mr. Hugo Trent',
      shortName: 'Mr. Trent',
      title: 'Sir Julius’s partner, of Marchbanks & Lowe',
      pronouns: 'he',
      firstName: 'Hugo',
      lastName: 'Trent',
      respectful: 'Mr. Trent',
      parental: 'Father',
      character: 'trent',
      // A partner in the firm: cause enough in the City, but nobody's hand to refuse.
      motives: ['hostile', 'indebted', 'jilted', 'disinherited', 'beneficiary', 'exposed', 'rival'],
      occasions: ['shooting', 'business'],
    },
    {
      id: 'tolley',
      name: 'Mr. Frank Tolley',
      shortName: 'the guard',
      title: 'guard of the Highland Express',
      pronouns: 'he',
      firstName: 'Frank',
      lastName: 'Tolley',
      respectful: 'the guard',
      parental: 'Father',
      character: 'guard',
      // Thirty years on the line, and he saw what went on in it: nothing to leave, nobody to dismiss.
      motives: ['hostile', 'indebted', 'exposed', 'jilted'],
      occasions: ['shooting', 'service'],
    },
  ],
  place: {
    name: 'the train',
    here: 'this train',
    people: 'the company',
    plan: 'the plan of the train',
    gathering:
      'Snow against the windows, the engine labouring north through the dark, and every passenger in the dining car, each with something to say before the questioning begins.',
    weather: 'the storm',
    one: 'passenger',
    ones: 'passengers',
    passage: 'the corridor',
    placeName: 'the Highland Express',
    placeShort: 'Highland Express',
    at: 'on',
  },
  // Snow on the line: flakes past the glass and no thunder — a blizzard beyond it, and the engine's breath as she runs.
  weather: 'blizzard',
  ambience: 'train',
  mapStyles: ['train'],
  windowLabel: 'between four and five in the afternoon, somewhere north of Perth',
  windowClock: 'Between 4 and 5 p.m. this afternoon',
  suspectsLine: 'The {n} passengers on the train',
  chiefNote: 'She gets into Inverness at midnight, and every one of them steps off the train. You’ve got till then to find out who did it.',
  windowFrom: 'four o’clock',

  rooms: [
    {
      id: 'c1',
      name: 'compartment No. 1',
      searchFlavor: ['A rug, a rack, a novel face down. The blind is up.', 'The seat is still warm from somebody.'],
    },
    {
      id: 'c2',
      name: 'compartment No. 2',
      searchFlavor: ['Two suitcases, one of them locked. The lamp flickers.', 'A window let down an inch, and snow on the sill.'],
    },
    {
      id: 'c3',
      name: 'compartment No. 3',
      searchFlavor: ['A hatbox, a fur, and a smell of violets.', 'The berth is made up. Nobody has slept in it.'],
    },
    {
      id: 'engine',
      name: 'the footplate',
      where: 'on the footplate',
      end: 'front',
      searchFlavor: ['Coal, steam, and the fire roaring white behind the door.', 'The shovel stands in the tender. The pressure gauge trembles at the red line.'],
    },
    {
      id: 'dining',
      name: 'the dining car',
      searchFlavor: ['White cloths, a spilt cruet, and the coffee gone cold in every cup.', 'The tables are laid for a dinner nobody finished.'],
    },
    {
      id: 'observation',
      name: 'the observation car',
      searchFlavor: ['Armchairs, ashtrays, and the black window at the end.', 'The platform door rattles in its frame.'],
    },
    {
      id: 'van',
      name: 'the guard’s van',
      end: 'back',
      searchFlavor: ['Mailbags, a bicycle, and a lantern turned low.', 'Labels, chalk, and a stove that has gone out.'],
    },
    {
      id: 'pantry',
      name: 'the attendant’s pantry',
      searchFlavor: ['Trays, glasses, and a kettle still ticking as it cools.', 'The tea-caddy is locked. The biscuits are not.'],
    },
  ],
  sceneRooms: ['c1', 'c2', 'c3', 'engine', 'dining', 'observation', 'van', 'pantry'],
  valuableRooms: ['c1', 'c2', 'c3', 'van'],
  docRooms: ['c1', 'c2', 'observation', 'van'],

  means: [
    { id: 'stillroom', label: 'has the run of the pantry and its medicine chest' },
    { id: 'firearms', label: 'carries a revolver' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the dining-car galley' },
    { id: 'motor', label: 'knows the working of the platform door' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a coffee cup, rinsed, and a twist of paper that was not sugar',
      methodLine: 'poisoned by somebody with the run of the pantry',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['c1', 'c2', 'c3', 'dining', 'observation', 'pantry'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'a service revolver, one round spent, pushed under a seat',
      methodLine: 'shot by somebody who carries a revolver',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'the fireman’s shovel from the footplate, wiped ill',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Shovel',
      rooms: ['c1', 'c2', 'c3', 'engine', 'dining', 'observation', 'van'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a window strap, cut from its frame and knotted',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Window Strap',
      rooms: ['c1', 'c2', 'c3', 'observation', 'van'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a carving knife from the galley, rinsed and put back wet',
      methodLine: 'stabbed by someone with the run of the galley',
      titled: 'The Knife',
    },
    {
      id: 'fall',
      means: 'motor',
      weaponName: 'the platform gate at the end of the car, swinging open, and a glove on the step',
      methodLine: 'thrown from the train by somebody who knew the platform door',
      titled: 'A Fall',
      rooms: ['observation'],
    },
  ],

  characters: [
    as('colonel', { title: 'going north for the shooting' }),
    as('vivienne', { title: 'travelling first class' }),
    as('josephine', { title: 'engaged at Inverness' }),
    as('ellison', { title: 'a doctor, travelling' }),
    as('trent', { title: 'Sir Julius’s partner', blurb: 'The Lowe of Marchbanks & Lowe, and lately the smaller name on the door.' }),
    as('barrow', { title: 'Sir Julius’s solicitor' }),
    as('dowager', { title: 'travelling with her maid, who is in third' }),
    as('explorer', { title: 'bound for the Cairngorms' }),
    as('hunter', { title: 'going north for the stags' }),
    as('medium', { title: 'engaged for a house party at Braemar' }),
    as('heiress', { title: 'seeing Scotland' }),
    as('painter', { title: 'commissioned in the Highlands' }),
    as('daughter', { id: 'financierdaughter', name: 'Miss Violet Marchbanks', shortName: 'Miss Marchbanks', title: 'Sir Julius’s daughter' }),
    as('son', { id: 'financierson', name: 'Mr. Julian Marchbanks', shortName: 'Mr. Marchbanks', title: 'Sir Julius’s son' }),
    {
      id: 'attendant',
      name: 'Mr. Albert Dunn',
      shortName: 'the attendant',
      title: 'the sleeping-car attendant',
      portrait: '🛎️',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.5, perfume: 0.1, spectacles: 0.4, gloves: 0.9 },
      means: ['stillroom', 'kitchen'],
      manners: { deferential: 1, reserved: 0.5, gossipy: 0.3 },
      motives: { dismissed: 0.9, indebted: 0.6, exposed: 0.5, hostile: 0.4 },
      voice: { pitch: 165, wave: 'triangle', lilt: 1.5, clip: 0.09, ring: 0.6 },
      blurb: 'Has made up a thousand berths and remembered every face that slept in them.',
    },
    {
      id: 'guard',
      name: 'Mr. Frank Tolley',
      shortName: 'the guard',
      title: 'the guard',
      portrait: '🚩',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.2, smoker: 0.8, perfume: 0.02, spectacles: 0.5, gloves: 0.5 },
      means: ['strength', 'motor'],
      manners: { blunt: 0.8, deferential: 0.6, rambling: 0.3 },
      motives: { dismissed: 0.8, hostile: 0.6, indebted: 0.5, exposed: 0.4 },
      voice: { pitch: 130, wave: 'triangle', lilt: 1, clip: 0.12, ring: 0.8 },
      blurb: 'Thirty years on the line, and never lost a passenger until tonight.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    financierdaughter: manor1920s.silhouettes!.daughter,
    financierson: manor1920s.silhouettes!.son,
  },

  flavorItems: [
    'a timetable with the connections underlined',
    'a Bradshaw, well thumbed',
    'a tartan rug, folded',
    'a menu card from the dining car, with a sketch on the back',
    'a ticket stub for a station nobody has heard of',
  ],
  passageItem: 'the connecting door between compartments, its bolt drawn back on the far side',
  bribeItem: 'an envelope of banknotes, with {name}’s name on it, pushed into a luggage rack',
  occasions: [
    {
      id: 'shooting',
      weight: 3,
      titles: ['The Night Train', 'Snow on the Line', 'North through the Snow'],
      sheet: 'The train was carrying a shooting party north.',
      report: 'The train was carrying a shooting party north. {Victim} was killed on the train, somewhere north of Perth.',
      event: 'quarrel',
      intro: [
        'The snow came on beyond Blair Atholl, and the Highland Express ran north into it with nothing on either side but white hillside. By four the light was going. At half past five {victim} was found in {scene}, quite dead, and it was certainly no accident. Nobody has left the train. There is, after all, nowhere to go before Inverness.',
        'Two carriages, the snow streaming past the glass, and a shooting party bound for the moors. {victim} had a gun waiting for {him} at the lodge; {he} will not be needing it. {He} was found in {scene}, the deed done {window}. The killer is on the train, and the train stops for nobody before Inverness.',
      ],
    },
    {
      id: 'service',
      weight: 2,
      titles: ['The Night Service', 'Last Train North', 'Snow at Dalwhinnie'],
      sheet: 'The train was running the night service north, full to the doors.',
      report: '{Victim} was aboard the night service north. {He} was killed on the train, somewhere north of Perth.',
      event: 'quarrel',
      intro: [
        'A full train, the night service north, and the snow coming on beyond Blair Atholl. By four the light was going; at half past five {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the train, and the train stops for nobody before Inverness.',
      ],
    },
    {
      id: 'business',
      weight: 2,
      titles: ['The {LastName} Partnership', 'Marchbanks & Lowe'],
      sheet: 'The train was carrying the partners of Marchbanks & Lowe to a meeting in Edinburgh.',
      report: '{Victim} was taking {his} partners to a meeting in Edinburgh to settle the affairs of the firm. {He} was killed before the meeting took place.',
      event: 'telephone',
      motives: { rival: 3, indebted: 2, exposed: 1.5 },
      intro: [
        'The partners, the solicitor, and one or two with money in the firm: {victim} had them all aboard the night train for a meeting in Edinburgh that would settle Marchbanks & Lowe one way or the other. Somebody on board settled it first. At half past five {he} was found in {scene}, quite dead. Meetings of that kind generally end with somebody ruined; this one ended rather sooner.',
      ],
    },
    {
      id: 'will',
      weight: 2,
      titles: ['The {LastName} Inheritance', 'The Unsigned Will'],
      sheet: '{Victim} was travelling north to sign a new will at {his} Scottish house.',
      report: '{Victim} was travelling north to sign a new will. {He} was killed before {he} was able to do so.',
      event: 'slam',
      motives: { disinherited: 3, beneficiary: 3 },
      intro: [
        '{victim} carried a new will in {his} dispatch case, to be signed at Kinloch tomorrow, and everyone with an interest in the old one had contrived to be on the same train. Somewhere north of Perth, in the snow, it was settled another way. At half past five {he} was found in {scene}, quite dead, and the will still unsigned. Tomorrow, it seems, was a day too late.',
      ],
    },
    {
      id: 'engagement',
      weight: 2,
      titles: ['The {LastName} Engagement', 'An Engagement at Inverness'],
      sheet: 'The train was carrying a party north for an engagement at Inverness.',
      report: '{Victim} was travelling to an engagement at Inverness, to which {he} had refused {his} blessing. {He} was killed before the announcement was made.',
      event: 'walkout',
      motives: { forbidden: 3, jilted: 2 },
      intro: [
        'An engagement was to be announced at Inverness, and the family and the friends had all taken the same train north. But that afternoon {victim} had let it be known that {he} would not give {his} blessing. Then the snow came down, and the train ran on into it. At half past five {he} was found in {scene}, quite dead.',
      ],
    },
  ],
  scenarioIntro: [
    'The snow came on at three, and the Highland Express has been running north into it ever since, with nothing before Inverness. At half past five {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the train.',
  ],
}
