// Wonderland, 1865: tea-time that never ends, the court of hearts sitting
// on the garden, and somebody dead among the creatures who were summoned
// there. Dry and exact, with Carroll's nonsense underneath and never played
// for a laugh. Everything not its own (the roles, the papers, the way the
// people talk) it shares with the manor.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'
import { WONDERLAND_SILHOUETTES } from './silhouettes'
import { WONDERLAND_GLYPHS } from './items'

const c = (d: CharacterDef): CharacterDef => d

export const wonderland1865: SettingPack = {
  ...manor1920s,
  id: 'wonderland1865',
  title: 'Wonderland, 1865',
  victims: [
    {
      id: 'queen',
      name: 'Her Majesty the Queen of Hearts',
      shortName: 'the Queen',
      title: 'Queen of Hearts',
      pronouns: 'she',
      firstName: 'the Queen',
      lastName: 'of Hearts',
      respectful: 'Her Majesty',
      parental: 'Mother',
      character: 'queen',
      children: [],
      motives: ['hostile', 'exposed', 'dismissed', 'jilted', 'beneficiary', 'rival'],
      occasions: ['croquet', 'trial', 'teaparty'],
    },
    {
      id: 'duchess',
      name: 'the Duchess',
      shortName: 'the Duchess',
      title: 'the Duchess, of the house with the pepper',
      pronouns: 'she',
      firstName: 'the Duchess',
      lastName: 'the Duchess',
      respectful: 'Her Grace',
      parental: 'Mother',
      character: 'duchess',
      motives: ['hostile', 'indebted', 'exposed', 'dismissed', 'jilted'],
      occasions: ['croquet', 'teaparty'],
    },
    {
      id: 'humpty',
      name: 'Humpty Dumpty',
      shortName: 'Humpty Dumpty',
      title: 'Humpty Dumpty, of the wall',
      pronouns: 'he',
      firstName: 'Humpty',
      lastName: 'Dumpty',
      respectful: 'Mr. Dumpty',
      parental: 'Father',
      character: 'humpty',
      motives: ['hostile', 'indebted', 'exposed', 'jilted', 'rival'],
      occasions: ['teaparty', 'trial'],
    },
  ],
  place: {
    name: 'Wonderland',
    here: 'this country',
    people: 'the court',
    plan: 'the map of Wonderland',
    gathering:
      'Everybody summoned to the court of hearts, the jury in its box and the tarts on the table, each with something to say before the questioning begins.',
    weather: 'the dusk',
    one: 'creature',
    ones: 'creatures',
    passage: 'the rabbit-hole',
    placeName: 'Wonderland',
    placeShort: 'Wonderland',
    at: 'in',
  },
  weather: 'calm',
  ambience: 'none',
  mapStyles: ['courtyard', 'wings', 'gallery'],
  windowLabel: 'between six and seven, at tea-time, which in Wonderland is always',
  windowClock: 'Between 6 and 7 p.m. this evening',
  suspectsLine: 'The {n} creatures summoned to the court of hearts',
  chiefNote: 'Nobody leaves Wonderland before midnight, if anybody ever does. You’ve got till then to find out who did it.',
  windowFrom: 'six o’clock',

  rooms: [
    {
      id: 'teaparty',
      name: 'the tea-party table',
      where: 'at the tea-party table',
      searchFlavor: [
        'A table laid for far too many, a great many cups used and not one washed, and every chair pushed back a place.',
        'A teapot with a dormouse-sized dent in the lid, and a watch that has been buttered and does not go.',
      ],
    },
    {
      id: 'kitchen',
      name: 'the Duchess’s kitchen',
      searchFlavor: [
        'Pepper in the air, a cauldron left to stand, and a row of ladles hung in order of size.',
        'Plates broken and swept into a corner, and a stool kicked over in the middle of the floor.',
      ],
    },
    {
      id: 'croquet',
      name: 'the croquet ground',
      where: 'on the croquet ground',
      kind: 'outdoor',
      searchFlavor: [
        'Hoops that are soldiers, bent double and not yet stood up, and the lawn all ridges and furrows.',
        'A hedgehog rolled into the long grass, looking put upon. Nobody has claimed the ball.',
      ],
    },
    {
      id: 'court',
      name: 'the court of hearts',
      searchFlavor: [
        'The jury box, twelve slates and twelve stubby pencils, and a judge’s chair with a cushion worn flat.',
        'A dish of tarts under a cloth, a trumpet on its side, and a list of evidence that has been crossed through.',
      ],
    },
    {
      id: 'rabbithouse',
      name: 'the White Rabbit’s house',
      searchFlavor: [
        'A neat little parlour with a fan and a pair of white gloves laid out on a table, and a clock ticking fast.',
        'A great many bottles on a shelf, none of them labelled in a hand one can read, and a hearth swept very clean.',
      ],
    },
    {
      id: 'shore',
      name: 'the shore of the pool of tears',
      where: 'on the shore of the pool of tears',
      kind: 'outdoor',
      searchFlavor: [
        'Salt water to the ankle, a mouse’s boot left on the bank, and the tide going out of nothing at all.',
        'A caucus of feathers drying on a rock, and the dry marks of a great many small feet.',
      ],
    },
    {
      id: 'garden',
      name: 'the garden of live flowers',
      kind: 'outdoor',
      searchFlavor: [
        'Roses being painted a more convenient colour, and a bed of tiger-lilies that has gone quiet on purpose.',
        'A white rose tree with the paint still wet, and a pot of red left at the foot of it.',
      ],
    },
    {
      id: 'wood',
      name: 'the Tulgey wood',
      kind: 'outdoor',
      searchFlavor: [
        'Trees that have lost their names, and a path that was here a moment ago.',
        'A signpost with two arms pointing the same way, and the dusk coming down between the trunks.',
      ],
    },
    {
      id: 'hall',
      name: 'the hall of doors',
      searchFlavor: [
        'Doors all round the room, every one locked, and a glass table with a tiny key that is not on it now.',
        'A curtain hung low, and behind it a door no higher than a hand’s breadth, standing a little open.',
      ],
    },
  ],
  sceneRooms: ['teaparty', 'kitchen', 'croquet', 'court', 'rabbithouse', 'shore', 'garden', 'wood', 'hall'],
  valuableRooms: ['rabbithouse', 'court', 'teaparty'],
  docRooms: ['court', 'rabbithouse', 'hall'],

  means: [
    { id: 'stillroom', label: 'has the run of the Duchess’s pepper and the little bottles' },
    { id: 'court', label: 'has the Queen’s warrant, and the axe that goes with it' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the kitchen and its knives' },
    { id: 'height', label: 'can climb, or fly, to the top of the wall' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a little bottle marked DRINK ME, empty, and a pinch of pepper in the cork',
      methodLine: 'poisoned by a hand with the run of the pepper and the little bottles',
      selfInflicted: true,
      titled: 'The Pepper',
    },
    {
      id: 'mallet',
      means: 'strength',
      weaponName: 'a flamingo used as a croquet mallet, now sulking and not to be questioned',
      methodLine: 'struck down with a croquet mallet by someone with the strength for it',
      titled: 'The Croquet Mallet',
      rooms: ['croquet', 'garden', 'court', 'wood'],
    },
    {
      id: 'fall',
      means: 'height',
      weaponName: 'the top of the wall, a scatter of shell on the grass below, and nobody who saw it',
      methodLine: 'brought down from a height by someone who can climb, or fly, to the top of the wall',
      titled: 'A Great Fall',
      rooms: ['garden', 'wood', 'shore'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a hat ribbon, the price still tucked in the band, pulled tight and then let drop',
      methodLine: 'strangled with a hat ribbon by someone with the strength for it',
      titled: 'The Hat Ribbon',
    },
    {
      id: 'axe',
      means: 'court',
      weaponName: 'the executioner’s axe, wiped and hung back on the wall of the court',
      methodLine: 'struck down with the executioner’s axe by someone with the Queen’s warrant',
      titled: 'Off With Their Head',
      rooms: ['court', 'croquet', 'hall', 'garden'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'the Cook’s carving knife, rinsed and put back on its hook, still wet',
      methodLine: 'stabbed by someone with the run of the kitchen and its knives',
      titled: 'The Carving Knife',
    },
  ],

  characters: [
    c({
      id: 'hatter',
      name: 'the Hatter',
      shortName: 'the Hatter',
      title: 'a hatter, in his own hat',
      portrait: '🎩',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.4, perfume: 0.1, spectacles: 0.3, gloves: 0.2 },
      means: ['stillroom', 'strength', 'kitchen'],
      manners: { dramatic: 0.9, cheeky: 0.8, rambling: 0.7 },
      motives: { indebted: 0.9, exposed: 0.7, hostile: 0.6, dismissed: 0.4, rival: 0.4 },
      voice: { pitch: 172, wave: 'square', lilt: 4.5, clip: 0.06, ring: 0.5 },
      blurb: 'Sells hats at ten and sixpence and has been on the verge of paying for the tea since the party began.',
    }),
    c({
      id: 'hare',
      name: 'the March Hare',
      shortName: 'the March Hare',
      title: 'host of the tea-party',
      portrait: '🐇',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.4, perfume: 0.1, spectacles: 0.2, gloves: 0.3 },
      means: ['strength', 'kitchen', 'height'],
      manners: { hearty: 0.9, rambling: 0.8 },
      motives: { hostile: 0.8, indebted: 0.7, jilted: 0.5, rival: 0.5, exposed: 0.4 },
      voice: { pitch: 190, wave: 'triangle', lilt: 5, clip: 0.05, ring: 0.3 },
      blurb: 'Pours at the head of the table and has never once been seen to take the same seat twice.',
    }),
    c({
      id: 'dormouse',
      name: 'the Dormouse',
      shortName: 'the Dormouse',
      title: 'sitting between the Hatter and the Hare',
      portrait: '🐭',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.1, perfume: 0.2, spectacles: 0.4, gloves: 0.3 },
      means: ['kitchen', 'height'],
      manners: { reserved: 0.9, rambling: 0.7 },
      motives: { hostile: 0.5, dismissed: 0.6, indebted: 0.5, exposed: 0.5 },
      voice: { pitch: 300, wave: 'sine', lilt: 2, clip: 0.05, ring: 0.2 },
      blurb: 'Takes the corner of the tea-table and a good deal of the evening, and answers only when pinched.',
    }),
    c({
      id: 'rabbit',
      name: 'the White Rabbit',
      shortName: 'the White Rabbit',
      title: 'herald and keeper of the court’s time',
      portrait: '🐰',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.05, perfume: 0.3, spectacles: 0.9, gloves: 1 },
      means: ['court', 'stillroom', 'height'],
      manners: { deferential: 1, official: 0.8 },
      motives: { dismissed: 0.9, exposed: 0.7, indebted: 0.5, hostile: 0.4 },
      voice: { pitch: 226, wave: 'triangle', lilt: 3, clip: 0.05, ring: 0.3 },
      blurb: 'Keeps the court’s hours, the Queen’s trumpet and a watch always being consulted, and is late for all three.',
    }),
    c({
      id: 'cat',
      name: 'the Cheshire Cat',
      shortName: 'the Cheshire Cat',
      title: 'to be found wherever the branch is',
      portrait: '🐱',
      pronouns: 'he',
      leanings: { cane: 0.05, smoker: 0.2, perfume: 0.4, spectacles: 0.3, gloves: 0.1 },
      means: ['height', 'strength'],
      manners: { cheeky: 0.9, donnish: 0.8 },
      motives: { rival: 0.6, exposed: 0.6, hostile: 0.6, jilted: 0.4 },
      voice: { pitch: 210, wave: 'sine', lilt: 5.5, clip: 0.07, ring: 0.4 },
      blurb: 'Arrives before the question and leaves, in part, before the answer.',
    }),
    c({
      id: 'duchess',
      name: 'the Duchess',
      shortName: 'the Duchess',
      title: 'of the house with the pepper',
      portrait: '👑',
      pronouns: 'she',
      leanings: { cane: 0.3, smoker: 0.3, perfume: 0.5, spectacles: 0.5, gloves: 0.5 },
      means: ['stillroom', 'kitchen'],
      manners: { prickly: 0.9, gracious: 0.7 },
      motives: { hostile: 0.8, indebted: 0.6, exposed: 0.6, jilted: 0.5, dismissed: 0.4 },
      voice: { pitch: 218, wave: 'sawtooth', lilt: 3, clip: 0.07, ring: 0.5 },
      blurb: 'Keeps a house, a baby and a very large kitchen, and has a moral for every occasion.',
    }),
    c({
      id: 'cook',
      name: 'the Cook',
      shortName: 'the Cook',
      title: 'of the Duchess’s kitchen',
      portrait: '🍲',
      pronouns: 'she',
      station: 'servant',
      leanings: { cane: 0.05, smoker: 0.3, perfume: 0.05, spectacles: 0.2, gloves: 0.1 },
      means: ['kitchen', 'stillroom', 'strength'],
      manners: { blunt: 0.9, prickly: 0.8 },
      motives: { dismissed: 0.9, hostile: 0.8, exposed: 0.5, indebted: 0.4 },
      voice: { pitch: 150, wave: 'sawtooth', lilt: 2.5, clip: 0.08, ring: 0.7 },
      blurb: 'Cooks with pepper, throws what comes to hand, and gives evidence as she would a receipt.',
    }),
    c({
      id: 'caterpillar',
      name: 'the Caterpillar',
      shortName: 'the Caterpillar',
      title: 'seated on a mushroom',
      portrait: '🐛',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 1, perfume: 0.1, spectacles: 0.5, gloves: 0.05 },
      means: ['stillroom', 'height'],
      manners: { donnish: 0.9, blunt: 0.8 },
      motives: { exposed: 0.7, hostile: 0.6, rival: 0.6, indebted: 0.4 },
      voice: { pitch: 124, wave: 'triangle', lilt: 1.5, clip: 0.11, ring: 0.8 },
      blurb: 'Asks who one is before one has said, and sits above the conversation on a mushroom, as one does.',
    }),
    c({
      id: 'queen',
      name: 'Her Majesty the Queen of Hearts',
      shortName: 'the Queen',
      title: 'Queen of Hearts',
      portrait: '♥️',
      pronouns: 'she',
      leanings: { cane: 0.1, smoker: 0.1, perfume: 0.9, spectacles: 0.1, gloves: 0.7 },
      means: ['court', 'strength'],
      manners: { prickly: 0.9, boastful: 0.8 },
      motives: { hostile: 0.9, exposed: 0.6, dismissed: 0.5, rival: 0.5, jilted: 0.4 },
      voice: { pitch: 196, wave: 'sawtooth', lilt: 6, clip: 0.05, ring: 0.6 },
      blurb: 'Holds the warrant, the croquet ground and a firm view on the proper treatment of gardeners.',
    }),
    c({
      id: 'king',
      name: 'the King of Hearts',
      shortName: 'the King',
      title: 'sitting as judge',
      portrait: '🤴',
      pronouns: 'he',
      leanings: { cane: 0.4, smoker: 0.2, perfume: 0.3, spectacles: 0.9, gloves: 0.4 },
      means: ['court', 'kitchen'],
      manners: { deferential: 0.8, rambling: 0.8 },
      motives: { exposed: 0.7, jilted: 0.5, indebted: 0.5, hostile: 0.4, forbidden: 0.3 },
      voice: { pitch: 142, wave: 'triangle', lilt: 2.5, clip: 0.09, ring: 0.7 },
      blurb: 'Tries the cases, reads the verdicts in the wrong order and pardons nearly everybody the Queen has sentenced.',
    }),
    c({
      id: 'knave',
      name: 'the Knave of Hearts',
      shortName: 'the Knave',
      title: 'of the tarts, and lately of the dock',
      portrait: '🃏',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.5, perfume: 0.4, spectacles: 0.1, gloves: 0.5 },
      means: ['court', 'kitchen', 'strength'],
      manners: { cheeky: 0.9, boastful: 0.8 },
      motives: { exposed: 0.8, jilted: 0.7, hostile: 0.6, forbidden: 0.5, indebted: 0.4 },
      voice: { pitch: 176, wave: 'square', lilt: 4, clip: 0.06, ring: 0.5 },
      blurb: 'Stood in the dock for some tarts, and carries himself like a man who has been acquitted of something.',
    }),
    c({
      id: 'turtle',
      name: 'the Mock Turtle',
      shortName: 'the Mock Turtle',
      title: 'once a real one, he says',
      portrait: '🐢',
      pronouns: 'he',
      leanings: { cane: 0.3, smoker: 0.2, perfume: 0.2, spectacles: 0.4, gloves: 0.2 },
      means: ['strength', 'kitchen'],
      manners: { dramatic: 0.9, rambling: 0.8 },
      motives: { hostile: 0.5, indebted: 0.6, jilted: 0.6, dismissed: 0.5, exposed: 0.4 },
      voice: { pitch: 132, wave: 'triangle', lilt: 3, clip: 0.1, ring: 0.8 },
      blurb: 'Sighs, and then tells the story of his schooldays, at length, with the lessons in their order.',
    }),
    c({
      id: 'gryphon',
      name: 'the Gryphon',
      shortName: 'the Gryphon',
      title: 'in attendance on the Queen',
      portrait: '🦅',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.5, perfume: 0.1, spectacles: 0.1, gloves: 0.2 },
      means: ['strength', 'height', 'court'],
      manners: { hearty: 0.9, boastful: 0.8 },
      motives: { hostile: 0.6, dismissed: 0.6, rival: 0.5, indebted: 0.5, jilted: 0.3 },
      voice: { pitch: 148, wave: 'sawtooth', lilt: 3.5, clip: 0.07, ring: 0.6 },
      blurb: 'Escorts the Queen’s visitors to wherever they are going, and says it is all the fancy, whatever it is.',
    }),
    c({
      id: 'humpty',
      name: 'Humpty Dumpty',
      shortName: 'Humpty Dumpty',
      title: 'of the wall',
      portrait: '🥚',
      pronouns: 'he',
      leanings: { cane: 0.1, smoker: 0.2, perfume: 0.2, spectacles: 0.3, gloves: 0.05 },
      means: ['height', 'court', 'stillroom'],
      manners: { donnish: 0.9, boastful: 0.8 },
      motives: { hostile: 0.7, exposed: 0.6, indebted: 0.6, rival: 0.5, jilted: 0.3 },
      voice: { pitch: 164, wave: 'sine', lilt: 3, clip: 0.07, ring: 0.6 },
      blurb: 'Holds that a word means what it is chosen to mean, neither more nor less, and has the wall to say it from.',
    }),
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ...WONDERLAND_SILHOUETTES,
  },
  itemArt: {
    ...manor1920s.itemArt!,
    glyphs: { ...manor1920s.itemArt!.glyphs, ...WONDERLAND_GLYPHS },
  },

  flavorItems: [
    'a pocket watch that tells the day of the month and not the hour',
    'a card painted red on one side, the other still wet',
    'a tiny glass bottle, its label reading only DRINK ME',
    'a fan and a pair of white kid gloves, laid neatly together',
    'a slate with a sum on it that comes out differently each time',
  ],
  bareScene: 'the place where it was done, and nothing it was done with',
  passageItem: 'a rabbit-hole in the skirting, and a long way down',
  bribeItem: 'a plate of tarts, with {name}’s name on the doily',
  keyItem: 'the little golden key, on the glass table',
  ashesItem: 'a corner of burnt paper in the grate, still warm',
  secondBody: '{name}, quite still, and no longer curious',

  occasions: [
    {
      id: 'croquet',
      weight: 3,
      titles: ['The Queen’s Croquet Party', 'Croquet {At} {Place}', 'The Last Hoop'],
      sheet: 'The court was at croquet on the Queen’s ground.',
      report: 'The court was at croquet. {Victim} was killed during the game.',
      event: 'quarrel',
      intro: [
        'The court had gone out to the croquet ground, the hedgehogs for balls and the flamingos for mallets, and the game had been going for as long as anybody could say. By six the light was low and the sentences had been passed; at seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. The game is still on, in its way, and so is everybody who was playing it.',
      ],
    },
    {
      id: 'trial',
      weight: 3,
      titles: ['The Trial of the Tarts', 'Evidence {At} {Place}', 'The Verdict First'],
      sheet: 'The court of hearts was sitting on the matter of the tarts.',
      report: 'The court was sitting on the matter of the stolen tarts. {Victim} was killed during the sitting.',
      event: 'slam',
      motives: { exposed: 2, hostile: 2 },
      intro: [
        'The court of hearts had sat all afternoon on the matter of the tarts, with a jury of twelve and a verdict that had been decided before the evidence. The sitting rose at six. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Everybody who gave evidence is still in the court, and some of them are now witnesses to something else.',
      ],
    },
    {
      id: 'teaparty',
      weight: 2,
      titles: ['The Unbirthday Party', 'No Room {At} {Place}', 'Tea for Everybody'],
      sheet: 'It was the Unbirthday party, which is held on every day but one.',
      report: 'The Unbirthday party was in progress at the long table. {Victim} was killed during the tea.',
      event: 'walkout',
      motives: { jilted: 2, indebted: 1.5 },
      intro: [
        'It was the Unbirthday party, held on the three hundred and sixty-four days of the year that are nobody’s birthday, and it had been tea-time for some while. The cups had been moved on a place, as they always are, and at seven o’clock {victim} was found in {scene}, quite dead. It had been done {window}. The kettle is still warm, and nobody has been allowed to wash a thing.',
      ],
    },
  ],
  scenarioIntro: [
    'The summons went out to the whole of the court at five, and by six every creature of any account had come to the court of hearts and the dusk had come down on the garden. At seven o’clock {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left Wonderland, and nobody can.',
  ],
}
