// The steam yacht Corinthia, 1931: hove to in a gale off the Needles, and her
// owner dead below. One long alleyway, the cabins and saloons to either side,
// the deck at the stern.

import type { CharacterDef, SettingPack } from '../schema'
import { manor1920s } from '../manor1920s'

const of = (id: string) => manor1920s.characters.find((c) => c.id === id)!
const as = (id: string, patch: Partial<CharacterDef>): CharacterDef => ({ ...of(id), ...patch })

export const boat1926: SettingPack = {
  ...manor1920s,
  id: 'boat1926',
  title: 'The Yacht Corinthia, 1931',
  victims: [
    {
      id: 'vane',
      name: 'Mr. Cornelius Vane',
      shortName: 'Mr. Vane',
      title: 'owner of the Corinthia, and of the Vane Line',
      pronouns: 'he',
      firstName: 'Cornelius',
      lastName: 'Vane',
      respectful: 'the owner',
      parental: 'Father',
      children: ['ownerdaughter', 'ownerson'],
      occasions: ['cruise', 'passage', 'business', 'will', 'engagement'],
    },
    {
      id: 'thorne',
      name: 'Captain Josiah Thorne',
      shortName: 'the Captain',
      title: 'master of the Corinthia',
      pronouns: 'he',
      firstName: 'Josiah',
      lastName: 'Thorne',
      respectful: 'the Captain',
      parental: 'Father',
      character: 'captain',
      // Master of the ship: he could put a man ashore, and had crossed the owner's guests before; no will, no firm.
      motives: ['hostile', 'indebted', 'exposed', 'rival', 'jilted', 'dismissed'],
      occasions: ['cruise', 'passage'],
    },
    {
      id: 'trent',
      name: 'Mr. Hugo Trent',
      shortName: 'Mr. Trent',
      title: 'of the Vane Line’s board',
      pronouns: 'he',
      firstName: 'Hugo',
      lastName: 'Trent',
      respectful: 'Mr. Trent',
      parental: 'Father',
      character: 'trent',
      // On the board, and at odds with half the ship over it: cause enough in the City, but no blessing of his to refuse, nobody of his to dismiss.
      motives: ['hostile', 'indebted', 'exposed', 'rival', 'jilted', 'beneficiary'],
      occasions: ['cruise', 'passage', 'business'],
    },
    {
      id: 'askew',
      name: 'Mr. Leonard Askew',
      shortName: 'the purser',
      title: 'purser of the Corinthia',
      pronouns: 'he',
      firstName: 'Leonard',
      lastName: 'Askew',
      respectful: 'the purser',
      parental: 'Father',
      character: 'purser',
      // Kept the ship’s money and the ship’s books, and knew what was in both: nothing to leave, nobody to dismiss.
      motives: ['hostile', 'indebted', 'exposed', 'jilted'],
      occasions: ['cruise', 'passage', 'books'],
    },
  ],
  place: {
    name: 'the ship',
    here: 'this ship',
    people: 'the ship’s company',
    plan: 'the plan of the ship',
    gathering:
      'A gale in the rigging, the yacht hove to, and everybody aboard in the saloon, each with something to say before the questioning begins.',
    weather: 'the gale',
    one: 'passenger',
    ones: 'passengers',
    passage: 'the alleyway',
    placeName: 'the Corinthia',
    placeShort: 'Corinthia',
    at: 'aboard',
  },
  weather: 'gale',
  ambience: 'ocean',
  mapStyles: ['boat'],
  windowLabel: 'between three and four in the afternoon, while the ship was hove to',
  windowClock: 'Between 3 and 4 p.m. this afternoon',
  suspectsLine: 'The {n} guests aboard the yacht',
  chiefNote: 'She’ll be kept hove to until midnight, and no longer. You’ve got till then to find out who did it.',
  windowFrom: 'three o’clock',

  rooms: [
    {
      id: 'saloon',
      name: 'the saloon',
      searchFlavor: ['Brass, mahogany, and a decanter in its fiddle. The ship rolls; nothing else moves.', 'Cards on the table, a hand left face down.'],
    },
    {
      id: 'diningsaloon',
      name: 'the dining saloon',
      searchFlavor: ['The cloth is wet at one corner where the water came in. The rest is laid for eight.', 'Silver, cold soup, and the steward’s tray.'],
    },
    {
      id: 'smoking',
      name: 'the smoking room',
      searchFlavor: ['Leather chairs bolted to the deck, and a smell of cigars and salt.', 'An ashtray brimming. A chart, weighted at the corners.'],
    },
    {
      id: 'stateroom',
      name: 'the owner’s stateroom',
      searchFlavor: ['A bed like a hotel’s, a safe in the bulkhead, and photographs of ships.', 'The porthole is dogged shut. The lamp swings.'],
    },
    {
      id: 'cabin',
      name: 'the guest cabin',
      searchFlavor: ['Two berths, a basin, a trunk that has not been unpacked.', 'A lifebelt on its hook, and a book about lifebelts.'],
    },
    {
      id: 'galley',
      name: 'the galley',
      searchFlavor: ['Pans on their hooks, swinging; the range still warm.', 'Knives in a rack, a rack in a cage, and the cage unlocked.'],
    },
    {
      id: 'bridge',
      name: 'the bridge',
      searchFlavor: ['The wheel lashed, the binnacle glowing, and rain on the glass.', 'A log-book open. The last entry is the weather.'],
    },
    {
      id: 'deck',
      name: 'the promenade deck',
      where: 'on the promenade deck',
      kind: 'outdoor',
      searchFlavor: ['Wet planking, the rail, and the sea very close.', 'A deck-chair blown against the rail, and nobody in it.'],
    },
  ],
  sceneRooms: ['saloon', 'diningsaloon', 'smoking', 'stateroom', 'cabin', 'galley', 'bridge', 'deck'],
  valuableRooms: ['stateroom', 'cabin', 'saloon', 'bridge'],
  docRooms: ['stateroom', 'saloon', 'smoking', 'bridge'],

  means: [
    { id: 'stillroom', label: 'has a key to the ship’s medicine chest' },
    { id: 'firearms', label: 'knew where the bridge pistol was kept' },
    { id: 'strength', label: 'has the strength for a heavy blow' },
    { id: 'kitchen', label: 'has the run of the galley' },
    { id: 'motor', label: 'has sea-legs enough for the deck in a gale' },
  ],
  methods: [
    {
      id: 'poison',
      means: 'stillroom',
      weaponName: 'a bottle from the medicine chest, the seal broken and the level down',
      methodLine: 'poisoned by a hand with a key to the medicine chest',
      selfInflicted: true,
      titled: 'Poisoning',
      rooms: ['saloon', 'diningsaloon', 'smoking', 'stateroom', 'cabin', 'galley', 'bridge'],
    },
    {
      id: 'revolver',
      means: 'firearms',
      weaponName: 'the bridge pistol, one round spent, back in its locker',
      methodLine: 'shot by somebody who knew where the pistol was kept',
      selfInflicted: true,
      titled: 'A Shot',
    },
    {
      id: 'bludgeon',
      means: 'strength',
      weaponName: 'a belaying pin, wiped ill and put back in the rack',
      methodLine: 'struck down by someone with the strength for it',
      titled: 'The Belaying Pin',
      rooms: ['saloon', 'diningsaloon', 'smoking', 'stateroom', 'cabin', 'bridge'],
    },
    {
      id: 'cord',
      means: 'strength',
      weaponName: 'a length of halyard, cut and knotted',
      methodLine: 'strangled by someone with the strength for it',
      titled: 'The Halyard',
      rooms: ['saloon', 'diningsaloon', 'smoking', 'stateroom', 'cabin', 'bridge'],
    },
    {
      id: 'knife',
      means: 'kitchen',
      weaponName: 'a galley knife, rinsed and put back in the rack wet',
      methodLine: 'stabbed by someone with the run of the galley',
      titled: 'The Knife',
    },
    {
      id: 'fall',
      means: 'motor',
      weaponName: 'the rail, and a torn cuff caught on the cleat below it',
      methodLine: 'put over the side by somebody who could keep their feet on the deck',
      titled: 'Overboard',
      rooms: ['deck'],
    },
  ],

  characters: [
    as('captain', { title: 'master of the Corinthia', blurb: 'Has been round the Horn four times, and does not care for the owner’s guests on his bridge.' }),
    as('ellison', { title: 'the ship’s doctor' }),
    as('colonel', { title: 'the owner’s guest' }),
    as('vivienne', { title: 'the owner’s guest' }),
    as('josephine', { title: 'singing for her passage' }),
    as('trent', { title: 'of the Vane Line’s board', blurb: 'On the board of the line, and lately at odds with its owner over every item on the agenda.' }),
    as('barrow', { title: 'the owner’s solicitor' }),
    as('dowager', { title: 'the owner’s aunt, a bad sailor' }),
    as('explorer', { title: 'working his passage to Madeira' }),
    as('hunter', { title: 'the owner’s guest' }),
    as('medium', { title: 'engaged for the voyage' }),
    as('heiress', { title: 'the owner’s guest' }),
    as('daughter', { id: 'ownerdaughter', name: 'Miss Violet Vane', shortName: 'Miss Vane', title: 'the owner’s daughter' }),
    as('son', { id: 'ownerson', name: 'Mr. Julian Vane', shortName: 'Mr. Vane, junior', title: 'the owner’s son' }),
    {
      id: 'purser',
      name: 'Mr. Leonard Askew',
      shortName: 'the purser',
      title: 'the purser',
      portrait: '📒',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.5, perfume: 0.1, spectacles: 0.7, gloves: 0.4 },
      means: ['stillroom', 'firearms'],
      manners: { official: 0.8, deferential: 0.5, gracious: 0.3 },
      motives: { exposed: 0.9, indebted: 0.7, dismissed: 0.7, hostile: 0.3 },
      voice: { pitch: 170, wave: 'triangle', lilt: 1.5, clip: 0.09, ring: 0.5 },
      blurb: 'Keeps the ship’s money and the ship’s books, and the two have not always agreed.',
    },
    {
      id: 'attendant',
      name: 'Wilf Hoskins',
      shortName: 'the steward',
      title: 'the saloon steward',
      portrait: '🍽️',
      pronouns: 'he',
      station: 'servant',
      leanings: { cane: 0.1, smoker: 0.6, perfume: 0.05, spectacles: 0.2, gloves: 0.8 },
      means: ['kitchen', 'strength'],
      manners: { deferential: 0.8, cheeky: 0.6, gossipy: 0.4 },
      motives: { dismissed: 0.9, hostile: 0.5, indebted: 0.5, exposed: 0.4 },
      voice: { pitch: 178, wave: 'square', lilt: 2.5, clip: 0.07, ring: 0.5 },
      blurb: 'Carries a tray through a gale without spilling a drop, and hears everything said over one.',
    },
  ],
  silhouettes: {
    ...manor1920s.silhouettes,
    ownerdaughter: manor1920s.silhouettes!.daughter,
    ownerson: manor1920s.silhouettes!.son,
  },

  flavorItems: [
    'a chart of the Solent, pencilled over',
    'a lifebelt stencilled CORINTHIA',
    'a novel swollen with damp',
    'a deck-quoit',
    'a menu in French, spotted with soup',
  ],
  passageItem: 'a hatch in the panelling, and a ladder down to the alleyway beneath',
  bribeItem: 'an envelope of banknotes, with {name}’s name on it, wedged behind a lifebelt',
  occasions: [
    {
      id: 'cruise',
      weight: 3,
      titles: ['The Last Cruise of {Place}', 'Hove To', 'Eight Bells'],
      sheet: 'The owner had {his} guests aboard for a week’s cruise.',
      report: 'The owner’s guests were aboard for a week’s cruise. {Victim} was killed after a gale forced the ship to heave to.',
      event: 'quarrel',
      intro: [
        'The glass fell all morning, and by two the Corinthia was hove to off the Needles, her guests below and the sea coming green over the bow. It was not weather for a pleasure cruise. At half past four {victim} was found in {scene}, quite dead, and not by any accident of the sea. Nobody has left the ship. Nobody could.',
        'A yacht, a gale, and eight people who cannot get off. {victim} was found in {scene}, the deed done {window}. At sea one cannot simply walk away from a murder, and neither, tonight, can the murderer.',
      ],
    },
    {
      id: 'passage',
      weight: 2,
      titles: ['The Passage to Madeira', 'Green Water', 'Two Days Out'],
      sheet: 'The Corinthia was two days out, bound for Madeira with the owner’s guests aboard.',
      report: '{Victim} was aboard for the passage to Madeira. {He} was killed after a gale forced the ship to heave to.',
      event: 'quarrel',
      intro: [
        'Two days out and bound for Madeira, with the owner’s guests below and the glass falling all morning: by two the Corinthia was hove to, the sea coming green over the bow. At half past four {victim} was found in {scene}, quite dead, and not by any accident of the sea. It had been done {window}. Nobody has left the ship. Nobody could.',
      ],
    },
    {
      id: 'business',
      weight: 2,
      titles: ['The Vane Line', 'A Matter of Business {At} {Place}'],
      sheet: 'The owner had the board of the Vane Line aboard to settle its affairs.',
      report: 'The board of the Vane Line was aboard to settle the line’s affairs. {Victim} was killed before the matter was concluded.',
      event: 'telephone',
      motives: { rival: 3, indebted: 2, exposed: 1.5 },
      intro: [
        'The board of the Vane Line, the solicitor, and the wireless crackling all day with the City: the owner had brought them aboard to settle the line’s affairs somewhere nobody could storm out. Then the gale came up, and at half past four {victim} was found in {scene}, quite dead. Nobody can storm out now, either.',
      ],
    },
    {
      id: 'books',
      weight: 2,
      titles: ['The Ship’s Books', 'A Matter of the Ledger', 'Eight Bells, and the Accounts'],
      sheet: 'The ship’s accounts were to be gone over before Madeira, and every book the purser kept laid on the saloon table.',
      report: '{Victim} had been over the ship’s books, and had asked to see several of those aboard about what {he} found there. {He} was killed before {he} could.',
      event: 'quarrel',
      motives: { exposed: 3, indebted: 2 },
      intro: [
        '{victim} kept the ship’s money and the ship’s books, and that morning {he} had let it be known that the two did not agree, and that {he} meant to say so before Madeira. The gale had the Corinthia hove to by two. At half past four {he} was found in {scene}, quite dead, and the ledger open on the desk. Whoever it would have named is still aboard.',
      ],
    },
    {
      id: 'will',
      weight: 2,
      titles: ['The {LastName} Inheritance', 'The Unsigned Will'],
      sheet: 'The owner meant to sign a new will aboard, with {his} solicitor to witness it.',
      report: '{Victim} meant to sign a new will aboard, with {his} solicitor to witness it. {He} was killed before {he} was able to do so.',
      event: 'slam',
      motives: { disinherited: 3, beneficiary: 3 },
      intro: [
        '{victim} had a new will drawn and meant to sign it aboard tonight, with everybody who had an interest in the old one sitting round the saloon table. The sea got up first. At half past four {he} was found in {scene}, quite dead, and the will unsigned. Somebody aboard had decided the old will would do very nicely.',
      ],
    },
    {
      id: 'engagement',
      weight: 2,
      titles: ['The {LastName} Engagement', 'No Toast {At} {Place}'],
      sheet: 'The cruise was to end with an engagement announced at dinner.',
      report: '{Victim}’s cruise was to end with an engagement, to which {he} had refused {his} blessing. {He} was killed before the announcement was made.',
      event: 'walkout',
      motives: { forbidden: 3, jilted: 2 },
      intro: [
        'An engagement was to be announced at dinner, and the champagne was already in the fiddles. But that afternoon {victim} had let it be known that {he} would not give {his} blessing. Then came the gale, and no dinner at all. At half past four {he} was found in {scene}, quite dead.',
      ],
    },
  ],
  scenarioIntro: [
    'The gale had the ship hove to by two. At half past four {victim} was found in {scene}, quite dead, and plainly not by accident. It had been done {window}. Nobody has left the ship.',
  ],
}
